### ISSUE TITLE
Webpack build

### ISSUE THREAD

**Issue by berchik** [NativeScript/sidekick-feedback#10]
What about webpack builds? Since sidekick is using the CLI it should'nt be too difficult to add this option. Otherwise the builds are fairly pointless for angular project types due to performance issues.
Thanks.

**Comment by teobugslayer** [comment]
@berchik , how are you using Webpack? Do you use it during development, i.e. with LiveSYnc in debug configuration? Or you need it only for the Release build before publishing to the app stores?

**Comment by berchik** [comment]
I enable webpack in my development with the nativescript-dev-webpack plugin, but develop with the emulator using the normal ‘tns run..’ for running/livesync.

However, to build/test/bundle on a device I use ‘npm run build-android-bundle --uglify’. This is needed for the final publishing of course, but also for real device testing.

**Comment by teobugslayer** [comment]
Thank you for the feedback. We are working on implementing Webpack in the cloud builds and your information helps a lot.

**Comment by gabitoesmiapodo** [comment]
+1

Webpack support would be great. I use it mostly for release builds.

**Comment by LeopoldPodmolik** [comment]
+1

**Comment by joshcomley** [comment]
Any news on webpack support?

**Comment by Universi** [comment]
+1

**Comment by david-quadpro** [comment]
I am using WebPack and build for iOS via Sidekick as I don't have a Mac. Where is this up to?

**Comment by ahitrov** [comment]
Hi @david-quadpro ,

Sidekick supports building with Webpack for release since **1.2.0-v.2018.1.22.1**. More info [here](https://docs.nativescript.org/sidekick/user-guide/build-app/webpack).

We are adding support for building with Webpack for debug in the next release of Sidekick due next week.

Cheers

**Comment by umutesen** [comment]
@ahitrov 

> Custom webpack settings
>  In this field, you can provide various custom webpack settings in JSON format.

How would I pass flags like `--bundle --env.apiUrl=value`?
