### ISSUE TITLE
New app fails to build

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/sidekick-feedback#102]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
This is my first time using Sidekick. I made a new project, clicked to create. And then... nothing. I can see an error (I assume) in the background, and I assume I can click the X to close the dialog, but right now something has gone wrong and the app isn't being helpful about what to do next. Screenshot:

![image](https://user-images.githubusercontent.com/393660/33618820-35d4fae8-d9a9-11e7-9538-507bce50cb1e.png)

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:

Version: 1.0.1-v.2017.11.16.1 (latest)
NativeScript CLI version: 3.3.1
CLI extension nativescript-cloud version: 1.0.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
I did above. :)

### Does this issue happen every time?
This is my first time using it.

### Send the client logs.
https://gist.github.com/cfjedimaster/6658900721bbd8a6f5d6617a704e8187

**Comment by cfjedimaster** [comment]
I closed the top window, looked at console, and saw this:

[17-12-05 10:40:37.721] (Error) Command npm.cmd install failed with exit code 1 Error output: Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node": 
 
 HTTP error 404 Not Found
 
 Hint: If github.com is not accessible in your location
 try setting a proxy via HTTP_PROXY, e.g. 
 
 export HTTP_PROXY=http://example.com:1234
 
 or configure npm proxy via
 
 npm config set proxy http://example.com:8080 gyp info it worked if it ends with ok gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe', gyp verb cli 'C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\node-gyp\\bin\\node-gyp.js', gyp verb cli 'rebuild', gyp verb cli '--verbose', gyp verb cli '--libsass_ext=', gyp verb cli '--libsass_cflags=', gyp verb cli '--libsass_ldflags=', gyp verb cli '--libsass_library=' ] gyp info using node-gyp@3.6.2 gyp info using node@9.2.0 | win32 | x64 gyp verb command rebuild [] gyp verb command clean [] gyp verb clean removing "build" directory gyp verb command configure [] gyp verb check python checking for Python executable "python2" in the PATH gyp verb `which` failed Error: not found: python2 gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed python2 { Error: not found: python2 gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed stack: 'Error: not found: python2\n at getNotFoundError (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:13:12)\n at F (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:68:19)\n at E (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:80:29)\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:89:16\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\index.js:42:5\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\windows.js:36:5\n at FSReqWrap.oncomplete (fs.js:166:21)', gyp verb `which` failed code: 'ENOENT' } gyp verb check python checking for Python executable "python" in the PATH gyp verb `which` failed Error: not found: python gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed python { Error: not found: python gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed stack: 'Error: not found: python\n at getNotFoundError (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:13:12)\n at F (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:68:19)\n at E (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:80:29)\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:89:16\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\index.js:42:5\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\windows.js:36:5\n at FSReqWrap.oncomplete (fs.js:166:21)', gyp verb `which` failed code: 'ENOENT' } gyp verb could not find "python". checking python launcher gyp verb could not find "python". guessing location gyp verb ensuring that file exists: C:\Python27\python.exe gyp ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. gyp ERR! stack at PythonFinder.failNoPython (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\node-gyp\lib\configure.js:483:19) gyp ERR! stack at PythonFinder.<anonymous> (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\node-gyp\lib\configure.js:508:16) gyp ERR! stack at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\graceful-fs\polyfills.js:284:29 gyp ERR! stack at FSReqWrap.oncomplete (fs.js:166:21) gyp ERR! System Windows_NT 10.0.16299 gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" gyp ERR! cwd C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\node-sass gyp ERR! node -v v9.2.0 gyp ERR! node-gyp -v v3.6.2 gyp ERR! not ok Build failed with error code: 1 npm WARN Error: EPERM: operation not permitted, lstat 'C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\cryptiles\node_modules' npm WARN { Error: EPERM: operation not permitted, lstat 'C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\cryptiles\node_modules' npm WARN stack: 'Error: EPERM: operation not permitted, lstat \'C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\cryptiles\\node_modules\'', npm WARN errno: -4048, npm WARN code: 'EPERM', npm WARN syscall: 'lstat', npm WARN path: 'C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\cryptiles\\node_modules' } npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the node-sass@4.5.3 postinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\ray\AppData\Roaming\npm-cache\_logs\2017-12-05T16_40_33_708Z-debug.log , Error: Command npm.cmd install failed with exit code 1 Error output: Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node": 
 
 HTTP error 404 Not Found
 
 Hint: If github.com is not accessible in your location
 try setting a proxy via HTTP_PROXY, e.g. 
 
 export HTTP_PROXY=http://example.com:1234
 
 or configure npm proxy via
 
 npm config set proxy http://example.com:8080 gyp info it worked if it ends with ok gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe', gyp verb cli 'C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\node-gyp\\bin\\node-gyp.js', gyp verb cli 'rebuild', gyp verb cli '--verbose', gyp verb cli '--libsass_ext=', gyp verb cli '--libsass_cflags=', gyp verb cli '--libsass_ldflags=', gyp verb cli '--libsass_library=' ] gyp info using node-gyp@3.6.2 gyp info using node@9.2.0 | win32 | x64 gyp verb command rebuild [] gyp verb command clean [] gyp verb clean removing "build" directory gyp verb command configure [] gyp verb check python checking for Python executable "python2" in the PATH gyp verb `which` failed Error: not found: python2 gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed python2 { Error: not found: python2 gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed stack: 'Error: not found: python2\n at getNotFoundError (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:13:12)\n at F (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:68:19)\n at E (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:80:29)\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:89:16\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\index.js:42:5\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\windows.js:36:5\n at FSReqWrap.oncomplete (fs.js:166:21)', gyp verb `which` failed code: 'ENOENT' } gyp verb check python checking for Python executable "python" in the PATH gyp verb `which` failed Error: not found: python gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed python { Error: not found: python gyp verb `which` failed at getNotFoundError (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:13:12) gyp verb `which` failed at F (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:68:19) gyp verb `which` failed at E (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:80:29) gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\which\which.js:89:16 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\index.js:42:5 gyp verb `which` failed at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\isexe\windows.js:36:5 gyp verb `which` failed at FSReqWrap.oncomplete (fs.js:166:21) gyp verb `which` failed stack: 'Error: not found: python\n at getNotFoundError (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:13:12)\n at F (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:68:19)\n at E (C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:80:29)\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\which\\which.js:89:16\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\index.js:42:5\n at C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\isexe\\windows.js:36:5\n at FSReqWrap.oncomplete (fs.js:166:21)', gyp verb `which` failed code: 'ENOENT' } gyp verb could not find "python". checking python launcher gyp verb could not find "python". guessing location gyp verb ensuring that file exists: C:\Python27\python.exe gyp ERR! configure error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. gyp ERR! stack at PythonFinder.failNoPython (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\node-gyp\lib\configure.js:483:19) gyp ERR! stack at PythonFinder.<anonymous> (C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\node-gyp\lib\configure.js:508:16) gyp ERR! stack at C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\graceful-fs\polyfills.js:284:29 gyp ERR! stack at FSReqWrap.oncomplete (fs.js:166:21) gyp ERR! System Windows_NT 10.0.16299 gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" gyp ERR! cwd C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\node-sass gyp ERR! node -v v9.2.0 gyp ERR! node-gyp -v v3.6.2 gyp ERR! not ok Build failed with error code: 1 npm WARN Error: EPERM: operation not permitted, lstat 'C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\cryptiles\node_modules' npm WARN { Error: EPERM: operation not permitted, lstat 'C:\Users\ray\Documents\NSSidekick\app1\app1\node_modules\cryptiles\node_modules' npm WARN stack: 'Error: EPERM: operation not permitted, lstat \'C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\cryptiles\\node_modules\'', npm WARN errno: -4048, npm WARN code: 'EPERM', npm WARN syscall: 'lstat', npm WARN path: 'C:\\Users\\ray\\Documents\\NSSidekick\\app1\\app1\\node_modules\\cryptiles\\node_modules' } npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the node-sass@4.5.3 postinstall script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\ray\AppData\Roaming\npm-cache\_logs\2017-12-05T16_40_33_708Z-debug.log at ChildProcess.childProcess.on (C:\Users\ray\AppData\Roaming\npm\node_modules\nativescript\lib\node-package-manager.js:236:36) at ChildProcess.emit (events.js:159:13) at maybeClose (internal/child_process.js:943:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
 DEVICES  OUTPUT 1

**Comment by MartoYankov** [comment]
hey @cfjedimaster 

Thank you for reporting this. It seems you are using node 9 and it doesn't work with the version of "node-sass" specified in the app package.json. We will patch the templates. In the meantime, you can install the latest version of node-sass using ```npm install node-sass --save-dev```. This should fix the issue.

**Comment by cfjedimaster** [comment]
Did you mean globally?

**Comment by cfjedimaster** [comment]
Obviously yes. ;) Working now - thank you.

**Comment by cfjedimaster** [comment]
Thanks!
