### ISSUE TITLE
Spaces in Sidekick path causes problem on Linux (xcfe window manager)

### ISSUE THREAD

**Issue by yonghongren** [NativeScript/sidekick-feedback#104]
Installed sidekick on Ubuntu 16.4 with XCFE window manager:
   sudo dpkg -i  ~/Downloads/NativeScriptSidekick-amd64.deb

Sidekick sets up a menu entry under Development, but selecting it would get:

Failed to execute command "/opt/NativeScript Sidekick/NativeScript Sidekick %F".

Renaming /opt/NativeScript Sidekick/NativeScript Sidekick to /opt/NativeScriptSidekick/NativeScriptSidekick and changing the menu entry to match gets Sidekick to launch correctly.

**Comment by tsvetie** [comment]
Hey @yonghongren, thank you for reporting this, we will look into it.
