### ISSUE TITLE
Debug process shut down due to:  java.io.FileNotFoundException: /data/anr/traces.txt: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/sidekick-feedback#107]
### Did you verify whether this issue has already been reported here?
Yes. No similar issues reported here 

### Tell us about the problem.
In Run on device tab, I could-built project. When LiveSync starts, I open debug window. However, debugging process is always shut down. 

### Which platform(s) does the issue occur on?
Android
 5.0.1 
Windows
Windows 10 

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick:** Version: 1.0.1-v.2017.11.16.1 (latest)
- **NativeScript CLI:** NativeScript CLI version: 3.3.0
- **CLI extension nativescript-cloud:** CLI extension nativescript-cloud version: 1.0.0
- **CLI extension nativescript-starter-kits:** CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application 
2. build 
3. open chrome dev tool 

### Does this issue happen every time?
Yes

### Send the client logs.
There is log snippet as follow, 
ActivityManager: Error reading /data/anr/traces.txt
ActivityManager: java.io.FileNotFoundException: /data/anr/traces.txt: open failed: ENOENT (No such file or directory)
ActivityManager: 	at libcore.io.IoBridge.open(IoBridge.java:456)
ActivityManager: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
ActivityManager: 	at android.os.FileUtils.readTextFile(FileUtils.java:227)
ActivityManager: 	at com.android.server.am.ActivityManagerService$19.run(ActivityManagerService.java:12053)
ActivityManager: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
ActivityManager: 	at libcore.io.Posix.open(Native Method)
ActivityManager: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
ActivityManager: 	at libcore.io.IoBridge.open(IoBridge.java:442)
ActivityManager: 	... 3 more
ActivityManager:   Force finishing activity 1 com.project.app/com.tns.NativeScriptActivity
ActivityManager: Killing 7145:com.project.app/u0a162 (adj 0): user request after error

**Comment by ahitrov** [comment]
Hi @AshleyCao ,

I wasn't able to reproduce the issue with neither of the templates.

Does this happen also when you start the debugger directly from the Run on Device screen (by checking the Start debugger checkbox)?

Can you provide a cut-down app that reproduces the problem?

Thanks
