### ISSUE TITLE
iOS cloud build fails after adding and then removing nativescript-nodeify

### ISSUE THREAD

**Issue by Andrea65** [NativeScript/sidekick-feedback#109]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem.
I added nativescript-nodeify plugin to my app.
I then removed the plugin. 
There is no trace of the plugin in package.json nor in package-lock.json nor in node_modules
During cloud build it fail with error

npm ERR! addLocal Could not install /private/tmp/builds/_/16f5dc9be44c0db54d4b5fc7ea78027f7764defa/ENEA/node_modules/jszip/nativescript-nodeify/node_modules/readable-stream@*

it was functioning some days ago

### Which platform(s) does the issue occur on?
_iOS
_Windows

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
 1.0.1-v.2017.11.16.1
- **NativeScript CLI:** 
 3.3.1.

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

[cli_17-12-14_17-54-53.934.log](https://github.com/NativeScript/sidekick-feedback/files/1560146/cli_17-12-14_17-54-53.934.log)

**Comment by ventsislav-georgiev** [comment]
@Andrea65 Could you try the Clean Build option and see if the issue persists. When you enable the Clean Build option, any previously cached data will be ignored and the application will undergo a complete rebuild. This type of build will not take advantage of certain optimizations and may take longer to finish.
