### ISSUE TITLE
Certificate Expired on iOS Cloud Build

### ISSUE THREAD

**Issue by wiwski** [NativeScript/sidekick-feedback#111]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I'm trying to run on my iPhone an app with an auto-generated certificate. It worked the first time (last week) but now it complains the certificate has expired.

### Which platform(s) does the issue occur on?
iOS 10.3.3
Window 10

### Provide the following version numbers that the issue occurs with:

Version: 1.1.0-v.2017.12.21.2 (latest)
NativeScript CLI version: 3.4.0
CLI extension nativescript-cloud version: 1.2.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Open the App Folder
2. Run on Device
3. Click on iOS Auto Generate Provisioning Profile and Certificate
4. Successfuly generate certificate
5. Select Cloud Build, Debug Configuration, with our without Clean Build, with or without Debugger
6. Run on Device
7. Error

### Does this issue happen every time?
Yes

### Send the client logs.

...
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Project successfully prepared (iOS)
Starting cloud build of 'C:\Users\witol\Documents\scoolapp\scoolapp', platform: 'iOS', configuration: 'Debug', buildId: 4fc3a082-5f26-4312-b244-f3e34aae403f.
Unable to apply changes on device: 19eedeefc379f02010040e4babcf8a8c9585c91d. Error is: The specified certificate: C:\...\CodeSigning\...\ios\cert.p12 has expired.
Executing after-watch hook from C:\...\hooks\after-watch\nativescript-dev-typescript.js

**Comment by tsvetie** [comment]
Hi @wiwski, the generated certificates are temporary. In order to fix this, you need to re-generate the certificate. Just open the configuration window for the device (hover over the device in the Run on Device view and click the configuration wheel) and delete the currently selected certificate. Then you can generate it just as you did the first time.

**Comment by wiwski** [comment]
Hi @tsvetie, thank you for the answer ! Unfortunately I already did. I tried several times. I even tried with another Apple account. 
Could it be an app version issue ?

**Comment by Mitko-Kerezov** [comment]
Hello @wiwski,
Prior to building, NativeScript Sidekick verifies the certificate passed in a number of ways. The expiration validation is namely whether `Date.now()` is in the time frame designated by the certificate's `notBefore` and `notAfter` properties.
Auto-generated certificates are valid for one year, so you're unlikely to exceed the `notAfter`.
Could you verify your system's clock, check to see whether it has been **set back**. If it has your `Date.now()` would be placed before the `notBefore` property and you would get the expiration error.

**Comment by glorious73** [comment]
> Hello @wiwski,
> Prior to building, NativeScript Sidekick verifies the certificate passed in a number of ways. The expiration validation is namely whether `Date.now()` is in the time frame designated by the certificate's `notBefore` and `notAfter` properties.
> Auto-generated certificates are valid for one year, so you're unlikely to exceed the `notAfter`.
> Could you verify your system's clock, check to see whether it has been **set back**. If it has your `Date.now()` would be placed before the `notBefore` property and you would get the expiration error.

I checked my system's clock and it was indeed lagging behind. Once that was fixed the build completed successfully. Thanks!
