### ISSUE TITLE
VS2017 Plugin

### ISSUE THREAD

**Issue by Czaste** [NativeScript/sidekick-feedback#112]
### Tell us about the problem.
Last word about this was November 7th. With this available, working on .Net CORE integrated Angular/Nativescript apps would be much easier. Any hints of when this will be released? Or even available for beta testing?

Thanks!

**Comment by ahitrov** [comment]
Hi @Czaste ,

The **NativeScript Sidekick extension for Visual Studio 2017** is currently available as part of a closed beta access program.

You can contact our product manager @teobugslayer at todor.totev@progress.com for more information on how to participate.

Thank you for your interest!

**Comment by teobugslayer** [comment]
Hey all,

We will release the preview of the Visual Studio extension on April 17th. Please, write to me on the mail address above if you want to test it.
