### ISSUE TITLE
add this configuration for push notification

### ISSUE THREAD

**Issue by runbb** [NativeScript/sidekick-feedback#118]
### Did you verify whether this issue has already been reported here?
No

### Tell us about the problem.

I need this configuration for onesignal push notification on nativescript sidekick
![screenshot_20180110_040810](https://user-images.githubusercontent.com/20779154/34751153-0d867cea-f5bc-11e7-82d1-5d0be7e21e06.png)

### Which platform(s) does the issue occur on?
iOS
Multiple

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.1.1-v.2018.1.4.6 (latest)
- **NativeScript CLI:** 3.4.0
- **CLI extension nativescript-cloud:** 1.2.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Does this issue happen every time?
Yes

**Comment by tsvetie** [comment]
Hey @runbb,

You can enable push notifications in your NativeScript app using the nativescript-push-notifications plugin. You can find details about this plugin and how to configure it here - [https://github.com/NativeScript/push-plugin](https://github.com/NativeScript/push-plugin).

To enable OneSignal Push Notifications in your NativeScript app, you can use the nativescript-onesignal plugin - [https://github.com/roblav96/nativescript-onesignal](https://github.com/roblav96/nativescript-onesignal). Documentation is located here - [https://documentation.onesignal.com/docs/ios-native-sdk](https://documentation.onesignal.com/docs/ios-native-sdk).

Now, regarding your feature request - could you provide a bit more information on what you expect? For now, I can tell you that we already have the support for entitlements file in the Sidekick backlog of features - to visualize and modify. Is that the feature you request?

**Comment by runbb** [comment]
You have fixed the problem by adding a file 
`app.entitlements` in `App/App_Resources/iOS`

And notifications work

**Comment by ggarabedian** [comment]
Hello @runbb,

Thank you for letting us know and apologies for the delay in our response. The addition of the .entitlements file is not directly related to Sidekick, nevertheless, we are happy to hear that the reported issue is now resolved. 

The issue does not seem to be relevant anymore and I am going to close it.
