### ISSUE TITLE
SideKick: Can you add ability to Pull/Push/Commit to Github just like AppBuilder?

### ISSUE THREAD

**Issue by relvis** [NativeScript/sidekick-feedback#120]
Would be cool to have the ability to Pull/Push/Commit to Github just like AppBuilder app has.

Thanks!

**Comment by tsvetie** [comment]
Hey @relvis,

This feature request is not in the scope of the Sidekick product as we see it currently. Let's see if your request will spark interest in other users as well.

**Comment by teobugslayer** [comment]
Hello @relvis ,

I think using a capable Git UI client is much better approach than trying to do it inside Sidekick. Sidekick's focus is on device management, easy builds and quick app creation / development.

We deliberately avoid expanding it towards IDE features, like code editing or source control management. We know that rich IDEs and code editors already cover these better than we could. Instead, we augment them.

Personally, I am happy user of git gui (the built-in GUI inside the git command) but SourceTree and Visual Studio Code's source control are also very capable tools, depending on your needs.

I am closing this issue now.
