### ISSUE TITLE
Timeout trying to install NativeScript CLI (which is already installed anyway)

### ISSUE THREAD

**Issue by Landcross** [NativeScript/sidekick-feedback#128]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
After installing NativeScript Sidekick it asks to install the NativeScript CLI. After pressing install it starts loading for a few minutes until it shows a notification with the message: 'Error: Timeout has occured'

There are 2 problems here:

- The CLI installation fails.
- The CLI is already installed anyway because I tried NativeScript without Sidekick before. The installed CLI version matches the version that SideKick is trying to install.

The problem occurs on two different systems here.

### Which platform(s) does the issue occur on?
Windows 10 Enterprise

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick:** 1.4.0-v2018296
- **NativeScript CLI:** 3.4.2

### Tell us how to recreate the issue in as much detail as possible.
1. Install SideKick / Start SideKick.
2. Press install on the question to install the nativescript CLI.

### Does this issue happen every time?
Yes

### Send the client logs.
https://gist.github.com/Landcross/1412c2d38e786ce6075c63a2fb018415

**Comment by tsvetie** [comment]
Hello @Landcross,

It seems that for some reason, NS Sidekick cannot detect your installation of NS CLI. Can you give me a bit more information how you installed NS CLI? Additionally, can you send me all log files - I am particularly interested in the log files with name starting with "prerequisites" and "console". The "console" log gives information about the process.env of the Sidekick process so you can inspect it yourself as well.

Just to note - we have had issues in case people use yarn to install NS CLI. You should use NPM to install NS CLI globally.

**Comment by Landcross** [comment]
I installed NativeScript using the following command (from the installation guide on the site):
`npm install -g nativescript`

The prerequisites log: https://gist.github.com/Landcross/6b66db4aa660134123ea28733c6e0cb3
The console log: https://gist.github.com/Landcross/662e4f2538bdee1cd7b5acee76f90e19

**Comment by jkossis** [comment]
Any luck? Having the same issue with the timeout, but I don't have NativesScript previously installed.

**Comment by Landcross** [comment]
Just tried the new 1.5.0 release and it still doesn't work (as I expected, since it doesn't mention any fixes in the changelog, but I figured I'd mention anyway).

**Comment by UtsavPreet** [comment]
Yes 
I'm also facing the same timeout issue (I'm running Mac OS)
Is it some issue with the global variables ? that the software can't set the cli to be globally available ?

**Comment by UtsavPreet** [comment]
Yes 
I'm also facing the same timeout issue (I'm running Mac OS)
Is it some issue with the global variables ? that the software can't set the cli to be globally available ?

**Comment by tsvetie** [comment]
Hey all, the originally reported problem is the same as this one #129. It is fixed in the latest version of NS Sidekick.
