### ISSUE TITLE
Sidekick install error: Cannot find module index.js (app-1.3.0-v2018222)

### ISSUE THREAD

**Issue by aff** [NativeScript/sidekick-feedback#129]
## Please, provide the details below:
![image](https://user-images.githubusercontent.com/75700/36340185-d6791f70-13d7-11e8-9675-0ba17614f3df.png)
[prerequisites_18-02-17_11-35-03.zip](https://github.com/NativeScript/sidekick-feedback/files/1733585/prerequisites_18-02-17_11-35-03.zip)

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\Thea\AppData\Local\NativeScriptSidekick\app-1.3.0-v2018222\resources\index.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Install fails, logs attached. 

### Which platform(s) does the issue occur on?
PS C:\Users\Thea> gwmi win32_operatingsystem |
>> select PSComputerName, caption, OSArchitecture, Version, BuildNumber | fl
>>
PSComputerName : THEA-PC
caption        : Microsoft Windows 8.1 Pro
OSArchitecture : 64-biters
Version        : 6.3.9600
BuildNumber    : 9600

### Provide the following version numbers that the issue occurs with:
app-1.3.0-v2018222
(Edit: reproduced with app-1.5.0-v20182153)

### Tell us how to recreate the issue in as much detail as possible.
Execute NativeScriptSidekickSetup.exe

### Does this issue happen every time?
Yes/

### Send the client logs.
Attached. 

Thank you for creating and supporting NativeScript and Sidekick!

**Comment by tsvetie** [comment]
Hello @aff ,

It seems that you have found a bug. This is a little embarrassing :smile:. I will look into it and update the status of this item once we fix it.

For the time being, your only option to use NativeScript Sidekick, is to install NodeJS and NativeScript CLI manually:
1. For NodeJS, you can download an installer from here: https://nodejs.org/en/download/
2. After you install NodeJS, open a command prompt and run the following command:
```
npm install -g nativescript
```

After you do this, you should be able to use Sidekick.

**Comment by tsvetie** [comment]
Hey @aff , I found the cause for the problem. The fix will be available with our next release
