### ISSUE TITLE
Not getting local npm packages from parent folder

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/sidekick-feedback#13]
I'm trying to build an app which has some dependencies to a local npm package located in the ../packages/ folder I'm getting the following error:
`[17-08-01 17:13:56.015] (Info) npm ERR! enoent ENOENT: no such file or directory, open '/private/tmp/builds/_/5568ba84fe26527dac52213c8ba07f9e9297e59f/plugins/MyCustomPlugin.tgz`
The plugin is referred in the package.json file with this row:
` "MyCustomPlugin": "../plugins/MyCustomPlugin.tgz",`
Is it possible to get those plugins from the parent folder if the SideKick has access to them?

**Comment by stoskov** [comment]
Hi @vtrifonov. This is not supported currently.

**Comment by bundyo** [comment]
This is a duplicate of #55, which is better described.
