### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ochemerys** [NativeScript/sidekick-feedback#132]
## Please, provide the details below:
Sidekick Getting Started Guide build iOS on attached device iPhone 5s Error

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I started with Sidekick Getting Started Guide  https://docs.nativescript.org/sidekick/getting-started/
when I try to build iOS on attached device iPhone 5s I have build error:
[18-03-03 15:39:16.523] (Error) Command pod failed with exit code 31 Error output: 
 
[!] Automatically assigning platform `ios` with version `8.0` on target `skexample` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

the same error for local and cloud builds

### Which platform(s) does the issue occur on?
iOS
macOS Version 10.13.3

### Provide the following version numbers that the issue occurs with:

Version: 1.5.1-v.2018.2.26.1 (latest)
NativeScript CLI version: 3.4.2
CLI extension nativescript-cloud version: 1.3.1
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Follow steps Sidekick Getting Started Guide
2. Configured Code signing
3. Selected Build on iOS

attached device:

Model: | iPhone 5s (A1433/A1453)
-- | --
Name: | Oleks Chemerys’s iPhone
OS Version: | 11.2.6
Vendor: | Apple
Identifier: | fcda050d91aa95e3cedc73ee59467601fbdbd2b3
Platform: | iOS

### Does this issue happen every time?
Yes

### Send the client logs.
attached:
[main_18-03-03_15-14-15.332.log](https://github.com/NativeScript/sidekick-feedback/files/1778012/main_18-03-03_15-14-15.332.log)

**Comment by ahitrov** [comment]
Hi @ochemerys,

can you provide us with the corresponding CLI log located in ~/Library/Application Support/NativeScriptSidekick/Logs which should contain a more detailed error.

Thank you

**Comment by ochemerys** [comment]
Hi ahitrov,
I do not see "NativeScriptSidekick" folder under "~/Library/Application Support" currently

I provided a log file in my initial message as an attachment main_18-03-03_15-14-15.332.log

if the attached file is not a correct one then please let me know what should I do to get right one.

Thank you

**Comment by ahitrov** [comment]
Hi @ochemerys,

Sidekick produces several log files, **main_<timestamp>.log** containing logs from the main Sidekick executable and **cli_<timestamp>.log** containing detailed information from **build** and **LiveSync**. We need the **cli_<timestamp>.log** file which will be in the same directory where you found **main_18-03-03_15-14-15.332.log**.

It would be great if you archived the entire contents of the directory where you found *main_18-03-03_15-14-15.332.log** and attached it to the issue.

Cheers

**Comment by ahitrov** [comment]
Hi @ochemerys ,

What you are describing is a valid way to install Sidekick.

Also it is **not** expected to not have a NativeScriptSidekick folder under ~/Library/Application Support as this is the location where every Electron application stores its files and NativeScriptSidekick is build upon Electron.

Have you tried navigating to the NativeScriptSidekick folder via the terminal?

```open ~/Library/Application\ Support/NativeScriptSidekick```

 **mind that the space needs to be escaped**

Cheers

**Comment by ochemerys** [comment]
Hi ahitrov,
I was able to find NativescriptSidekick folder via terminal. Not sure why it was not exposed for me via Finder.
I attached the whole log folder as a zip file.

Thank you.

[Logs.zip](https://github.com/NativeScript/sidekick-feedback/files/1795441/Logs.zip)

**Comment by ahitrov** [comment]
Hi @ochemerys ,

The cli log showed a more detailed error:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase":
 In Podfile:
   Firebase (~> 4.8.0)


It seems the firebase plugin needs a newer version of the Firebase cocoapod but your local pod repo is not up-to-date.

Try running ```pod repo update``` from the terminal.

Cheers

**Comment by ochemerys** [comment]
Hi ahitrov
Thank you very much for your help 
pod repo update fixed my issue.
I was able to build and install my testing app on attached device (iPhone 5s).
During building process I was asked multiple times to enter my login password
<img width="1144" alt="screen shot 2018-03-10 at 11 03 43 am" src="https://user-images.githubusercontent.com/20651535/37245493-e3cea86e-2455-11e8-967d-b1758eded2f7.png">

Is it expected behaviour or I still missing some configuration settings?

Thanks again,

**Comment by ahitrov** [comment]
Hi @ochemerys ,

The password dialog is prompted by the OS itself, so I fear there's not much you can do. Even if you select Always Allow there's no guarantee how long this will keep macOS from asking for your password.

Cheers

**Comment by JillevdW** [comment]
In my case, this problem was fixed by simply removing the iOS platform and then adding it again.

**Comment by ggarabedian** [comment]
@JillevdW, thank you for sharing one possible way to resolve the reported issue.

I’m closing this issue because it seems to be resolved and prior of your comment it has been inactive for a few months. If anyone continue to experience the same problem with the latest version of Sidekick, please reopen this issue so we can investigate it further.

Thank you!

**Comment by mahavirvataliya** [comment]
**ERROR ReferenceError: Can't find variable: Toaster**
I get Above Error

**Comment by biapar** [comment]
I'm not able to use Sidekick with OSX environment. I've the same error.
