### ISSUE TITLE
iOS Cloud build error:  Cannot find module '../config/config'

### ISSUE THREAD

**Issue by wiwski** [NativeScript/sidekick-feedback#133]
Hi there,

### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem.
Clean Cloud Build on iOS gives me a Build Failed Error. 
Log file indicates: "error TS2307: Cannot find module '../config/config'", but the files are present in the project. 
It may be a cache problem since I forgot this file during the first attemp to build.

### Which platform(s) does the issue occur on?
_iOS_
_Windows 10_

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

SideKick: Version: 1.5.1-v.2018.2.26.1 (latest)
NativeScript CLI version: 3.4.3
CLI extension nativescript-cloud version: 1.3.1
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Open Project with Sidekick
2. Start a Cloud Build on iOS with Clean Build enabled

### Does this issue happen every time?
_Yes_

### Send the client logs.
https://gist.github.com/wiwski/590659717226560ba7b58b69ed8db91a

**Comment by ahitrov** [comment]
Hi @wiwski ,

Can you check if ```.../config/config``` is in your **.gitignore** file.
If so - make sure the module is not git-ignored

For cloud builds our infrastructure uses git to upload the sources of the project to the cloud and if the path to ```.../config/config``` is ignored that might explain the error you are reporting.

Cheers

**Comment by vtjon** [comment]
I just hit this same issue. I have a dev config that the developer can override but during our automated builds, it copies config.dev.ts to config.ts so that's it's available. It would be good to have some way to override this for sidekick.

**Comment by ahitrov** [comment]
Hi @vtjon ,

{N} supports adding custom build steps aka [hooks](https://github.com/NativeScript/nativescript-hook).

See if implementing this in a ```before-prepare``` hook works for you.

Cheers

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for a couple of months. Please, do not hesitate to reopen the issue if you require further assistance.

Thank you!
