### ISSUE TITLE
Cloud Build iOS Clean Build not working

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/sidekick-feedback#136]
### Did you verify whether this issue has already been reported here?
YES

### Tell us about the problem.
I am using a plugin i built. I have had to tweak and modify it some. This works fine in android but iOS i need to do cloud builds. But when i do that it appears the updates i do to the plugin arent saved for iOS and it loads the original TS file

### Which platform(s) does the issue occur on?
iOS
Windows - Nativescript Sidekick Cloud Build

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.6.0-v.2018.3.7.2 (latest)
- **NativeScript CLI:** 3.4.3
- **CLI extension nativescript-cloud:** 1.3.1
- **CLI extension nativescript-starter-kits:** 0.3.4

### Does this issue happen every time?
YES

**Comment by LorenDorez** [comment]
I dont think clean build is working.

**Comment by LorenDorez** [comment]
I have unstalled the app off the iPhone, restarted and reinstalled and still pulling cached files event with clean build enabled

**Comment by LorenDorez** [comment]
This appears to only be happening to plugin files

**Comment by tsvetie** [comment]
Hi @LorenDorez,

For cloud builds, we do not upload the node_modules folder in your NS app. So, in case you are making some changes to the files in node_modules, these will not be applied with a cloud build.

If this is the problem, you have two options to test the changes with a cloud build:
1. Move the modified code of the plugin to a new folder in your app folder.
2. Create a github repository with the modified code of the plugin.

After that, edit the your package.json so that the plugin entry points either to the new folder or to the github repository.

**Comment by LorenDorez** [comment]
@tsvetie 

This is a new plugin im building using the plugin-seed clone. I havent published it to NPM or anything so how does the cloud build pull it? because if that were true how does it add the plugins? does the cloud server directly download them from NPM?

 I have the updated tgz file in the app folder and here is my package.json.

```
 "dependencies": {
    "moment": "^2.21.0",
    "moment-timezone": "^0.5.14",
    "nativescript-background-http": "^3.2.1",
    "nativescript-camera": "^4.0.0",
    "nativescript-dialog": "^0.1.0",
    "nativescript-downloader": "^1.1.0",
    "nativescript-fontawesome": "^1.0.0",
    "nativescript-loading-screen": "file:nativescript-loading-screen-1.0.1.tgz",
    "nativescript-sqlite": "^2.0.1",
    "nativescript-sqlite-commercial": "file:nativescript-sqlite-commercial-1.0.0.tgz",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-listview": "^3.5.1",
    "nativescript-ui-sidedrawer": "^3.5.0",
    "tns-core-modules": "~3.4.0"
  },
```

**Comment by LorenDorez** [comment]
I just publish my plugin to NPM thinking that might help with an updated version number and still iOS cloud build still pull the original files....

See my plugin here [https://github.com/LorenDorez/nativescript-loading-screen](url)

**Comment by LorenDorez** [comment]
If i use theCloud Buil and install via the QR code i seem to have gotten the updated version

**Comment by tsvetie** [comment]
Hey @LorenDorez,

I am guessing you ran into a situation related to NPM that is somewhat expected. Can you check if you have a package-lock.json? If this is the case, you can either delete it, or use _npm remove --save [package_name/tgz]_ and then _npm i --save [package_name/tgz]_ to update the dependency to point to the new tgz file or the version of your released plugin. This will update both package.json and package-lock.json. 

Basically, when you first installed the dependency from the TGZ file, npm added an entry to package-lock.json with a specific "integrity" value. Any subsequent _npm i_ for your project folder checks that value and verifies that you have the initial version of your dependency in the local node_modules folder (you can check your node_modules/[package_name] code to verify whether you indeed have the original code there). After you run the app on your device, even though the built package has the correct version of the depedency, we perform a full sync of the local node_modules folder to the device. As a result, you end up with the old version of the dependency on the device.

The correct approach to testing with a local dependency is the following:

1. Add the tgz file to the folder of your project
2. Add a dependency with _npm i --save [path_to_tgz]_
3. Run on device - you should be able to use both cloud and local build with this approach

If you need to change the tgz file:

1. Update the tgz file in your peoject with the new one
2. Close the app in Sidekick (to stop the running LiveSync operation) - go to Recent apps screen
3. Delete the node_modules/[dependency_name] folder from your project
4. Delete package-lock.json or alternatively use _npm remove --save [dependency_name]_ and then _npm i --save [dependency_name]_ to update it
5. Open the app in Sidekick again and Run on device - the changed code of the dependency should be on the device after this

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for a few months. If you encounter the same problem with the latest version of Sidekick, please feel free to reopen it. :)

Thank you!
