### ISSUE TITLE
Login screen white on macOS Sierra

### ISSUE THREAD

**Issue by T0T4R4** [NativeScript/sidekick-feedback#145]
## Please, provide the details below:
The Authentication window is completely white.

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When launching nativescript, the authentication window is all white.

### Which platform(s) does the issue occur on?
macOS Sierra

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 1.7.1-v2018.3.16.2
- **NativeScript CLI:** 3.4.3
- **CLI extension nativescript-cloud:** 1.7.1
- **CLI extension nativescript-starter-kits:** 0.34

### Tell us how to recreate the issue in as much detail as possible.
On the first start, the authentication window shows blank. Links are clickable though, if we can find where they are :)

### Does this issue happen every time?
Yes

**Comment by bundyo** [comment]
This is a rather rare issue with NVidia cards on macOS Sierra and High Sierra. Can you try to run Sidekick for a Terminal by using this command and tell us how it goes?

```open -a NativeScript\ Sidekick --args --disable-gpu```

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months. If you are still experiencing the same behavior with the latest version of Sidekick, please do not hesitate to reopen it. :)

Thank you!

**Comment by realtebo** [comment]
Please, reopen, I have the same issue, but I am on Mojave.

It's my first installation of Sidekick on my Mac. It should open the browser to allow me to login,  but it only shows a white page, so no login, no app.

Please, I need to fix this because I've an app waiting to be released.
