### ISSUE TITLE
When you create a new app within SideKick you cannot specify an existing template.

### ISSUE THREAD

**Issue by PeterWokke** [NativeScript/sidekick-feedback#146]
## Please, provide the details below:
Using the CLI I can create a new app like this:
tns create Tekmo --template tns-template-hello-world

After creation you can open it in SideKick.
You cannot specify the template and create the app in SideKick directly.

### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem.
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by teobugslayer** [comment]
Hello Peter,

Can you tell me more where these templates come from? For example, is this a GitHub/GitLab/etc repo? Or a private npm registry? Or just a directory on your file system?

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months. If you are still experiencing the reported problem with the latest version of Sidekick, please do not hesitate to reopen it. :)

Thanks!
