### ISSUE TITLE
Error: Cannot find a vaild app in C:\Users\...\...

### ISSUE THREAD

**Issue by In-the-Black-Games** [NativeScript/sidekick-feedback#148]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem.
I start the Nativesript Sidekick program. I click "open". I choose and "App" to open. When I choose the app to open I get a message saying "Cannot find a vail app in C:\Users\...\...\... Do you want to remove the app from recent apps?" This is my first time opening the folder in nativescript sidekick. How can I open an app in sidekick?

### Which platform(s) does the issue occur on?
neither
_Windows

### Provide the following version numbers that the issue occurs with:
Version: 1.7.1-v.2018.3.16.2 (latest)
- **NativeScript Sidekick:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Click Open (to add an App folder)
3. Select folder

### Does this issue happen every time?
_Yes - for every folder I try to open

### Send the client logs.
Attached is a .zip file of the app that I am trying to open.
[whatsapp-master.zip](https://github.com/NativeScript/sidekick-feedback/files/1838653/whatsapp-master.zip)

**Comment by ahitrov** [comment]
Hi @In-the-Black-Games 

NativeScript Sidekick can only open NativeScript apps and the attached app is **not** a NativeScript app.

You can create a new NativeScript app by clicking **Create** and completing the Create App wizard.

Cheers
