### ISSUE TITLE
iOS cloud build fails

### ISSUE THREAD

**Issue by damikael** [NativeScript/sidekick-feedback#151]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
After upgrade to Nativescript CLI 3.4.3 iOS cloud build does not work anymore. Build fails during building project. See below:
`
▸ Building Pods/Pods-myapp [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling Pods-myapp-dummy.m
▸ Compiling Pods_myapp_vers.c
▸ Compiling Pods-myapp-dummy.m
▸ Compiling Pods_myapp_vers.c
▸ Copying Pods-myapp-umbrella.h
▸ Touching Pods_myapp.framework
▸ Building myapp/myapp[Release]
▸ Check Dependencies
** ARCHIVE FAILED **
The following build commands failed:
\tCheck dependencies
(1 failure)
`

### Which platform(s) does the issue occur on?
iOS
Windows 10

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick: 1.7.1-v.2018.3.16.2** 
- **NativeScript CLI: 3.4.3** 
- **CLI extension nativescript-cloud: 1.7.1** 
- **CLI extension nativescript-starter-kits: 0.3.4** 

### Tell us how to recreate the issue in as much detail as possible.
1. Run Build on Sidekick

### Does this issue happen every time?
Yes

**Comment by damikael** [comment]
Can it be related to bug in nativescript-cloud fixed on version 1.7.2 ?
(https://github.com/NativeScript/nativescript-cloud/releases)

**Comment by tsvetie** [comment]
Hey @damikael,

I am not sure what the problem is. Can you send me the log files. They are located in:

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

In order to send only the ones that are relevant, you can empty the folder, start Sidekick, reproduce the problem and then send me the newly created files.

Additionally, send me your package.json file.

**Comment by damikael** [comment]
Problem was related to a misconfiguration of build.xcconfig

**Comment by alereisan** [comment]
@tsvetie I am facing the same problem ... on Mac and on Windows, when trying to do a Cloud Build/Publish for iOS.

Logfile (Windows):
[main_18-04-05_08-36-27.518.log](https://github.com/NativeScript/sidekick-feedback/files/1882956/main_18-04-05_08-36-27.518.log)

package.json:
[package.json.txt](https://github.com/NativeScript/sidekick-feedback/files/1882969/package.json.txt)

**Comment by alereisan** [comment]
@damikael could you please mention what you have done to make this work?

**Comment by damikael** [comment]
Hello @alereisan,
in my case I had to delete entitlements file under app/App_Resources/iOS.
I use nativescript-plugin-firebase and cloud messaging on iOS needs that file (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md)
I must investigate better to understand why my entitlements file does not work.

**Comment by hackerunet** [comment]
I have exactly the same issue and has something to do maybe with a dependency not been correctly installed, maybe that is, my build failed on Windows 10 env with Nativescript:
Version: 1.9.1-v.2018.4.23.1 (latest)
NativeScript CLI version: 4.0.0
CLI extension nativescript-cloud version: 1.9.0
CLI extension nativescript-starter-kits version: 0.3.4
NPM 5.6.0
node v8.11.1
[main_18-05-17_21-35-28.558.log](https://github.com/NativeScript/sidekick-feedback/files/2014865/main_18-05-17_21-35-28.558.log)
