### ISSUE TITLE
"drawer-fragment.ios.css" or "app.ios.css" get cleared by sidekick

### ISSUE THREAD

**Issue by brianha** [NativeScript/sidekick-feedback#155]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I am using projecttype: javascript, Template: Drawer Navigation and working from there using autocomplete, Dataform and other plugins. I have two apps running from the old telerik appbuilder but I now have to move to a new platform, and this is it. 

I have installed the nativescript sidedrawer app. I can't seem to keep my CSS files  "drawer-fragment.ios.css" or "app.ios.css" intact nomatter what text editor I used (Visual Studio Code prefered) When I build the project all its content gets removed and they are left blank. Is there some basic thing I am missing? Should i not edit those files? I can't make any progress when they get changed "behind the scenes" all the time.

### Which platform(s) does the issue occur on?
iOS
macOS, 10.13.3

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick: 1.8.2 (latest)
- **NativeScript CLI: 3.4.3
- **CLI extension nativescript-cloud: 
Installed extensions:
┌───────────────────────────┬─────────┐
│ Name                      │ Version │
│ nativescript-cloud        │ 1.8.0   │
│ nativescript-starter-kits │ 0.3.4 

- **CLI extension nativescript-starter-kits: Sidedrawer template

### Tell us how to recreate the issue in as much detail as possible.
1. install sidedrawer tempalte with javascript
2.  Edit "drawer-fragment.ios.css" or "app.ios.css" using Visual studio Code
3. Build and run using xode simulator and NativeScript Sidekick

### Does this issue happen every time?
More or less. Right now it is,.

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_ (Cant see any folder there)
 - _Linux: ~/.config/NativeScriptSidekick/Logs_
 
Any help appreciated as it is driving me nuts and really hard to develop my app.

**Comment by brianha** [comment]
Ok. I just stopped using the files "drawer-fragment.ios.scss" and "app.ios.scss" as a workaround that seems to work for now.

**Comment by bundyo** [comment]
All templates currently use SASS, so the CSS files get replaced when the SCSS files are compiled.

**Comment by brianha** [comment]
Thx for letting me know as I didn’t know that but guess I learned the hard way but I really appreciate the info. I think some of the tutorials told me to change the global css actually. If you are a part time developer like me who doesn’t follow any new (.sass I this case) technology it’s really hard to figure out what is going on. 

Anyway I am making great progress now.
