### ISSUE TITLE
SideKick creating Apps from Old Templates

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/sidekick-feedback#156]
I noticed the template for thdrawer has been updated to use an "app-root" folder setup. When i use NativeScript Sidekick to create the new app it uses the older template that puts the nav menu in the shared folder.

How do i update sidekick to use the latest template versions

**Comment by LorenDorez** [comment]
It appears the template in question has been updated on github but not pushed to NPM yet.

**Comment by ventsislav-georgiev** [comment]
@LorenDorez I see you have found the reason for the issue. Sidekick uses the templates published in NPM and until the templates are published you will be creating an app with an older version of the template. Sidekick currently does not support to create an app from a repository. However, you could use the NativeScript CLI and create an app with the following command:
`tns create MyApp --template https://github.com/NativeScript/template-drawer-navigation.git`
Then you can open the newly created app in Sidekick.

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months and the initial question seems to be answered.
