### ISSUE TITLE
App ID can't start with a number?

### ISSUE THREAD

**Issue by brandonwilliams** [NativeScript/sidekick-feedback#163]
> App Identifier must be unique and contain two or more strings, separated by a dot. _Each string must start with a letter_ and should contain only letters and numbers. The app identifier must not start with an uppercase letter

Is this necessary? the part after "com." or "org." can begin with a number in Xcode. Sidekick allows you to save, but it says it's invalid.

**Comment by ivanovit** [comment]
Hi,

The Application Identifier must satisfy both iOS and Android requirements. The requirement you mentioned comes from the Android specification.
```
Each segment must start with a letter.
```
https://developer.android.com/studio/build/application-id.html

Please let us know if you have any further questions.

**Comment by dtopuzov** [comment]
@brandonwilliams If you really insist to use number as leading char in name you can try this workaround:

Create app with {N} CLI using `--force` option:
```
tns create 1app --force
```
Then open the app in Sidekick and do what you need to do.

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months. If you would like us to investigate this further, please do not hesitate to reopen it.

Thank you!
