### ISSUE TITLE
Cannot open project after update to 4.0.0

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/sidekick-feedback#168]
## Please, provide the details below:
Cannot open project(android) after update to latest version (4.0.0). 
Projects which have been built on IOS can be opened. 
### Tell us about the problem.
ENOENT: no such file or directory, open 'C:\.\app\App_Resources\iOS\Assets.xcassets\AppIcon.appiconset\Contents.json',

### Which platform(s) does the issue occur on?
Android

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:1.9.0-v.2018.4.11.4 (latest)
- **NativeScript CLI:4.0.0
- **CLI extension nativescript-cloud:1.9.0
- **CLI extension nativescript-starter-kits:0.3.4

### Tell us how to recreate the issue in as much detail as possible.
Open sidekick -> open existing project->fail to open 

### Does this issue happen every time?
_Yes

**Comment by AshleyCao** [comment]
@tsvetie Please find files you need here: [https://github.com/AshleyCao/sidekick1.9.0-ios.git](url)
I did have package.json in c drive. 
What I did yesterday is copy the missing files from other ios project to this one so I can open it. 
The project is native Android, never deploy on ios. 
After adding files, I can run on the device but it kept giving me "Unreachable" warning error on the device icon. I need to replugin device.

**Comment by tsvetie** [comment]
Hey @AshleyCao,

You are correct. With the old version of Sidekick, you can open a project, in which you have deleted the App_Resources/iOS folder and with the new version, you cannot. For the time being, do not delete the resources, even if you do not intend on building the app for the given platform. I will verify with my colleagues whether this is a bug and get back to you.

**Comment by AshleyCao** [comment]
@tsvetie I didn't delete any files in resource folder. Just copy from other ios files so I can at least open it. 
If I only deploy on Android device, files for ios setting should be needed, right?

**Comment by tsvetie** [comment]
@AshleyCao, this is very interesting. How did you create the NS project so that it has no App_Resources/iOS folder?

On a side note, we will fix the error when you try to open a NS project with no App_Resources/iOS folder in Sidekick with one of our next released.

**Comment by AshleyCao** [comment]
@tsvetie There is an ios folder under App_Resource but only images, no Assets.xcassets folder or so.
