### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by frey1esm** [NativeScript/sidekick-feedback#172]
### Did you verify whether this issue has already been reported here?
Yes
### Tell us about the problem
Attempting to run a starter app on a device and running into numerous missing dependencies, such as webpack and a few associated webpack modules, NativeScriptWorkerPlugin. I manually added the webpack modules but am stuck on NativeScriptWorkerPlugin. I suspect there are more.

### Which platform(s) does the issue occur on?
IOS and Android  <br/>

Mac

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
1.9.0-v.2018.4.11.4

- **NativeScript CLI:** 
4.0.0

- **CLI extension nativescript-cloud:** 
1.9.0
- **CLI extension nativescript-starter-kits:** 
0.3.4

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2.  CLick "Run on Device"

### Does this issue happen every time?
Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

https://gist.github.com/frey1esm/a0caa5bafcbf20213febb05f95768400

Also, `tns doctor` reports no issues - all green.

**Comment by frey1esm** [comment]
I manually installed all the missing dependencies and now have this error:

`Error detected during LiveSync on 43196b524e87a15996ccc4ab824ce37a5526d24b for /Users/david/Documents/HSWEB/mobile/apps/MyApp/REPOS/mobile-app-nativescript/MyApp Beta 2. Error: Executing webpack failed with exit code 2.`

**Comment by teobugslayer** [comment]
Hello @frey1esm ,

Apologies for the late reply. Have you found a way to fix the issue yet?

**Comment by frey1esm** [comment]
I did get this resolved by manually installing the missing dependencies. 

But I stiall am stuck trying to get Sidekick working. [See this issue # 179](https://github.com/NativeScript/sidekick-feedback/issues/179).

**Comment by tsvetie** [comment]
Hey @frey1esm,

Can you tell me why you reopened this issue?

**Comment by frey1esm** [comment]
accidental.
