### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/sidekick-feedback#176]
So upgraded and a new section "Services" ;-)

They all use kinvey.. but the icon or documentation dont explain what kinvey is..

To resolve, can the "powered by kinvey" when clicked goto https://www.kinvey.com/

**Comment by teobugslayer** [comment]
Hey @pedromorgan, 
thank you for your feedback - much appreciated! It seems like a good change and I will talk with the team when we can implement it.

**Comment by teobugslayer** [comment]
This is implemented.
