### ISSUE TITLE
Installed Plugin list is out of sync with app

### ISSUE THREAD

**Issue by seaware** [NativeScript/sidekick-feedback#177]
### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem
Sidekick's plugin list can become out of sync with the actual plugin state of the app under development.

### Which platform(s) does the issue occur on?
I only tried this on an iOS app using a Mac

### Provide the following version numbers that the issue occurs with:

Using Sidekick Version: 1.9.0-v.2018.4.11.4 (latest)
NativeScript CLI version: 4.0.0
CLI extension nativescript-cloud version: 1.9.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
On the installed plugins list within Sidekick, I highlighted the 'native script-toast' plugin then clicked on Uninstall. The spinner indicating it was busy never stopped. (I waited several minutes). I navigated to the asset list and back to plugins which still showed the nativescript-toast plugin and no spinner. I then went to a terminal and entered 'tns plugin' on a terminal which showed the plugin was actually removed even though Sidekick showed it was installed. When I exited Sidekick then restarted it, it then refreshed the plugin status properly.

### Does this issue happen every time?
Not sure

### Send the client logs
[main_18-04-18_06-30-02.437.log](https://github.com/NativeScript/sidekick-feedback/files/1935898/main_18-04-18_06-30-02.437.log)
[console_18-04-18_06-29-33.436.log](https://github.com/NativeScript/sidekick-feedback/files/1935900/console_18-04-18_06-29-33.436.log)

**Comment by tsvetie** [comment]
Hey @seaware,

I tested a couple of scenarios, but I could not reproduce the problem locally. I can see from the log files that the uninstall completes, but I do not see the package.json file changing.

Can you try the following:
1. Restart Sidekick
2. Open/create an app
3. Install _nativescript-toast_
4. Uninstall _nativescript-toast_

Can you reproduce the problem with these simple steps? If so, send me the newly created log files.

On a side note, can you tell me how you installed _nativescript-toast_ in the first place?

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for a couple of months. If you are still experiencing the reported behavior with the latest version of Sidekick and would like us to investigate it further, please feel free to reopen it.
