### ISSUE TITLE
Build failed. Command failed: ruby -e "require 'xcodeproj'

### ISSUE THREAD

**Issue by frey1esm** [NativeScript/sidekick-feedback#179]
### Did you verify whether this issue has already been reported here?
_Yes/No_
Yes

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

When attempting to build ios, I am getting this error:

```
[18-04-25 14:31:19.089] Build failed. Command failed: ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/david/Documents/apps/MyApp/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/david/Documents/apps/MyApp/app/App_Resources/iOS/build.xcconfig')).save_as(Pathname.new('/Users/david/Documents/apps/MyApp/platforms/ios/plugins-debug.xcconfig'))"
/Users/david/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Users/david/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

```

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

ios on Mac 

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:**    1.9.1-v.2018.4.23.1 (latest)
- **NativeScript CLI:**     4.0.0
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Try to build the app

### Does this issue happen every time?
_Yes/No_

Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._
 
see above.

**Comment by frey1esm** [comment]
Also, `tns doctor` reporst all is fine with regards to xcode:

`✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.1

**Comment by frey1esm** [comment]
Ruby install conflict. Problem solved.

**Comment by dogaoz** [comment]
How did you solve the problem?

**Comment by DimitarTachev** [comment]
@dogaoz could you share your OS and the other details from the issue template? I suppose you are using macOS Catalina?

**Comment by dogaoz** [comment]
Yeah, I’m using Catalina. I fixed it though. As far as I can remember, I updated Ruby and cocoapods(re-installed) and it started working.
