### ISSUE TITLE
Apple App Store publish: ERROR ITMS-90161

### ISSUE THREAD

**Issue by alereisan** [NativeScript/sidekick-feedback#181]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I am struggling since days again to publish an app to the Apple App Store. It fails and returns: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle ch.inaffect.hcm Could not upload binary to iTunes Connect. 

I made sure multiple times that I use the right provisioning profile and certificate. I re-downloaded the provisioning profile for the App-ID: ch.inaffect.hcm, re-downloaded the certificate and extracted the .p12 file with the keychain tool on mac.

Tried on Mac:
- Local Build
- Cloud Build

Tried on Windows:
- Cloud Build

### Which platform(s) does the issue occur on?
Tried on Mac:
- Local Build
- Cloud Build

Tried on Windows:
- Cloud Build

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick: Version: 1.9.1-v.2018.4.23.1 (latest)** 
- **NativeScript CLI: 4.0.0** 
- **CLI extension nativescript-cloud: 1.9.0** 
- **CLI extension nativescript-starter-kits: 0.3.4** 

### Tell us how to recreate the issue in as much detail as possible
1. Start nativescript sidekick
2. Publish
3. Select provisioning profile & certificate
4. Choose Cloud or Local Build
(Clean build, no webpack)
<img width="1205" alt="screen shot 2018-05-04 at 11 28 46" src="https://user-images.githubusercontent.com/14333479/39624111-5f17b11a-4f98-11e8-8739-bbe67827b665.png">

### Does this issue happen every time?
Yes

**Comment by alereisan** [comment]
24 days ago I was able to publish with the provisioning profile + certificate.

**Comment by tsvetie** [comment]
Hi @alereisan,

I am not quite sure I understand you correctly. Can you confirm that you used the same provision and certificate to publish an app successfully before and now trying to publish the same app, you get this error?

Please note that local builds do not take into account the provision/certificate that you select in the configuration window. This configuration window applies only to iOS Cloud Builds. When you are using local builds, both provision and certificate are automatically selected from the eligible ones available on your machine.

Additionally, can you send me the log files of a Sidekick session, in which you reproduce the problem? You can locate them by selecting _Help → Show Logs_ from the top menu.

**Comment by alereisan** [comment]
Hi @tsvetie 

The problem was: build.xconfig file had the wrong DEVELOPMENT_TEAM ID
this works now.
