### ISSUE TITLE
Nativescript Sidekick ios cloud build failed

### ISSUE THREAD

**Issue by Vprime007** [NativeScript/sidekick-feedback#182]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Get an \tCheck dependencies  error everytime i try to iOS cloud build with SideKick.

### Which platform(s) does the issue occur on?
iOS runtime version 4.1.0-2018-04-24-01
Windows 8.1 Professionnal

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio: 1.9.1-v.2018.4.23.1** 
- **NativeScript CLI: 4.0.0** 
- **CLI extension nativescript-cloud: 1.9.0** 
- **CLI extension nativescript-starter-kits: 0.3.4** 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application SideKick
2. Select Build Menu
3. Select iOS, BUILD TYPE => Cloud Build, CONFIGURATION => Release, Clean Build

### Does this issue happen every time?
Yes

### Send the client logs

[main_18-05-04_09-06-59.457.log](https://github.com/NativeScript/sidekick-feedback/files/1974592/main_18-05-04_09-06-59.457.log)

**Comment by alereisan** [comment]
I have the same issue. But the \tCheck dependencies error seems to appear randomly.

**Comment by tsvetie** [comment]
Hey @Vprime007 and @alereisan,

It has been a while, but do you still reproduce the problem? In case you do, would it be possible for you to send me a stripped down project that you can reproduce the problem with so that I can test it on my side?

**Comment by ggarabedian** [comment]
We are closing this issue due to prolonged period of inactivity. If the issue is still present in the latest version of Sidekick and you would like us to investigate it further, please feel free to create a new issue with up-to-date information.

Thank you! 😃
