### ISSUE TITLE
Gradle 4.1 doesn't recognise Java 10?

### ISSUE THREAD

**Issue by GijsOnGitHub** [NativeScript/sidekick-feedback#185]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When creating a local build for Android ... appears that Gradle 4.1 doesn't recognise/support Java 10:

[18-05-10 13:53:03.506] (CLI) FAILURE: Build failed with an exception.
[18-05-10 13:53:03.506] (CLI) * What went wrong:
[18-05-10 13:53:03.506] (CLI) Could not determine java version from '10.0.1'.

Do I need to downgrade my Java or do I have to upgrade Gradle? Or something else? Please advise.

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

macOS High Sierra Version 10.13.4

### Provide the following version numbers that the issue occurs with:

Version: 1.9.1-v.2018.4.23.1 (latest)
NativeScript CLI version: 4.0.0
CLI extension nativescript-cloud version: 1.9.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Build the application .. (Build Type-Local, Config-Debug)
2. Error Message (See description above)

### Does this issue happen every time?
_Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._

**Comment by GijsOnGitHub** [comment]
Just tried to build an Android app with TNS in Terminal and there you go:

✖ Javac version 10.0.1 is not supported. You have to install version 1.8.0. 

Guys I like the prospect of using NativeScript ... however, getting it to work is a challenge.

**Comment by teobugslayer** [comment]
Hey @GijsOnGitHub ,

Did you try Sidekick's cloud builds? They are using secure cloud infrastructure to build your apps and do not require any complex setup of your machine.
