### ISSUE TITLE
Build failed. Only 8, 16, 24, or 32 bits supported: 872 -- even with .p12 cert

### ISSUE THREAD

**Issue by thomascmost** [NativeScript/sidekick-feedback#186]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Using latest NativeScript and Sidekick, I get the "Build failed. Only 8, 16, 24, or 32 bits supported: 872" on Release cloud builds for Android with AOT turned *off* -- as listed here https://docs.nativescript.org/sidekick/intro/known-issues, but after I converted my keystore key to a p12 I am still seeing the issue.

### Which platform(s) does the issue occur on?
Android (Cloud)
Windows

### Provide the following version numbers that the issue occurs with:

- Sidekick Version: 1.9.1-v.2018.4.23.1
- NativeScript CLI version: 4.0.0
- CLI extension nativescript-cloud version: 1.9.0
- CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
This just happens when I try to do a cloud build on the Sidekick. My local emulator webpack build works (as long as I use the --bundle flag) but the cloud build throws this error. If we need repro steps I can try to create a slimmed down version of our app to share.

### Does this issue happen every time?
Yes 

### Send the client logs
https://gist.github.com/thomascmost/03777cfc47848a8ea00dff7fbc5ff868

**Comment by tsvetie** [comment]
Hey @thomascmost,

Can you give me more details how your converted the keystore key to a p12? The correct way would be to follow the steps in this post - [https://www.tbs-certificates.co.uk/FAQ/en/627.html](https://www.tbs-certificates.co.uk/FAQ/en/627.html). In case this is what you did in the first place, can you try converting it again just in case something when wrong the first time?

**Comment by thomascmost** [comment]
@tsvetie That seems to have worked! Thanks!

**Comment by delanick** [comment]
@tsvetie I've followed the approach in the article you linked, but still have the same issue. Been knocking my head repeatedly. Is there any possibility you guys can do this for me? I really need this done as my app is going live in 2 weeks and this is my last outstanding item on the project. PLEASE help.
