### ISSUE TITLE
Constantly loading old versions of my app

### ISSUE THREAD

**Issue by delanick** [NativeScript/sidekick-feedback#189]
Hi,

Sidekick is now often (so far the last 5 attempts) loading an old version onto my devices. This last case is me updating the code and it successfully running on Android, but the updates aren't being deployed to iOS, it just keeps deploying the old code without my new updates. Please look into this urgently, incredibly frustrating.

**Comment by ahitrov** [comment]
Hi @delanick 

From what you are describing it seems there might be an issue with LiveSync on iOS.

In order to investigate it further we'll need some more info:

1. the version of Sidekick
2. the version of {N} CLI
3. the OS (Windows or iOS)
4. the logs from a Sidekick session where you made changes but they weren't synced on to you iOS device.

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._

Cheers,
Alex

**Comment by delanick** [comment]
1. Sidekick version 1.9.1
2. {N} 4.0.1 I think. it's the current @next version, but was doing it before then even.
3. Using a Mac, and error is on both iOS and Android
4. I've been advised by someone in your team in another thread to use {N} @next, so haven't received this error too much. I am now experiencing loading the app onto the devices but the CSS isn't loading.

**Comment by ahitrov** [comment]
@delanick , you could create a gist off the ```package.json``` and the log file and paste a link here. More info here: https://help.github.com/articles/creating-gists/ .

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for more than a month. Please, do not hesitate to reopen it if you continue to experience such problem with the latest version of Sidekick and require further assistance.

Thank you!
