### ISSUE TITLE
ab.buildDeploy.shell.build - SASS compiler failed with exit code 1

### ISSUE THREAD

**Issue by akaco** [NativeScript/sidekick-feedback#19]
## Please, provide the details below:
When I try local build for Android in Log error I get this 
ab.buildDeploy.shell.build - SASS compiler failed with exit code 1
and app not build 
### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem.
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application  and make new test application as Drawer Navigation
2. select Build under Run Menu > select android > select local build > select Build 
### Does this issue happen every time?
_Yes/No_

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by dtopuzov** [comment]
Hi @akaco 

Can you please specify:
- CLI version
- `node` and `npm` versions
- Which template you build (or if it is custom app then post the package.json of the app)

**Comment by stoskov** [comment]
Would you please send us the log files located in:

_Windows: %AppData%\NativeScriptSidekick\Logs
macOS: ~/Library/Application Support/NativeScriptSidekick/Logs
Linux: ~/.config/NativeScriptSidekick/Logs_
