### ISSUE TITLE
Not able to update/install plugin

### ISSUE THREAD

**Issue by AshleyCao** [NativeScript/sidekick-feedback#193]
## Please, provide the details below:
Use sidekick "plugin" function to manage plugin, cannot implement any command ( includes update/delete/add). Have not tried cli yet.
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I can see a list of my plugin and when tried to uninstall. But always failed.

For instance, I tried to update tns-core-modules from 4.0.0 to 4.0.1
Error is :  Command npm.cmd install tns-core-modules@4.0.1 --save --save-exact failed with exit code 4294963238 

Also, I just wonder why " nativescript-dev-android-snapshot@0.0.11 preuninstall" always show up?
I already replaced nativescript-dev-android-snapshot with dev-webpack 
### Which platform(s) does the issue occur on?
Android

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio: 1.9.1
- **NativeScript CLI:4.0.1
- **CLI extension nativescript-cloud:1.9.0
- **CLI extension nativescript-starter-kits:0.3.4

### Does this issue happen every time?
Yes. Not able to update any plugin 

Please find log file [here](https://gist.github.com/AshleyCao/a0b89096f98dca895f17245a11a5711d)

**Comment by ahitrov** [comment]
Hi @AshleyCao 

It seems that npm has locked files in your app and in the user cache.
Can you try:
1. deleting the node_modules folder of your app
2. deleting the contents of the user cache folder located at ```C:\Users\<user name>\AppData\Roaming\npm-cache```
3. run npm install in the folder of your app

Let me know if that helps.
Cheers,

Alex

**Comment by AshleyCao** [comment]
By removing all spaces in the folders, it works.
Please refer to https://github.com/NativeScript/nativescript-cli/issues/3607#issuecomment-391232235
