### ISSUE TITLE
Publish to apple store

### ISSUE THREAD

**Issue by vasyliv** [NativeScript/sidekick-feedback#196]
## Please, provide the details below:
There is an error in publishing to apple.store

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I've used this guide to publish an application, after put username and password I've got an error
![image](https://user-images.githubusercontent.com/19407350/40539642-0901b000-601e-11e8-8215-29e8f2a83ee9.png)

### Which platform(s) does the issue occur on?
iOS
Windows

### Provide the following version numbers that the issue occurs with:

- NativeScript Sidekick Desktop
- **NativeScript CLI:** 4.0.2
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. build ap application
2. publish IOS
3. write username and password

### Does this issue happen every time?
Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._

**Comment by tsvetie** [comment]
Hi @vasyliv,

Can you verify if you can still reproduce the problem? In case you can, send me the log files that Sidekick created during a session in which you reproduced the error (select Help → Show Logs from the top menu). The log files contain a bit more information than you see in the Output pane.

**Comment by vasyliv** [comment]
@tsvetie the bug is fixed
