### ISSUE TITLE
Cannot find module chokidar

### ISSUE THREAD

**Issue by jeremypele** [NativeScript/sidekick-feedback#2]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
`Error while loading nativescript-cloud is: Cannot find module 'chokidar'`

### Which platform(s) does the issue occur on?
Both
macOS

### Provide the following version numbers that the issue occurs with:
npm 5.3.0
node 6.4.0

### Does this issue happen every time?
Yes

**Comment by ventsislav-georgiev** [comment]
Could you try to reinstall the `nativescript` cli:
* `npm r -g nativescript`
* `npm i -g nativescript`

and remove the cli extensions folder (it will be recreated on first launch):
* Mac/Linux - `~/.local/share/.nativescript-cli`
* Windows - `%appdata%\.nativescript-cli`

to see if the issue is related to corrupted npm dependencies installation.

**Comment by jeremypele** [comment]
Yep, removing the cli extensions folder does the trick.

Thanks @ventsislav-georgiev :)

**Comment by teobugslayer** [comment]
Glad we helped. We will continue monitoring the situation. So far we were able to reproduce it only with npm 5.

**Comment by njtrentacoste** [comment]
I'm currently having this issue as well, though not with nativescript-cloud.  I've installed nativescript, and updated all modules.  Below are the details:

Application is the Groceries sample for Angular.
Issue occurs when executing 'tns run android' via windows command prompt.
'tns build android' returns 'BUILD SUCCESSFUL'
'tns doctor' returns 'Your components are up-to-date.' and 'No issues were detected.'

OS: Windows 10 (Creators Update)
Nativescript: v3.1.3
tns-core-modules: v3.1.1
node: v8.1.2
npm: v5.3.0

I've tried the above suggestions of uninstalling/reinstalling as well as deleting the extensions folder.  It does not appear to fix my error.
I've also directly installed chokidar via npm and still didn't fix it.

Any help/guidance you can provide is greatly appreciated.

Thanks.
