### ISSUE TITLE
Can't Open Nativescript Sidekick

### ISSUE THREAD

**Issue by DMarinsa** [NativeScript/sidekick-feedback#202]
### Did you verify whether this issue has already been reported here?
No

### Tell us about the problem
Whe I try to open nativescript it says 
`Error: tunneling socket could not be established, cause=socket hang up `
and after that
`Error: tunneling socket could not be established, cause=error 501 `

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
- **NativeScript CLI: 4.0.2
- **CLI extension nativescript-cloud: 
- **CLI extension nativescript-starter-kits: 0.7.4

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Try to start sidekick

### Does this issue happen every time?
YES

**Comment by tsvetie** [comment]
Hey @DMarinsa,

Can you send the log files that Sidekick creates? You can find them in:

Windows: _%AppData%\NativeScriptSidekick\Logs_
macOS: _~/Library/Application Support/NativeScriptSidekick/Logs_
Linux: _~/.config/NativeScriptSidekick/Logs_

**Comment by ggarabedian** [comment]
We are closing this issue due to prolonged period of inactivity. If the issue is still present in the latest version of Sidekick and you would like us to investigate it further, please feel free to create a new issue with up-to-date information.

Thank you!
