### ISSUE TITLE
Iphone not detected on Windows platform

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/sidekick-feedback#204]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I plug an Iphone on my widows 10 PC and can't see it on "Devices" on Sidekick.
It works well with my android phone.
I tried with an other Iphone and it still doesn't work

### Which platform(s) does the issue occur on?
Sidekick runing on windows
Try to connect IOS phone

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:**  : Version: 1.10.1-v.2018.5.24.5 (latest)
- **NativeScript CLI:**  4.1.0
- **CLI extension nativescript-cloud:** 1.10.0
- **CLI extension nativescript-starter-kits:**  0.3.4

### Does this issue happen every time?
Yes

### Send the client logs
no specific log, I can't run on Iphone...

**Comment by tsvetie** [comment]
Hey @Serge-SDL,

Can you send us the log files that Sidekick creates? I understand the problem from the information you provided, but the log files hold more information that can help us identify why you experience this. You can open the folder, in which the log files are created by selecting Help → About from the top menu.

Apart from this, can you try restarting Sidekick to see if the issue will persist? In case it does, you can open command prompt and execute the following command to see if it will list any problems:

```
tns doctor
```
In case the doctor command does not list any problems, next you can try the devices command to see if NS CLI can detect your iPhone:

```
tns devices
```

**Comment by Serge-SDL** [comment]
Hello and thanks for your quick answer!

I tried again on my computer (PC1) and it starts working! The log files before (when the error appends):
[log PC 1.zip](https://github.com/NativeScript/sidekick-feedback/files/2076016/log.PC.1.zip)

I also tried on an other windows 10 PC (PC 2) and it fails (no device connection). Here are the logs:
[log PC 2.zip](https://github.com/NativeScript/sidekick-feedback/files/2076017/log.PC.2.zip)

on PC 1 when the no detection issue appends, there was no problem (except tns-ios is not installed) on tns doctor and the list of tns devices was empty. It's the same on PC2 (list was not empty because an android emulator was running)

Let me know if I can help you with more informations...
Thanks

**Comment by tsvetie** [comment]
Hey @Serge-SDL,

The important information from the log files is the following:

_iTunes is not installed. Install it on your system and run this command again._ 

Basically, in order to work with iOS devices, you need to install iTunes. You can download it, following this link - [https://www.apple.com/itunes/download/win64](https://www.apple.com/itunes/download/win64).

**Comment by ggarabedian** [comment]
We are closing this issue due to prolonged period of inactivity. If the issue is still present in the latest version of Sidekick and you would like us to investigate it further, please feel free to create a new issue with up-to-date information.

Thank you!

**Comment by steadycoding** [comment]
@tsvetie 
Thank you for your post. In order for Sidekick to recognize iTunes. The version **has to be the win64 build** and not the Microsoft Store build.

**Comment by jkarst** [comment]
I'me having the same issue.

Windows 10 is installed on two different machines (Pro and Home).  iTunes installed on both (and reinstalled using the link provided in these comments).

iTunes sees the iPhone device fine on both machines.

NativeScript Sidekick sees nothing on both machines.  tns devices sees nothing on both machines.

Any guesses what I can try next (besides a different iOS device, which I can try later)?

**Comment by ZeroCoolJr** [comment]
Jumping to 2019, and I'm not detecting my iPhone on Windows 10. Installed iTunes64 referred in this thread. iTunes detected my phone. `tns devices` does report iTunes is installed. Will iOS12 be an issue? What else to do?

**Comment by SudduK** [comment]
Same issue for me. Couldn't detect iPad after installing iTunes 64-bit on Windows 10 from Native script sidekick and also "**tns device"** command doesn't list iPad either. Am I missing anything?
Thank you for your help!

**Comment by kartercs** [comment]
Same issue, but as all the other nobody still respond a more than 1 year old post which is still relevant, is nativescript completly dead or what?

**Comment by ForzaMark** [comment]
any progress on this ?
