### ISSUE TITLE
Sidekick fails on iOS publish: An error has occurred while uploading the package

### ISSUE THREAD

**Issue by Austin0949** [NativeScript/sidekick-feedback#206]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I am able to deploy to google play store, and to my iOS device but not to the apple store with sidekick on my windows laptop.  I get this error in my sidekick console:

[18-06-10 14:26:26.248] undefined
[!] 
The request could not be completed because:, Error: undefined
[!] 
The request could not be completed because:

at CloudPublishService.getiOSError (C:\Users\austi\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:79:21)

at CloudPublishService.<anonymous> (C:\Users\austi\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:103:29)

at Generator.next (<anonymous>)
at fulfilled (C:\Users\austi\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:4:58)

at process._tickCallback (internal/process/next_tick.js:68:7)

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:
NativeScript Sidekick Desktop

Version: 1.10.2-v.2018.6.5.2 (latest)
NativeScript CLI version: 4.1.0
CLI extension nativescript-cloud version: 1.10.0
CLI extension nativescript-starter-kits version: 0.3.4

### Does this issue happen every time?
Yes

**Comment by ahitrov** [comment]
Hi @Austin0949 ,

Can you give us the entire logs from a Sidekick session where you reproduced this issue so we could investigate further?

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._

Cheers,
Alex

**Comment by Austin0949** [comment]
[main_18-06-09_15-53-11.809.log](https://github.com/NativeScript/sidekick-feedback/files/2092986/main_18-06-09_15-53-11.809.log)

**Comment by Austin0949** [comment]
[console_18-06-09_15-53-07.814.log](https://github.com/NativeScript/sidekick-feedback/files/2092988/console_18-06-09_15-53-07.814.log)

**Comment by Austin0949** [comment]
Hi, thank you for having a look at the logs. I was very careful to make sure that both the cert and profile used were distribution and not development.  I can remake them again and try again, but I am 99% sure they were distribution already when it failed.

**Comment by Austin0949** [comment]
I have logged into my apple dev account and verified that the cert and profile I used are for production / distribution.

**Comment by Austin0949** [comment]
[main_18-06-12_12-33-24.184.log](https://github.com/NativeScript/sidekick-feedback/files/2095632/main_18-06-12_12-33-24.184.log)

**Comment by Austin0949** [comment]
[console_18-06-12_12-33-20.528.log](https://github.com/NativeScript/sidekick-feedback/files/2095634/console_18-06-12_12-33-20.528.log)

**Comment by Austin0949** [comment]
I just tried to publish again and got errors and posted the new logs above.

**Comment by ahitrov** [comment]
Thank you!

I'll get back to you when we have investigated the issue

**Comment by Austin0949** [comment]
thank you for your help Alex.

**Comment by ahitrov** [comment]
Hi @Austin0949 ,

Unfortunately, the logs did not contain the detail of information that would help us pinpoint the problem.

So can you bump the log level following these steps:
1.) Open %APPDATA%\npm\node_modules\nativescript\config\config.json
2.) Add the key "DEBUG": false
3.) save the file

Then try to publish again and attach the produced logs here.

Once you have produced the logs, delete the "DEBUG" key in %APPDATA%\npm\node_modules\nativescript\config\config.json as this has a performance penalty to all NativeScript operations.

Thanks,
Alex

**Comment by Austin0949** [comment]
is this the path / file you are referring to?  it already had the debug key
set to false.

C:\Users\austi\AppData\Roaming\npm\node_modules\nativescript\config

**Comment by Austin0949** [comment]
{
    "DEBUG": false,
    "TYPESCRIPT_COMPILER_OPTIONS": {},
    "CI_LOGGER": false,
    "ANDROID_DEBUG_UI_MAC": "Google Chrome",
    "USE_POD_SANDBOX": false,
    "DISABLE_HOOKS": false
}

**Comment by Austin0949** [comment]
18-06-13 21:26:51.472] (CLI) ▸ Running script 'NativeScript PreBuild'
[18-06-13 21:26:51.472] (CLI) ▸ Precompiling DailyWins/DailyWins-Prefix.pch
[18-06-13 21:26:51.472] (CLI) ▸ Precompiling DailyWins/DailyWins-Prefix.pch
[18-06-13 21:26:51.472] (CLI) ▸ Compiling main.m
[18-06-13 21:26:51.472] (CLI) ▸ Compiling main.m
[18-06-13 21:26:51.472] (CLI) ▸ Linking DailyWins
[18-06-13 21:26:51.472] (CLI) ▸ Linking DailyWins
[18-06-13 21:26:51.472] (CLI) ▸ Running script 'NativeScript PreLink'
[18-06-13 21:26:51.472] (CLI) ▸ Copying InfoPlist.strings
[18-06-13 21:26:51.472] (CLI) ▸ Compiling LaunchScreen.storyboard
[18-06-13 21:26:51.472] (CLI) ▸ Processing DailyWins-Info.plist
[18-06-13 21:26:51.472] (CLI) ▸ Copying
/tmp/builds/_/182d719711b00df12e5e098d03be5e252d30e025/4.1.0/DailyWins/node_modules/nativescript-pro-ui/platforms/ios/TelerikAppFeedback.framework

[18-06-13 21:26:51.472] (CLI) skipping copy phase strip, binary is code
signed:
/tmp/builds/_/182d719711b00df12e5e098d03be5e252d30e025/4.1.0/DailyWins/node_modules/nativescript-pro-ui/platforms/ios/TelerikAppFeedback.framework/TelerikAppFeedback

[18-06-13 21:26:51.472] (CLI) ▸ Copying
/tmp/builds/_/182d719711b00df12e5e098d03be5e252d30e025/4.1.0/DailyWins/node_modules/nativescript-pro-ui/platforms/ios/TelerikUI.framework

[18-06-13 21:26:51.472] (CLI) skipping copy phase strip, binary is code
signed:
/tmp/builds/_/182d719711b00df12e5e098d03be5e252d30e025/4.1.0/DailyWins/node_modules/nativescript-pro-ui/platforms/ios/TelerikUI.framework/TelerikUI

[18-06-13 21:26:51.472] (CLI) ▸ Copying
/tmp/builds/_/182d719711b00df12e5e098d03be5e252d30e025/4.1.0/DailyWins/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework

[18-06-13 21:26:51.472] (CLI) skipping copy phase strip, binary is code
signed:
/tmp/builds/_/182d719711b00df12e5e098d03be5e252d30e025/4.1.0/DailyWins/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets

[18-06-13 21:26:51.472] (CLI) ▸ Signing
DerivedData/DailyWins/Build/Intermediates.noindex/ArchiveIntermediates/DailyWins/InstallationBuildProductsLocation/Applications/DailyWins.app/Frameworks/TelerikAppFeedback.framework

[18-06-13 21:26:51.472] (CLI) ▸ Signing
DerivedData/DailyWins/Build/Intermediates.noindex/ArchiveIntermediates/DailyWins/InstallationBuildProductsLocation/Applications/DailyWins.app/Frameworks/TelerikUI.framework

[18-06-13 21:26:51.472] (CLI) ▸ Signing
DerivedData/DailyWins/Build/Intermediates.noindex/ArchiveIntermediates/DailyWins/InstallationBuildProductsLocation/Applications/DailyWins.app/Frameworks/TNSWidgets.framework

[18-06-13 21:26:51.472] (CLI) ** ARCHIVE FAILED **
[18-06-13 21:26:51.472] (CLI) The following build commands failed:
[18-06-13 21:26:51.472] (CLI) \tCodeSign
DerivedData/DailyWins/Build/Intermediates.noindex/ArchiveIntermediates/DailyWins/InstallationBuildProductsLocation/Applications/DailyWins.app/Frameworks/TelerikAppFeedback.framework

[18-06-13 21:26:51.472] (CLI) \tCodeSign
DerivedData/DailyWins/Build/Intermediates.noindex/ArchiveIntermediates/DailyWins/InstallationBuildProductsLocation/Applications/DailyWins.app/Frameworks/TelerikUI.framework

[18-06-13 21:26:51.472] (CLI) \tCodeSign
DerivedData/DailyWins/Build/Intermediates.noindex/ArchiveIntermediates/DailyWins/InstallationBuildProductsLocation/Applications/DailyWins.app/Frameworks/TNSWidgets.framework

[18-06-13 21:26:51.472] (CLI) (3 failures)
[18-06-13 21:27:14.051] Build failed.

**Comment by Austin0949** [comment]
[18-06-13 21:36:59.564] (CLI) Finished cloud build of 'C:\Code\DailyWins',
platform: 'iOS', configuration: 'Release', buildId:
ac5aafae-b51f-4336-b8dc-e8590b13961f successfully. Downloading result...
[18-06-13 21:36:59.568] Download step started.
[18-06-13 21:37:16.766] Download step completed.
[18-06-13 21:37:16.769] (CLI) The result of cloud build of
'C:\Code\DailyWins', platform: 'iOS', configuration: 'Release', buildId:
ac5aafae-b51f-4336-b8dc-e8590b13961f successfully downloaded.
OutputFilePath: C:\Code\DailyWins\.cloud\ios\device\DailyWins.ipa
[18-06-13 21:38:16.605] (CLI) Starting publishing.
[18-06-13 21:38:47.818] undefined
[!] The request could not be completed because:, Error: undefined
[!] The request could not be completed because:
    at CloudPublishService.getiOSError
(C:\Users\austi\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:79:21)
    at CloudPublishService.<anonymous>
(C:\Users\austi\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:103:29)
    at Generator.next (<anonymous>)
    at fulfilled
(C:\Users\austi\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ahitrov** [comment]
@Austin0949 , apologies, I have misled you with the instructions for bumping up the log level.

C:\Users\austi\AppData\Roaming\npm\node_modules\nativescript\config\config.json

is correct but the value for the "DEBUG" key was wrong.

So
1.) Open C:\Users\austi\AppData\Roaming\npm\node_modules\nativescript\config\config.json
2.) Add the key **"DEBUG": true**
3.) save the file

Then try to publish again and attach the produced logs here.

Once you have produced the logs, **delete the "DEBUG" key** in C:\Users\austi\AppData\Roaming\npm\node_modules\nativescript\config\config.json as this has a performance penalty to all NativeScript operations.

Again, apologies for the inconvenience,

Alex

**Comment by Austin0949** [comment]
ok, no problem.  I am re-publishing now with debug set to true.  just in
case the issue is related my scss to css is not working.  If I make changes
to to the _app-commons.scss file it does not work, I have to make changes
directly to the css files.  I think sidekick gave me some scss errors
earlier when I tried to publish, I made some changes and now scss does not
work.

**Comment by Austin0949** [comment]
I think I deleted some scss.js file and re-ran the scss installer, both
were suggested on line to fix the sidekick scss error

**Comment by Austin0949** [comment]
that might have been what broke my scss?

**Comment by ahitrov** [comment]
Hi @Austin0949 ,

The scss issue does not seem to be related to this one nor to the "DEBUG" key in the config.json. When it happens again could you open another issue and attach the logs for that session there?

Thanks,
Alex

**Comment by Austin0949** [comment]
OK. Just sent the logs from the failed publish with debug set to true.

**Comment by ahitrov** [comment]
Hm, I don't see any new logs here.

Can you attach them to this issue?

**Comment by Austin0949** [comment]
[main_18-06-14_01-06-56.454.log](https://github.com/NativeScript/sidekick-feedback/files/2101496/main_18-06-14_01-06-56.454.log)

**Comment by Austin0949** [comment]
[console_18-06-14_01-06-53.402.log](https://github.com/NativeScript/sidekick-feedback/files/2101497/console_18-06-14_01-06-53.402.log)

**Comment by ahitrov** [comment]
Hi @Austin0949 ,

After investigating the logs I think we have found the culprit for the failure on publish:

Apple have updated their privacy statement at the end of May this year (as part of the new GDPR policy) and now would return a failure when you try to publish but have not yet acknowledge the new privacy statement.

Please manually log into https://appleid.apple.com (or https://itunesconnect.apple.com) to acknowledge the statement.

Let me know if that fixes the issue for you.

We will update our tooling so that such errors are more visible to the user without having to update the log level.

Cheers,
Alex

**Comment by Austin0949** [comment]
when Sidekick gets to this step it would be better if it remembered these
credentials or at least ring the windows notification so that I am prompted
to enter this info, otherwise it can just sit there...

**Comment by Austin0949** [comment]
Thank you.  I logged into both of the urls as you suggested, and after doing so was able to successfully publish into the appstoreconnect.apple.com site with Sidekick on a Windows 10 laptop.

**Comment by Austin0949** [comment]
It would help a lot if Sidekick could remember the two sets of credentials needed during publishing.  The password for the profile, and then the login credentials for the appstore.  As it is now you have to keep checking back with Sidekick to see if it has paused at those prompts.

**Comment by ahitrov** [comment]
Hi @Austin0949 ,

I'm glad you were able to publish your app.
Thank you for the suggestion for improvement! We will consider it for future releases.

**Comment by Austin0949** [comment]
Hi Alex,

Sidekick publishing worked a few days ago for me but now I am getting this
SideKick error message below when I try to publish to the apple store. Not
sure how to resolve this issue.

An error has occurred while uploading the package Error: Publishing failed.
[31m [!] The request could not be completed because: You must provide a
Privacy Policy URL. You must provide a Privacy Policy URL.[0m Publishing
failed.
