### ISSUE TITLE
Can't enter empty password for certificate

### ISSUE THREAD

**Issue by lukeramsden** [NativeScript/sidekick-feedback#21]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I select a .p12 certificate for iOS and run Cloud Build, it asks for a password and won't let me leave the box empty, even though the .p12 cert has no password.

### Platforms
I'm on Windows building for iOS, but I doubt it makes a difference.

### Version Numbers
Version: 0.2.0-v.2017.7.31.4 (latest)
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

**Comment by bundyo** [comment]
This is a design decision and security precaution - we don't want to upload certificates without a password for cloud builds. In case of a leak they won't have any additional protection.

**Comment by Garthanos** [comment]
It seeams Certificate Signing requests created in the Sidekick interface do not have a method for assigning a password?
