### ISSUE TITLE
"Unhandled Observer Error" notification on Sidekick startup

### ISSUE THREAD

**Issue by LeoDupont** [NativeScript/sidekick-feedback#210]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When launching Sidekick, several notifications like these ones appear: 
![image](https://user-images.githubusercontent.com/29914053/41546070-fb3a10f4-731c-11e8-8714-14d20a3f1855.png)
![image](https://user-images.githubusercontent.com/29914053/41585383-2d4a68fe-73aa-11e8-9c74-7c9add906446.png)

When Sidekick finished launching, I can see this error in the Sidekick Errors log (which occurs 8 times in a row):
```
[18-06-18 17:26:14.487] [object Object], Error: [object Object]
    at fetch.then.then.catch (file:///C:/Users/L%C3%A9o/AppData/Local/NativeScriptSidekick/app-1.10.2-v2018652/resources/app.asar/ui/app.js:26146:43)
    at <anonymous>
```

Note: my Windows account name contains a non-ASCII character (an "é"). I've already had a problem compiling to Android because of this character in a project path, so I moved my project to C:\NativeScript and compiled successfully - sort of. However, I didn't get to choose where to install Sidekick so it is inexorably installed in a path containing a non-ASCII character (same goes for Sidekick's AppData folder).

### Which platform(s) does the issue occur on?
Windows 10 Pro 64-bit

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop:** 1.10.2-v.2018.6.5.2 (latest)
- **NativeScript CLI:** 4.1.0
- **CLI extension nativescript-cloud:** 1.10.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible
As far as I'm concerned, this is pretty much what I have done since the beginning of my NativeScript adventure: 
1. Have already Node 6 and NPM installed (for Angular development)
2. Install NativeScript Sidekick, which installs NativeScript CLI
3. Wait a few days
4. Start Sidekick and run the update
5. Sidekick won't update and start throwing error notifications (like on the screenshot) because I have CLI 4.0.1 and it needs CLI 4.1.0
6. Run `npm i -g nativescript` to install latest CLI version (and update Node to latest LTS version because v6 is deprecated)
7. Start Sidekick, it updates correctly but still throws errors on startup
8. Run `@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://www.nativescript.org/setup/win'))"` as seen in the docs to install every requirement, it works - though I had to manually set the correct JAVA_HOME path in order to install the Android SDK.
8. Reinstall Sidekick, same problem
9. Uninstall Sidekick, delete its AppData/Local and AppData/Roaming directories, reinstall, same problem
10. Restart the computer, same problem

### Does this issue happen every time?
Yes

### Send the client logs
Main log: [main_18-06-18_17-26-13.647.log](https://github.com/NativeScript/sidekick-feedback/files/2111988/main_18-06-18_17-26-13.647.log)
Console log: [console_18-06-18_17-26-10.255.log](https://github.com/NativeScript/sidekick-feedback/files/2111990/console_18-06-18_17-26-10.255.log)

**Comment by ElecTreeFrying** [comment]
Hello this is also happening to mine ns sidekick. please help us resolve this issue.

**Comment by LeoDupont** [comment]
@ElecTreeFrying Hello, do you have any special character in your Microsoft account name or in any installation path like I do?

**Comment by ElecTreeFrying** [comment]
@LeoDupont yes has `ñ` on it `C:\Users\*****ñ**`

**Comment by LeoDupont** [comment]
I'm afraid these non-ASCII characters in paths might cause a lot of troubles to NativeScript.
Let's hope they will soon be supported, or that we'll be able to choose the installation directory of Sidekick and its dependencies (which would also be nice for computers with a small SSD C:\ drive, by the way).

**Comment by ventsislav-georgiev** [comment]
@LeoDupont, @ElecTreeFrying thank you for the report. We identified what is causing the issue and we are working on resolving it as soon as possible.

In the meantime, we cannot offer any viable workarounds, however, the issue should only affect the loading of some Sidekick image resources and should not obstruct the the build/deploy/publish functionality. 
The Assets property page will also not load if the app is created in a path containing non-ascii character. 

Can you please confirm if you have the same experience and you are able to build and deploy your app successfully?

**Comment by ElecTreeFrying** [comment]
yes @ventsislav-georgiev ns sidekick doesnt load all img resources but other features that I use with ns sidekick works perfectly fine.

**Comment by ElecTreeFrying** [comment]
@LeoDupont issue resolve by downloading ns-sidekick latest version `1.10.3-v.2018.6.26.1 (latest)`. I think we can close this issue now.

**Comment by LeoDupont** [comment]
@ElecTreeFrying indeed, this update cleared the error messages. I'm closing this issue.
@ventsislav-georgiev and the NativeScript team, thank you for your work 👍
