### ISSUE TITLE
First run on Mac - "Unable to load extension nativescript-cloud"

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/sidekick-feedback#22]
First run on Mac (Sierra 10.12.6). {N} is 3.1.3, npm is 4.6.1, node is 6.0.0. Upon start up I get an error notification of:

`[17-08-04 13:00:32.786] (Error) ab.cliExtensions.shell.extensionLoaded - {"extensionName":"nativescript-cloud","extensionVersion":"0.11.6","error":"Unable to load extension nativescript-cloud. You will not be able to use the functionality that it adds. Error: Cannot find module 'chokidar'"}`

Unless I'm missing something, I don't see a `~/Library/Application Support/NativeScriptSidekick` directory either?

**Comment by ventsislav-georgiev** [comment]
@rdlauer check if the solution [here](https://github.com/NativeScript/sidekick-feedback/issues/2#issuecomment-319116695) fixes the issue.

**Comment by rdlauer** [comment]
That fixed it!
