### ISSUE TITLE
Version: 1.10.3-v.2018.6.26.1 (latest) Can no longer get debug to run

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/sidekick-feedback#220]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Since upgrading to the latest version I am having trouble running the debug console. I have tried deleting the app, re-compiling with Start Debugger, Tried clicking the Bug icon. Each time it errors telling me the App is not installed or not built with debugging enabled, even though Build Configuration is Debug, Start Debugger is Ticked.

### Which platform(s) does the issue occur on?
iOS at the moment, haven't tried Android.

### Provide the following version numbers that the issue occurs with:

Version: 1.10.3-v.2018.6.26.1 (latest)
Nativescript 4.1.0

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Open Application
3. Run on Device with debug options set.

### Does this issue happen every time?
Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._

**Comment by mrwrighty** [comment]
Oddly after closing Nativescript SideKick, re-compiling the app and letting it run, clicking the Bug icon did load the debug console, but seems hit and miss.

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
