### ISSUE TITLE
iOS Cloud build failed with unexpected Mach-O header error

### ISSUE THREAD

**Issue by seaware** [NativeScript/sidekick-feedback#223]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Built the project on the cloud, but am getting an interesting error ```Error Domain=DVTMachOErrorDomain Code=0 \"Found an unexpected Mach-O header code: 0x72613c21\" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}```. I am on a mac and building and running with project on an iOS simulator works fine.

I found this on how to fix it, but it appears out of my control if I am building in the cloud (although correct me if I'm wrong):
- https://kobkrit.com/how-to-fix-found-an-unexpected-mach-o-header-code-0x72613c21-on-submitting-to-app-store-7d5b8ec180c

### Which platform(s) does the issue occur on?
iOS cloud build
Built using Sidekick on macOS

### Provide the following version numbers that the issue occurs with:

- Version: 1.10.3-v.2018.6.26.1 (latest)
- NativeScript CLI version: 4.1.0
- CLI extension nativescript-cloud version: 1.11.0
- CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Start Sidekick > select project > Build > iOS
2. Setup certificates for iOS
3. Set Build type = Cloud
4. Set Configuration = Release
5. The "Clean build" setting does not make a difference for this problem.
6. Click Build

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.githubusercontent.com/seaware/6342568a7a4ebdbcc6df9401f61eaa37/raw/172ed4294cc92c8fcf9f3fdc3ffa320de130766c/log.txt

**Comment by arpit2438735** [comment]
Same issue I am also facing with NS 4.1

**Comment by arpit2438735** [comment]
I got the fix.Upgrade the package of
`nativescript-background-fetch` and `nativescript-background-geolocation-lt` to latest and it will solve the problem

**Comment by seaware** [comment]
Thanks @arpit2438735, that fixed the problem. Interestingly the "tns plugin upgrade" command seems broken so I did a "tns plugin remove" and "tns plugin add".

In case it helps others, before the upgrade these versions created the Mach-O error:
```
┌────────────────────────────────────────┬─────────┐
│ Plugin                                 │ Version │
│ nativescript-background-fetch          │ ^1.1.1  │
│ nativescript-background-geolocation-lt │ ^1.8.0  │
```
After the plugin upgrade, these versions resolved it:
```
┌────────────────────────────────────────┬───────────────┐
│ Plugin                                 │ Version       │
│ nativescript-background-fetch          │ ^1.2.0        │
│ nativescript-background-geolocation-lt │ ^1.9.0-beta.3 │
```
