### ISSUE TITLE
Build modules from project

### ISSUE THREAD

**Issue by kefahB** [NativeScript/sidekick-feedback#224]
### Did you verify whether this issue has already been reported here?
_Yes
### Tell us about the problem
When build, Sidekick download the dependences modules (package.json) from respectif npm repo's.
The problème is sum modules has issue and the owner have not time for upgrade the issues; for this I made a provisional correction while waiting for the correction by the owner; Now if I build with Sidekick the module will be downloaded from npm repo by Sidekick where they are issue !

### Which platform(s) does the issue occur on?
Both

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop

### Tell us how to recreate the issue in as much detail as possible
1. create a project
2. install `npm i --save nativescript-socketio`
3. do init or just a emit in main-page.js
4. build with simulator, you will have error io is undefined 
5. go to `node_modules/nativescript-socket.io/socketio.d.ts` comment 
```ts 
protected socket: io.socket.client.Socket;
``` 
and add 
```ts 
protected socket: any;
```
5. save and build again with simulator it will done (no error)
6. now build with Sidekick it will throw same Exception io is undefined !

### Does this issue happen every time?
_Yes

THANK YOU

**Comment by ggarabedian** [comment]
@kefahB, the cloud builds are implemented in such a way on purpose and changing this behavior will result in a performance degradation of the build process.  

To workaround this limitation, you can download the plugin (module) in question and place it in the folder of your app, then make the necessary modifications to it and finally [add it to your project from the local path](https://docs.nativescript.org/plugins/plugin-reference#install-a-plugin). This will ensure that the local version (the fixed one) of the plugin is taken during the cloud build and not the one from npm.

**Comment by kefahB** [comment]
@ggarabedian Thank you for reply 👍
