### ISSUE TITLE
Cloud build for iOS fails with ** ARCHIVE FAILED **

### ISSUE THREAD

**Issue by ntrpnr** [NativeScript/sidekick-feedback#225]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Cloud build for iOS fails with \*\* ARCHIVE FAILED \*\*

### Which platform(s) does the issue occur on?
iOS cloud build (initiated from Windows)

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop:** 1.10.3-v.2018.6.26.1 (latest)
- **NativeScript CLI:** 4.2.0-2018-06-06-11764
- **CLI extension nativescript-cloud:** 1.12.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Start a cloud build for iOS

I have tried to do a clean build as well.

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/ntrpnr/3a7fe0a4beeb71d628ebdafa4ce334e0

**Comment by ntrpnr** [comment]
After trying a local build on my Mac, I got this message:
```
[18-07-09 10:24:15.588] (CLI) Code Signing Error: The file "/Users/eriknilsson/projects/dottar.mobile/platforms/ios/DottarApp\DottarApp.entitlements" could not be opened. Verify the value of the CODE_SIGN_ENTITLEMENTS build setting for target "dottarmobile" and build configuration "Debug" is correct and that the file exists on disk.
```


It seems like Sidekick automatically added a line for ```DottarApp.entitlements``` which is a file that does not exist. After changing the name of my entitlesments file, it worked.

Is there any documentation regarding how Sidekick treats entitlement files?

**Comment by ThunderAnimal** [comment]
Some Problem here....

### Version numbers that the issue occurs with
- **NativeScript Sidekick Desktop:**  1.11.0-v.2018.7.12.1
- **NativeScript CLI:** 4.1.0
- **CLI extension nativescript-cloud:**  1.12.0
- **CLI extension nativescript-starter-kits:**  0.3.4
- **tns-ios:** 4.1.1

### Client Logs
https://gist.github.com/ThunderAnimal/bc393b2aa2ea6b1ca0ef2b7d4790b5c3 (release)
https://gist.github.com/ThunderAnimal/c4ab90ad4a050d72924e2a69246dcf54 (debug)

Also I check the _build.xconfig_. The entitlements file is valid.
```
// You can add custom settings here
// for example you can uncomment the following line to force distribution code signing
// CODE_SIGN_IDENTITY = iPhone Distribution 
// To build for device with XCode 8 you need to specify your development team. More info: https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html
DEVELOPMENT_TEAM = XXXXXXXX;
ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage;

CODE_SIGN_ENTITLEMENTS = behaelterMobile\behaelterMobile.entitlements
```

The File *behaelterMobile.entitlements* exists under *app/App_Resources/iOS* and after adding platform iOS also under *platforms/ios/behaelterMobile/behaelterMobile.entitlements*.


![folder_structure_behaerltermobile-entitlements_1](https://user-images.githubusercontent.com/6366929/42751866-728a6a2a-88ec-11e8-9f81-df1225656ca1.PNG)
![folder_structure_behaerltermobile-entitlements_2](https://user-images.githubusercontent.com/6366929/42751867-751f90bc-88ec-11e8-9e11-b85022543def.PNG)
