### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#237]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report.
Local project will not build, I get the following error:

[18-07-25 12:05:52.023] (CLI) (node:10189) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

I don't have a plugin called Tapable so I'm not sure how to fix this.

### Which platform(s) does the issue occur on?
iOs

### Provide the following version numbers that the issue occurs with:

Version: 1.11.1-v.2018.7.17.4 (latest)
NativeScript CLI version: 4.1.2
CLI extension nativescript-cloud version: 1.13.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Build

### Does this issue happen every time?
Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

[main_18-07-25_12-02-52.098.log](https://github.com/NativeScript/sidekick-feedback/files/2229060/main_18-07-25_12-02-52.098.log)

**Comment by ggarabedian** [comment]
Hello @bradrice,

The reported error is connected to the version of the webpack (or nativescript-dev-webpack) module used in your application. To investigate this further, we would need to reproduce the issue on our end. To do this, I would ask you to share the content of your **package.json** file.

**Comment by bradrice** [comment]
OK, I am attaching. The odd thing is I can compile using the cli. In order to do so after trying to use Sidekick, requires me to remove the platform and re-add it using the cli. I was hoping Sidekick would make development smoother, but I seem to fight with it worse than the cli.

`
{
  "description": "Class 2.0 NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "https://github.com/toolingudev/classappnativescript.git",
  "name": "class2tns",
  "version": "0.1.0",
  "scripts": {
    "test": "ng test"
  },
  "nativescript": {
    "id": "com.toolingu.class2tns",
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.0.6",
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "async-await": "^0.1.40",
    "lodash": "^4.17.10",
    "moment": "^2.22.0",
    "nativescript-angular": "^6.0.6",
    "nativescript-audio": "^4.3.5",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-orientation": "^2.2.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "3.5.9",
    "nativescript-ui-sidedrawer": "^4.1.1",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-videoplayer": "^4.1.0",
    "nativescript-webview-interface": "^1.4.2",
    "nativescript-xmlobjects": "^1.1.4",
    "node-sass": "^4.9.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.0.0 || >=6.1.0",
    "tns-core-modules": "^4.1.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0-rc.0",
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "~6.1.0-beta.1",
    "@types/lodash": "4.14.68",
    "@types/node": "~6.0.60",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "codelyzer": "~4.0.1",
    "jasmine-core": "^3.1.0",
    "karma": "^2.0.5",
    "karma-jasmine": "^1.1.1",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.6.0",
    "nativescript-dev-webpack": "^0.14.4",
    "tns-platform-declarations": "^3.4.1",
    "ts-node": "~3.3.0",
    "tslint": "^5.8.0",
    "typescript": "~2.7.2",
    "webpack": "^4.16.2"
  },
  "author": "bradrice"
}
`

**Comment by ggarabedian** [comment]
Hello @bradrice,

I apologize for the delayed response. 

Unfortunately, we are not able to reproduce the described behavior when testing a sample app with the provided **package.json** file. I even tried to mix cloud builds with Sidekick and local builds with the CLI, but the process completes successfully every single time. With this in mind, I am not sure of how much help we can be without being able to reproduce and debug the issue locally. 

Having said that, in addition to removing the platform/ios folder, you might want to delete the **node_modules** folder as well and see if this makes any difference.

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
