### ISSUE TITLE
Incorrect Certificates

### ISSUE THREAD

**Issue by delanick** [NativeScript/sidekick-feedback#241]
I move between projects a lot, and I see the reason I'm getting ARCHIVE FAILED errors is because Sidekick keeps using the incorrect certs and mobileprovisions for my apps. It doesn't keep track of which files each app uses, can you guys please correct this?

**Comment by ggarabedian** [comment]
Hello @delanick, 

Actually, the behavior you describe is the intended one for the management of certificate and mobile provisions in Sidekick. The decision for this implementation was reached after a lot of internal discussions and user feedback. The conclusion was that most people use a single certificate for their applications and this implementation would benefits them the most.

Nevertheless, we continuously look for ways to improve the UI and overall experience with the certificate management and while we cannot make any promises, we will investigate if we have any options to extend this behavior to cover more scenarios.

**Comment by delanick** [comment]
@ggarabedian Amazing, thank you! :)
