### ISSUE TITLE
tns doesn't seem to detect Microsoft Store iTunes installation?

### ISSUE THREAD

**Issue by john-landgrave** [NativeScript/sidekick-feedback#243]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I updated iTunes, which installed the version from the Microsoft Store, and now `tns devices` is showing "iTunes is not installed" message.

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:

- **NativeScript CLI:** 4.1.2

### Tell us how to recreate the issue in as much detail as possible
1. Update iTunes on Windows, which should prompt you to replace your iTunes installation
2. Run `tns devices`
3. See error message

### Does this issue happen every time?
Appears to, yes.

**Comment by ggarabedian** [comment]
Hello @john-landgrave,

This is a known issue and for the time being the only workaround we can offer is for you to download and install iTunes from the [Apple website](https://www.apple.com/itunes/download/). 

To download the package directly from the link provided above, you need to click on **Windows >** under the "Looking for other versions?" label and then click on the **Download now (64-bit)** button. 

I hope this helps.

**Comment by john-landgrave** [comment]
I'll try it again, but I did that earlier and still no dice. Any thoughts there? And is there anything magic I need to do on the device a la enabling USB debugging on Android?

**Comment by ggarabedian** [comment]
@john-landgrave, this error message is showing only when you do not have iTunes installed on your machine or when you are using the Microsoft Store version, which does not contain some of the components required for debugging and deploying on a device.

Apart from that, once the device is detected successfully, you only need to ensure that the device is [trusted](https://support.apple.com/en-ca/HT202778) and that the app is code signed with a development certificate and mobile provision.

**Comment by Ghits-nl** [comment]
I have this message when try the "tns devices" command:
iTunes is not installed. Install it on your system and run this command again.
