### ISSUE TITLE
Build IPA - certificate error

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/sidekick-feedback#25]
Hi,

I have generated iOS IPA file. Build type = local build. Configuration = release. 
I have set up certificate and distribution provision profile.
![snimek obrazovky 2017-08-06 v 21 47 40](https://user-images.githubusercontent.com/4247839/29006464-e67065f8-7af0-11e7-969a-1e6e3eb3f37a.png)

But when I try to upload app to App store by Application loader it fails with this error. I dunno what to do. Yes of couse I have paid apple developer account.

![snimek obrazovky 2017-08-06 v 21 54 01](https://user-images.githubusercontent.com/4247839/29006512-d45a76f0-7af1-11e7-92bb-576986a13c9a.png)

Thank you for help

**Comment by stoskov** [comment]
Hi @b4rtt,

The "Manage iOS Provisioning and Certificates" window is only applicable for cloud builds. For local builds the certificates and provisioning profiles imported in xCode matter. Please, check the imported profiles there and inform is if you still have the problem,

**Comment by b4rtt** [comment]
@stoskov still same problem. This is how looks my xCode
![snimek obrazovky 2017-08-07 v 21 09 17](https://user-images.githubusercontent.com/4247839/29041871-cefd1262-7bb4-11e7-8f0d-b269586b935f.png)

**Comment by stoskov** [comment]
In order to publish to the store you should use distribution certificate and provisioning profiles. As seen on the picture your certificate is developer and this is why you cannot publish the app. Please create them and try again.

**Comment by b4rtt** [comment]
@stoskov 
And what is right way how to use Sidekick?

1) I have empty folder /platforms/
2) open project in sidekick
3) local build (cerificates could be empty - it is only for cloud build)
4) build is done (I have IPA file, but not signed - in (plartforms/ios/build/device))
--- what next? Open xcode project, set certificates and build it in Sidekick again? Because in "Application loader" I need signed IPA file.
What is right workflow?

Thank you so much for your time! :)

**Comment by b4rtt** [comment]
Because if I do it like this. Edit xcode file. Set up right certificate and provision profile and try to build it again in sidekick I see this error

[17-08-08 12:09:39.218] (Info) Error Domain=IDEProvisioningErrorDomain Code=9 ""PiratiGo.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="PiratiGo.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the "Default" build configuration in the project editor.}

**Comment by Mitko-Kerezov** [comment]
Hello, @b4rtt 
You are trying to do a publish build which is something different than a mere release build. Currently builds that can be published to the App Store cannot be produced with Sidekick, however we are actively working towards achieving this.

What you can do instead is use the NativeScript command-line interface to publish your build. In order to do that you would need to:
1. Open the Terminal application
1. Execute `cd <path-to-your-application>`
1. Execute `tns publish ios`

The command requires some parameters - your Apple ID, your Password, the identifier of the provision you'd like to build with and the name of your code sign identity (your certificate). The CLI will prompt you for each of them.

Let me know if this helps.

**Comment by b4rtt** [comment]
@Mitko-Kerezov 
Still got this error 

Archive at: /Users/roman/Desktop/eSports/PiratiGo/platforms/ios/build/archive/PiratiGo.xcarchive
2017-08-08 18:04:48.097 xcodebuild[1496:21642] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/c8/kcxg82ln2mn7qy9v0rtppm8w0000gn/T/PiratiGo_2017-08-08_18-04-48.095.xcdistributionlogs'.
2017-08-08 18:04:53.243 xcodebuild[1496:21642] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7f8b24e5f400>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
    "Error Domain=IDEProvisioningErrorDomain Code=9 \"\"PiratiGo.app\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"PiratiGo.app\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the \"Default\" build configuration in the project editor.}"
)}
error: exportArchive: "PiratiGo.app" requires a provisioning profile.

Error Domain=IDEProvisioningErrorDomain Code=9 ""PiratiGo.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="PiratiGo.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the "Default" build configuration in the project editor.}

There you can see my repository? Is't something wrong there? :-O

https://github.com/b4rtt/PiratiGo

**Comment by Mitko-Kerezov** [comment]
@b4rtt 
Could you try the following:
1. Remove `platforms` directory
1. Run `tns publish ios`

And let me know how it goes.
As a side note: could you run `ls -al ~/Library/MobileDevice/Provisioning\ Profiles` and tell me whether there are any files inside said directory.

**Comment by b4rtt** [comment]
@Mitko-Kerezov 

When I do it I see this error.

```
Check dependencies
Signing for "PiratiGo" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 11.0'
Code signing is required for product type 'Application' in SDK 'iOS 11.0'
```

ls -al ~/Library/MobileDevice/Provisioning\ Profiles
Show me this
```
total 232
drwxr-xr-x  16 roman  staff   512 Aug  8 12:29 .
drwxr-xr-x   4 roman  staff   128 Aug  6 10:03 ..
-rw-r--r--   1 roman  staff  7563 Jul 21 09:38 11a7e25d-0533-4282-9ba1-447c9bf8e21d.mobileprovision
-rw-r--r--   1 roman  staff  7563 Jul 29 09:30 1f69ea6e-b326-485e-b324-9f5b00ef3926.mobileprovision
-rw-r--r--   1 roman  staff  7557 Jun 22 18:11 34016d3d-86a3-4b14-916f-c71bd0433879.mobileprovision
-rw-r--r--   1 roman  staff  7557 Jul  9 17:09 392de015-220e-49db-b02f-15ada2665001.mobileprovision
-rw-r--r--   1 roman  staff  7584 Jul 14 09:06 3ac81c0c-cc24-4d47-9b9a-cef60f9ec80d.mobileprovision
-rw-r--r--   1 roman  staff  7563 Jul 11 17:55 3e52a96a-d83d-4526-a06f-06d3ab7010aa.mobileprovision
-rw-r--r--   1 roman  staff  7584 Jun 14 11:43 429b88a2-02d6-4325-8fd3-ee0efeb5e324.mobileprovision
-rw-r--r--   1 roman  staff  7517 Aug  5 09:10 5056d786-ae00-492e-8d6f-b18cec7ac512.mobileprovision
-rw-r--r--   1 roman  staff  7566 Jul 10 16:04 6ab8abf5-219b-4630-8788-2dec3018df56.mobileprovision
-rw-r--r--   1 roman  staff  7563 Jun 24 12:45 6ed1d463-e47c-4907-91f5-a012b747310f.mobileprovision
-rw-r--r--   1 roman  staff  7410 Aug  7 21:11 70362c19-d6fc-4f85-87e5-c3d3cb60cd0f.mobileprovision
-rw-r--r--   1 roman  staff  9445 Aug  8 12:29 821feb37-0c18-4b4f-9070-b7ab879dff8f.mobileprovision
-rw-r--r--   1 roman  staff  7557 Jul 10 16:11 82ae210f-943a-451e-874d-df0a74517637.mobileprovision
-rw-r--r--   1 roman  staff  7584 Jun 22 17:33 b9191f4c-0712-42e3-bc88-597efb4add28.mobileprovision
```

**Comment by b4rtt** [comment]
@Mitko-Kerezov But when I start tns publish ios I see this

```
No mobile provision identifier set. A default mobile provision will be used. You can set one in app/App_Resources/iOS/build.xcconfig
No code sign identity set. A default code sign identity will be used. You can set one in app/App_Resources/iOS/build.xcconfig
```

Maybe it's problem?

**Comment by Mitko-Kerezov** [comment]
@b4rtt 
I've tried a couple of ways to reproduce the issue you're having, however I didn't manage to. I suspect that there's something wrong in either your provisioning profile (which is more likely) or in your certificate (less likely).

In order to eliminate that problem could you go to [developer.apple.com](http://developer.apple.com/) and re-create your provisioning profile and certificate and try again.

Let me know how it goes.

**Comment by Mitko-Kerezov** [comment]
Closing this in favor of https://github.com/NativeScript/nativescript-cli/issues/3059. We'll continue the discussion there
