### ISSUE TITLE
Problem installing and running standalone and plugin Sidekick on Win7 x64 machine.

### ISSUE THREAD

**Issue by rob-j47** [NativeScript/sidekick-feedback#251]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I have NativeScript CLI installed and running fine, it passes the tns doctor checks. I created a project from a template. I did a build, deploy and run on a connect Android device. All works fine.

I have issued the tns proxy command and there is NO proxy configured. 
I have successfully run the tns login command and logged in with my Telerik account.

I have tried to install and run both NativeScript Sidekick and NativeScript Sidekick plugin in VS2017. I do not have any success. 

When I click on the standalone Sidekick app, it opens to a dialog box. Although I see the application in the Task Manager, I have a hidden / blank window. I have left this dialog open for over 4 hours but have never successfully launched the application. Uninstall / reinstall has no effect.

I tried installing the plugin for VS2017. I have VS2017 Enterprise. I can go to new solution, choose NativeScript project, choose a templates, give project a name and start to create the project. After an hour or so VS2017 is locked up hard with the Sidekick dialog. The only way to abort is killing VS2017 from the task manager.

### Which platform(s) does the issue occur on?
_iOS/Android/Both NOT APPLICABLE<br/>
Windows 7 Professional, Service Pack 1, x64. 32GB memory.

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop: Build from 8/17/2018 (currently it's uninstalled) **
- **Sidekick for Visual Studio: 0.5.0.18071201 ** 
- **NativeScript CLI: - 4.2.1 ** 
- **CLI extension nativescript-cloud: N/A ** 
- **CLI extension nativescript-starter-kits: N/A ** 

> _You can obtain the requested information by following the steps outlined below._

I cannot run the Sidekick (standalone) to launch any kind of menu or about boxes.  I pulled the plugin version from VS2017 About box. CLI version is as reported by tns --version.

### Tell us how to recreate the issue in as much detail as possible
Standalone:
1. Start the application.
2. Dialog box appears but then turns completely transparent/invisible. Sometimes switching with Alt-Tab key to the application will show the dialog, most times not though.
3. Wait 4 hours while nothing happens.
4. Kill app from Task manager after it is apparent nothing is ever going to happen.
5. This happens all the time.

VS2017 Plugin
1. File, New Project
2. NativeScript, General, Javascript.
3. Choose Tab Navigation project template.
4. Browse to c:\temp\NativeScript
5. Enter project name "Test1"
6. Click OK
7. Dialog with no frame or buttons appears.
8. Folder for project is created in correct location.
9. VS2017 is now locked up until killed with the Task Manager, no way to cancel or about, no modal dialog to switch to. No pop-up error or message in Output tab of VS.

### Does this issue happen every time?
Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

I cannot run the Sidekick (standalone or plugin) to launch any kind of menu or about boxes. Your log files should not be in hidden AppData folder (which is where I found them) - tell me which ones you need and I will reinstall, try to run and get them and upload them.

Thanks in advance for your assistance, 

Rob

**Comment by ggarabedian** [comment]
Hello @rob-j47,

The reported behavior might be related to your proxy configuration or an antivirus program that blocks some of the requests made by Sidekick. To avoid speculating as to what is causing the issue, I would ask you to share the logs. As you have already found out they are located in the AppData folder, which is the location where most applications place their cache, configuration and log files. I understand that in your case those files are hard to discover, but through the UI interface they can be accessed quite easily. Here are the locations of the logs and which files you should share. 

- The Sidekick logs are located in `%appdata%/NativeScriptSidekick/logs`. You should send us the latest `main` and `console` files. The `main` file is more important, but the `console` one contains environment specifics that might prove helpful as well.
- The logs of the extension for Visual Studio can be found in `%appdata%/NativeScriptSidekickVS/logs`. The latest `main`, `cli` and `console` files should help us identify what is causing the issue in Visual Studio.

**Comment by rob-j47** [comment]
Just bumping this thread. Turning off my antivirus completely (including all network monitoring) and Sidekick still does not run on Win7 x64. Dialog box is there but hidden. Running Node command prompt "tns doctor" reports all is well. NativeScriptSidekick shows up in task manager, but it cannot display modal window for some reason. Looking in AppData folders I see it downloaded a new version, right now I think it is asking for me to update something but I cannot see full dialog to click and proceed.

I have running on my personal Win10x64 box but would like to get this going on my development machine.

Rob

**Comment by ggarabedian** [comment]
Hello Rob,

Thank you for sharing the requested logs and for taking the time to capture images of the issue. My apologies for the delayed response, I was left under the impression that disabling the antivirus works out for you.

We were not able to reproduce the described behavior when testing locally and we cannot find any error messages in the provided logs that would explain this behavior. The only error is the "Error: self signed certificate in certificate chain" , which might be related to the proxy, or to the Fiddler instance you have running (in case you had it running while using Sidekick). If you were not running Fiddler at this moment, you could try setting the `NODE_TLS_REJECT_UNAUTHORIZED` variable to 0. Below are the steps on how you can achieve this:
1) Open the Environment Variables window. To fastest way to do this is to type "env" in the Windows 10 search bar and select "Edit environment variables for your account".
2) Select New under "User variables for _username_".
3) For Variable name, enter `NODE_TLS_REJECT_UNAUTHORIZED`.
4) For Variable value, enter `0`.
5) Click OK.

If the above does not help, can you please enable the extended logging for Sidekick and share the produced logs again. Here are the steps to achieve that:
1) Ensure that Sidekick is not running (in the task manager as well) and delete the old files in `%appdata%\NativeScriptSidekick\Logs`.
2) Navigate to `%appdata%/npm/node_modules/nativescript/config` and open the `config.json` file that is in this folder.
3) Change `"DEBUG": false` to `"DEBUG": true`.
4) Start Sidekick, reproduce the problem and then completely stop Sidekick (from the task manager).
5) Send us the newly created log files

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
