### ISSUE TITLE
Version 1.12.0 doesn't work on NodeJS 10.9.0 (Ubuntu)

### ISSUE THREAD

**Issue by robregonm** [NativeScript/sidekick-feedback#257]
## Please, provide the details below:
After upgrading from 1.11.1 to 1.12.0, Sidekick is not loading anymore.

### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem
_Previous version: 1.11.1-v.2018.7.17.4-669 worked perfectly, without issues_

### Which platform(s) does the issue occur on?
_Ubuntu/Debian/Elementary_ <br/>

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop: 1.12.0-v.2018.8.14.2-684** 
- **NativeScript CLI: 4.2.3** 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. You'll see a message saying: NodeJS >= 8.0.0 <= 10.5.0 (detected version is 10.9.0)

### Does this issue happen every time?
_Yes_

**Comment by teobugslayer** [comment]
Hi @robregonm ,

Node 10.6 introduced breaking change which prevented interprocess communication between Electron and pure Node.js processes. As a temporary work-around, we require Node.js 10.5 or lower version. This is until we can find a good fix to this issue.

**Comment by ggarabedian** [comment]
Hello @robregonm, 

Thank you for reporting this problem!

As @teobugslayer has mentioned, we are experiencing issues with the latest versions of NodeJS (10.5.0 and above) and we are currently investigating possible ways to resolve them. However, those issues are Windows specific and don't affect Linux and macOS systems. 

Having said that, your comment is completely correct and we will remove the 10.5.0 limitation from the macOS and Linux versions of Sidekick with our next release. We will do our best to have this fix released by the end of next week. In the meantime, the only workaround we can suggest is to use an older NodeJS version. 

Thank you for your patience and understanding!

**Comment by robregonm** [comment]
@teobugslayer @ggarabedian Thanks for your reply.
In the meantime, Is there a place where I can download previous versions of SideKick?
Thanks for your hard work..

**Comment by ggarabedian** [comment]
@robregonm, apologies for the delayed response. 

Unfortunately, there is no way to download an older version of Sidekick and even if there was, the client will not work correctly because it won't be compatible with the latest version of our cloud infrastructure.

Having said that, we are planning to release the new version of Sidekick (one with the fix about the supported NodeJS versions) later today. After we release the update and you apply it, you should no longer see the reported error.

**Comment by robregonm** [comment]
@ggarabedian Thanks, no problem, take your time ;-)
I just wanted to find a workaround for this issue :-)

**Comment by robregonm** [comment]
Just downloaded latest version (1.12.1-v.2018.9.3.2-691) and it work fine again :-)
Thank you very much. Closing.
