### ISSUE TITLE
Integrate WSL

### ISSUE THREAD

**Issue by TheDeepNate** [NativeScript/sidekick-feedback#258]
## Please, provide the details below:

So I use windows, but my dev enviroment is under WSL (windows subsystem for linux) I have Node, NPM etc, but when I open sidekick, it requires me to install these under my windows enviromenent.

### Did you verify whether this issue has already been reported here?
_Yes/No_

Yes

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

Top

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

Windows (WSL -- Ubnuntu)

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:**  Latest
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:**

**Comment by teobugslayer** [comment]
Hi @TheDeepNate ,

This is by design. We do not have immediate plans for supporting interoperability of Sidekick and WSL node.

As a workaround, you may install Node.js distribution for Windows.
