### ISSUE TITLE
SideKick -> MackBoock -> Ventilator 

### ISSUE THREAD

**Issue by kefahB** [NativeScript/sidekick-feedback#261]
Thank you for Sidekick is really cool :-)

I have à MacBook Pro SSD and 8G RAM .. but when I build with Sidekick the ventilator turn very fast .. the problem is will still turn like this until I close Sidekick; a few seconds and the ventilator will stop !

This happen only with Sidekick and i never hear my ventilator else if...

This is normal ?

Thanks

**Comment by ggarabedian** [comment]
Hello @kefahB,

Based on your description of the issue, it sounds very similar to #61. Can you please check if the CPU usage is high on your end as well? If this is so, can you try adding the following environment variable (as suggested in the issue linked above): 
```
TSC_NONPOLLING_WATCHER="1"
```

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
