### ISSUE TITLE
I can not connect my iPhone SE to Sidekick on Ubuntu 18.10

### ISSUE THREAD

**Issue by WebRuin** [NativeScript/sidekick-feedback#266]
## Please, provide the details below:

I can not connect my iPhone SE to SideKick on Ubuntu 18.10

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Sidekick is not seeing my iPhone SE connected via USB to Thunderbolt cable

➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Cosmic Cuttlefish (development branch)
Release:        18.10
Codename:       cosmic

### Which platform(s) does the issue occur on?
I have only tried iOS (JS Template)

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop**
- **NativeScript CLI: nativescript --version 4.2.4**

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Connect device
3. See "No device found

### Does this issue happen every time?
YES

**Comment by teobugslayer** [comment]
This is a known limitation. Sidekick depends on the iTunes drivers to interact with iOS devices.

That's why on Linux only Android development is available.

To dovelop for iOS with Sidekick, you need to run it on Windows or Mac.
