### ISSUE TITLE
NativeScript Sidekick Network Debugger

### ISSUE THREAD

**Issue by sputn1k** [NativeScript/sidekick-feedback#267]
I can't seem to see any Network request outputs from the Debugger?

I am running the latest version of the NativeScript SideKick (installed on Mac OSX). 

I have `"Start Debugger"` checked and have the Network tab open - When I make an HTTP request I don't see anything in the Network activity?  

My app has the `http` module added. I am receiving a  `console.log` response all OK so I know it's making the calls just nothing is outputting in the Network activity log in the Debugger?  

```
const httpModule = require("http");

httpModule.request({
    url: PATH,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    json: true,
    content: JSON.stringify({
        action: "auth",
        username: this.email, 
        password: this.password
    })
}).then((response) => {
    const obj = response.content.toJSON();
    console.log("Response = "+obj.response);
}, (e) => {
    console.log("Error: ");
    console.log(e);
});

```

**Comment by tsvetie** [comment]
Hello @sputn1k,
The Network panel works out of the box only for the built-in [http module](https://docs.nativescript.org/ns-framework-modules/http). You can read more about the Network panel support [here](https://docs.nativescript.org/tooling/debugging/chrome-devtools#network). I tried to reproduce the problem (note: I tested with a GET request) and I can see the request in the panel.

I am not aware of any bugs, related to this functionality. Can you send me the log files that Sidekick created during a session, in which you reproduced the problem? You can open the log files folder by selecting _Help menu -> Show Logs_. Additionally, do you reproduce the problem on both Android and iOS devices?

**Comment by sputn1k** [comment]
Hi @tsvetie 

Sorry for the delay responding. 

I have been using `tns debug ios` instead of launching it from the **NativeScript SideKick**. It's providing a dynamic link I have been opening in the browser. Which is outputting the Network HTTP Requests all OK. 

When **NativeScript SideKick** Automatically launches a `Developer Tools` window. The URL says - http://mail.xml - could that be the issue? Screen grab attached - 
![screen shot 2018-10-03 at 15 42 05](https://user-images.githubusercontent.com/294358/46418123-049d4a80-c723-11e8-910b-2a2f37efa79f.png)

I experienced the bug on iOS (haven't tried Android yet). 

You could close this Issue as I found a workaround now for the time being. 

Thanks

**Comment by mryraghi** [comment]
@sputn1k thanks for sharing the workaround

**Comment by trainerbill** [comment]
@tsvetie what about the angular module?  I have tried everything and cannot get an http request to show up in chrome dev tools or safari(--inspector) when using angular and the nativescript http modules.
