### ISSUE TITLE
*.p12 without a password.

### ISSUE THREAD

**Issue by dmytro-gokun** [NativeScript/sidekick-feedback#269]
Somehow, sidekick would not allow me to use a certificate file w/o password. Is that by design?

**Comment by tsvetie** [comment]
Hi @dmytro-gokun,
Your assumption is correct - this is by design for cloud builds. You can refer to this issue for more details - #21.

**Comment by dmytro-gokun** [comment]
@tsvetie Thanks a lot for the answer! You should've searched better :)
