### ISSUE TITLE
Specifying iOS build only for iPad not working (app can be deployed on iPhone)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/sidekick-feedback#274]
In the [iOS properties](https://docs.nativescript.org/sidekick/user-guide/configure-app/ios-properties) we can specify the device family to build for. However, checking only **iPad** is actually creating a build for iPhone as well.

Possibly related to the way [UIDeviceFamily](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW11) is added in info.plist.

> Important: Do not insert this key manually into your Info.plist files. Xcode inserts it automatically based on the value in the Targeted Device Family build setting. You should use that build setting to change the value of the key

Reported via the feedback form.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4038](https://github.com/NativeScript/nativescript-cli/issues/4038) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rosen-vladimirov** [comment]
Reopening this as it is a problem with Cloud builds only.

**Comment by ggarabedian** [comment]
I am closing this issue because the bug has been fixed in the latest version of Sidekick.
