### ISSUE TITLE
What is the minimum android API Version that should be used for Sidekick 

### ISSUE THREAD

**Issue by baskar3078** [NativeScript/sidekick-feedback#276]
## Please, provide the details below:
What is the minimum android API version that should be used for SideKick - Getting Started Chapter 1 instructions as per the documentation ?

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Follow the instructions given in below link provided in Chapter 1. 
https://docs.nativescript.org/sidekick/getting-started/create-app

The project builds successfully. When the app is deployed to Android Emulator API -19, version 4.4 and x86 Image, the application hangs with out starting.

### Which platform(s) does the issue occur on?
Verified only on Android. Android Emulator API -19, version 4.4 and x86 Image
Android <br/>
Windows

### Provide the following version numbers that the issue occurs with:

NativeScript Sidekick Version: 1.13.0-v.2018.10.5.2 (latest)
NativeScript CLI version: 4.2.4
CLI extension nativescript-cloud version: 1.14.0
CLI extension nativescript-starter-kits version: 0.3.5

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application 
2. The application hangs.

### Does this issue happen every time?
Yes

### Send the client logs
No issues observed in logs. The build completes successfully.

**Comment by ggarabedian** [comment]
Hello @baskar3078,

The minimum Android SDK version that can be used in Sidekick is identical to the one required by NativeScript - Android 4.2 SDK (API level 17). This information is available in the [NativeScript System Requirements article](https://docs.nativescript.org/angular/start/general-requirements).

Having said that, I created a new Master-Detail with Firebase app and successfully deployed it on an Android 4.4 emulator. The app was working as expected and I did not encounter any issues. Can you tell me if you are trying to run the newly created template or you have modified it in some way? Additionally, when you launch the app on the device, do you see any error messages in the **Device Console** (which can be accessed through the OUTPUT window)?

**Comment by baskar3078** [comment]
@ggarabedian Thanks for responding quickly. For some reason it was taking more time to respond. May be it was for the first time. Now it is working. Please find the logs.

ActivityManager: Start proc org.nativescript.testsidekick for activity org.nativescript.testsidekick/com.tns.NativeScriptActivity: pid=3002 uid=10063 gids={50063, 3003, 1028, 1015}
D/dalvikvm( 3029): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
ActivityManager: Launch timeout has expired, giving up wake lock!
ActivityManager:     92% 3002/pt.testsidekick: 92% user + 0% kernel
D/dalvikvm( 3312): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
ActivityManager: Force stopping org.nativescript.testsidekick appid=10063 user=0: from pid 3312
ActivityManager: Killing 3002:org.nativescript.testsidekick/u0a63 (adj 0): stop org.nativescript.testsidekick
ActivityManager: Force removing ActivityRecord{9d06f4c0 u0 org.nativescript.testsidekick/com.tns.NativeScriptActivity t2}: app died, no saved state

**Comment by ggarabedian** [comment]
@baskar3078, thank you for sharing the device logs. 

From what I can see, only the "ActivityManager: Launch timeout has expired, giving up wake lock!" message can be related to the behavior you describe. Unfortunately, this warning can be caused by a lot of different things, including the "hardware" (for example, the amount of RAM) of the emulator that you have configured.

In any case, I am glad to hear that the issue was only temporary and you are now able to deploy and run your app on the emulated device. Please, let us know if you experience the same behavior again.
