### ISSUE TITLE
Feature request: app name vs project name

### ISSUE THREAD

**Issue by delanick** [NativeScript/sidekick-feedback#278]
Hi,

I'm not sure if this is the right place, or where I should request this of the Sidekick team, but:

Please allow us to change the app's name during the project. Currently (with Sidekick anyway), you can only create a project name, which also doubles as the app name. I would like to be able to change the app's name (the name they see on their phone under the icon image) and Sidekick doesn't allow it. Or is there another way via package.json I can change it?

**Comment by ggarabedian** [comment]
Hello @delanick,

For the time being having a different app and project name is not possible. This is a limitation of the NativeScript CLI, however, we are continuously looking for ways to work around it (as noted in #273).

With the above in mind, you can still change the app name manually by following the suggestions provided in [How to change display name of the application in launcher?](https://github.com/NativeScript/NativeScript/issues/1377). For Android, you should add a _strings.xml_ file in the `app\App_Resources\Android\src\main\res\values` folder as suggested in the [post made by 3rror404](https://github.com/NativeScript/NativeScript/issues/1377#issuecomment-251439195). For iOS, you need to modify the values of the **CFBundleDisplayName** and **CFBundleName** keys in the _Info.plist_ file located in `app\App_Resources\iOS`.

I would like to note that both changes might result in some kind of unexpected behavior in your app (the build can fail or the livesync might stop working) so I recommend using them with caution.

**Comment by SephReed** [comment]
This issues should probably be re-opened as it is a pretty merited feature request, and the feature does not exist.
