### ISSUE TITLE
'Clean Build' using old files?

### ISSUE THREAD

**Issue by berchik** [NativeScript/sidekick-feedback#28]
I’m attempting the `Clean Build` option on ios but the old launch images remain. I’ve recreated the platforms folder and App_Resources contains the new images only. 

Does this mean the cloud build keep using old build’s files or is there something else I should do?

Thanks.

**Comment by ventsislav-georgiev** [comment]
@berchik Could you provide more information regarding the issue, by following the issue template:
* The versions of the different parts of the Sidekick
    - NativeScript CLI:
    - CLI extension nativescript-cloud:
    - CLI extension nativescript-starter-kits:
* The OS you are using.
* The scenario in which the issue happens: 
    - Is it Build, Run on Device or LiveSync?
    - How did you updated the App Resources and does the Sidekick show the new images in the Assets view?
* The Sidekick log files
     - Windows: %AppData%\NativeScriptSidekick\Logs
     - macOS: ~/Library/Application Support/NativeScriptSidekick/Logs
     - Linux: ~/.config/NativeScriptSidekick/Logs

**Comment by berchik** [comment]
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

OS: Windows 10

I use sidekick’s Cloud Build option, then use the QR code to download and install on iphone device

Once I’ve changed to the new launch screens images/backgrounds, I completely erased the folder: `‘\App_Resources\iOS\Assets.xcassets\LaunchImage.launchimage’` and erased `‘ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage’` from build.xcconfig file.
Sidekick shows the right resources in its Assets folder.

App icons did change correctly, launchscreens still show the previous original NS launch images.

Log:
[main_17-08-07_16-18-40.280.zip](https://github.com/NativeScript/sidekick-feedback/files/1205146/main_17-08-07_16-18-40.280.zip)

**Comment by ventsislav-georgiev** [comment]
@berchik We have made several changes in the builds and deploy on device functionalities with the recent release. Also, I successfully went through: 
* Cloud build and deploy
* Splash Screen (LaunchScreen-Center) update for iOS
* Cloud build again
* See the updated Splash on app start

Could you verify if you still manage to reproduce the reported issue?

**Comment by berchik** [comment]
Thanks @ventsislav-georgiev 

I’ve tried and it didn’t change. To fully test it I’ve downloaded sidekick to OSX machine and did a local build with the same code and assets which worked correctly. Then tried cloud build and it worked too. When tried back the win10 cloud build again - it did work. So, there was a cache problem but I'm not sure where.

**Comment by ventsislav-georgiev** [comment]
@berchik I am closing this for now. Feel free to reopen it if you can find a pattern to reproduce it.

**Comment by Delivrator** [comment]
Hello @berchik @ventsislav-georgiev 
I add a similar issue. It seems the cache problem is on the phone (or simulator).
Uninstall the app from the phone, restart the phone, re-install the app. Your Launch Image should be updated.
