### ISSUE TITLE
"Open Shell" button

### ISSUE THREAD

**Issue by toddanglin** [NativeScript/sidekick-feedback#29]
It might just be me, but I found the "Open Shell" button confusing.

On a Mac, I guess I would expect that button to say "Open Terminal."
On Windows, probably "Open Cmd Prompt"?

Not sure if we can "localize" this text to the different environments where Sidekick runs. If we can't, I think I'd suggest "Open Terminal" as the default since that's what we use in the NativeScript docs. Just a suggestion.

**Comment by teobugslayer** [comment]
Todd,

Indeed this was a compromise to get the build out of the doors as soon as possible. The suggestion is sound and we can implement it in one of our next updates.

**Comment by elena-gancheva** [comment]
This issue has been implemented and will be available with the next release.
