### ISSUE TITLE
Cannot find module temp

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#290]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I can't seem to get the newest version of Nativescript Sidekick to launch on my Mac. I get a message "Cannot find module temp"

### Which platform(s) does the issue occur on?
macOSX

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
Version: 1.13.0-v.2018.10.5.2 (latest)
NativeScript CLI version: 4.2.4
CLI extension nativescript-cloud version: 1.14.2
CLI extension nativescript-starter-kits version: 0.3.4

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. error, never gets beyond the startup screen.

### Does this issue happen every time?
yes
[main_18-10-30_12-24-43.401.log](https://github.com/NativeScript/sidekick-feedback/files/2530554/main_18-10-30_12-24-43.401.log)
[prerequisites_18-10-30_12-13-18.633.log](https://github.com/NativeScript/sidekick-feedback/files/2530555/prerequisites_18-10-30_12-13-18.633.log)

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

**Comment by ggarabedian** [comment]
Hello @bradrice,

Based on the error message, it looks like the NativeScript CLI or one of its extensions (nativescript-cloud) are corrupted. Can you please open a Terminal, run the `tns extension uninstall nativescript-cloud` command and then launch Sidekick again.

If the above does not help, I would ask you to open a Terminal, execute the `tns doctor` command and share the resulting log. This will output information about any outstanding issues with the NativeScript CLI or your environment and help us determine what might be causing the problem.

**Comment by bradrice** [comment]
uninstalling nativescript-cloud did in fact allow my Sidekick to launch.
