### ISSUE TITLE
Cloud Publish to the App Store fails with NoSuchKey error

### ISSUE THREAD

**Issue by drophit** [NativeScript/sidekick-feedback#291]
### Did you verify whether this issue has already been reported here?
**_Yes**

### Tell us about the problem
Using cloud publilsh fails with an error. Cloud build to device works. the .ipa is there however upload fails after about 5mins.

### Which platform(s) does the issue occur on?
_iOS <br/>
_Windows 10 64_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
Version: 1.13.0-v.2018.10.5.2 (latest)
NativeScript CLI version: 4.2.4
CLI extension nativescript-cloud version: 1.14.2
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the application
2. Select Run/Publish
3. Select Apple App Store
4. Webpack ON
5. AOT OFF
6. Publish

### Does this issue happen every time?
_Yes

### Send the client logs
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>OTk2NzQ2NDktZGQ1OC00ZDkzLTYxZDMtOWJhY2U5YjY2ODNh/results.json</Key><RequestId>1AB76AAF3DC34F90</RequestId><HostId>CbTFmG6DS6fQSVOQ5e/nlpvYCLp8XoxRzjMYP8bnZfZIjzGgfxV6r7dzU6jxb7QfNokIc/I07F0=</HostId></Error>, Error: The server returned unexpected response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>OTk2NzQ2NDktZGQ1OC00ZDkzLTYxZDMtOWJhY2U5YjY2ODNh/results.json</Key><RequestId>1AB76AAF3DC34F90</RequestId><HostId>CbTFmG6DS6fQSVOQ5e/nlpvYCLp8XoxRzjMYP8bnZfZIjzGgfxV6r7dzU6jxb7QfNokIc/I07F0=</HostId></Error>
    at IncomingMessage.responseStream.on (C:\Users\drophit\AppData\Roaming\npm\node_modules\nativescript\lib\common\http-client.js:133:45)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[main_18-11-01_12-41-51.089.log](https://github.com/NativeScript/sidekick-feedback/files/2540106/main_18-11-01_12-41-51.089.log)

**Comment by ggarabedian** [comment]
@drophit, thank you for bringing this issue to our attention. 

The problem was related to our cloud infrastructure.  We have taken the necessary steps to fix the issue and you should no longer experience it when publishing your application.

**Comment by drophit** [comment]
Thanks!

**Comment by drophit** [comment]
Looks like it is working as expected - is there any way to determine publish systems "health" - this issue held us up for quite a few days past our deadline :(

**Comment by ggarabedian** [comment]
@drophit, it's good to hear that the issue is now resolved and we are sorry to hear that it delayed your release. We still do not have a public dashboard that shows the current status of our services, but we have this in our roadmap and we hope to implement it soon.

**Comment by ShyshkovOleg** [comment]
Hi, everyone. Could not publish to AppStore too. The error is:
Error: The server returned unexpected response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>ZTkwYmUyYzMtZDU3Mi00ZmRjLTYyNGUtMjYzZjE3ZDU5Mzgz/results.json</Key><RequestId>F9007BB945AF18DC</RequestId><HostId>1S4OFClrPxpqNQjJqJMk8hHebwjSJxv/+7vMO6OjomqDZlhqib9cuavgQebJ8iOZ+/kqVoYdGYM=</HostId></Error>

Is there an issue with AWS or I've missed something ?

**Comment by drophit** [comment]
This looks like a container/cloud storage bug in the Sidekick code in which the binary can not be found (probably a persistence issue) - the sidekick team fixed this once before hopefully they fix soon :(

**Comment by drophit** [comment]
Working now thanks!

**Comment by throwingdarts** [comment]
Having same issue this evening. :-(
