### ISSUE TITLE
Local iOS build fails due to missing Provisioning Profiles

### ISSUE THREAD

**Issue by VeeK727** [NativeScript/sidekick-feedback#295]
### Did you verify whether this issue has already been reported here?
The issue has been discussed previously but there were no useful fixes.

### Tell us about the problem
I'm trying to run my project on iOS but I get this error and build fails on that

```
[18-11-09 10:23:44.118] (CLI) Unable to apply changes on device: 9991865793b34ae30366571031b6c251590c222a. Error is: ENOENT: no such file or directory, scandir '/Users/vipulk/Library/MobileDevice/Provisioning Profiles/'.
[18-11-09 10:23:44.149] Error detected during LiveSync on 9991865793b34ae30366571031b6c251590c222a for /Users/vipulk/Documents/YashOrnaments. Error: ENOENT: no such file or directory, scandir '/Users/vipulk/Library/MobileDevice/Provisioning Profiles/'
```

I've generated certificates and provisioning profiles via my developer account and I added the files to the device via the cogwheel icon on the devices list
![screen shot 2018-11-09 at 10 36 08 am](https://user-images.githubusercontent.com/11595460/48244389-89a70e00-e40b-11e8-9b3e-70695bb0a0ba.png)
Do I have to copy the provisioning profile to said location?

### Which platform(s) does the issue occur on?
_iOS <br/>
_macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop: ** 1.13.0-v2018.10.5.2
- **NativeScript CLI:** 4.2.4
- **CLI extension nativescript-cloud:** 1.14.2 
- **CLI extension nativescript-starter-kits:** 0.3.5

### Does this issue happen every time?
_Yes

### Send the client logs
[main_18-11-09_10-18-16.759.log](https://github.com/NativeScript/sidekick-feedback/files/2564672/main_18-11-09_10-18-16.759.log)

**Comment by ggarabedian** [comment]
@VeeK727, when you build locally for iOS, you need to use a certificate and mobile provision that are imported in the macOS Keychain as they are taken from there during build. Only cloud builds require you to provide code signing assets that are located on your file system.

In general, double-clicking the certificate should import it in the Keychain. Please, give this approach a try and let me know if you require further assistance.

**Comment by VeeK727** [comment]
Indeed that worked. Double clicked the .p12 file to add it to keychain. Thanks.

Although I had to do a couple more things but those errors were clearly communicated by sidekick. I had to add my team id to build.xcconfig file and I had to add my developer account to xcode. None of these steps were mentioned in the docs. Anyways thanks for your help.

**Comment by ggarabedian** [comment]
@VeeK727, I am glad to hear that you were able to build successfully. 

I also wanted to thank you for bringing to our attention that the documentation is missing important bits of information, we will make sure to update it accordingly.
