### ISSUE TITLE
Cant open Sidekick app on ubuntu

### ISSUE THREAD

**Issue by LeopoldPodmolik** [NativeScript/sidekick-feedback#3]
Hi,
after open **NS sidekick app** I got error - that _nodejs_ is old, but I have _node v7.10.0_ (`node -v`) 
OS: Ubuntu 16.04

![nativescript-sidekick-err](https://user-images.githubusercontent.com/4380789/28785971-224168e4-7618-11e7-84a5-d803b868a5d0.png)

My logs file:

- [main_17-07-31_17-42-52.926.txt](https://github.com/NativeScript/sidekick-feedback/files/1188087/main_17-07-31_17-42-52.926.txt)
- [cli_17-07-31_17-42-52.895.txt](https://github.com/NativeScript/sidekick-feedback/files/1188086/cli_17-07-31_17-42-52.895.txt)

Thank for any advice ...

**Comment by teobugslayer** [comment]
Hello Leopold,

thanks for the logs - the exception looks suspicious. @nadyaA, can you help?

**Comment by ventsislav-georgiev** [comment]
@LeopoldPodmolik The Sidekick uses the default shell's environment variables to determine which node to use, so the first node specified in $PATH wins. 

Could you run the following commands in a terminal to verify if there is an old node version somewhere in your shell profile:
* `$SHELL -ilc "node -v"`
* `$SHELL -ilc "which node"`
* `$SHELL -ilc "echo $PATH"`

If `$SHELL` environment variable is not specified, replace it with `bash`

**Comment by LeopoldPodmolik** [comment]
Every command show me node v7.10.0 ..

- `$SHELL -ilc "node -v"`
v7.10.0

- `$SHELL -ilc "which node"`
/home/leo/.nvm/versions/node/v7.10.0/bin/node

- `$SHELL -ilc "echo $PATH"`
/home/leo/.nvm/versions/node/v7.10.0/bin:....

**Comment by LeopoldPodmolik** [comment]
Now I try open app from cmd ... `/opt/NativeScriptSidekick$ ./NativeScriptSidekick ` and it is working ... before I click on Icon in menu ..

**Comment by ventsislav-georgiev** [comment]
@LeopoldPodmolik This may be related to the usage of nvm, we will investigate if that is the case. Until then, as you have found a workaround by running it from the Terminal, you can use a shorter command to launch the app - `nssidekick`.

**Comment by ventsislav-georgiev** [comment]
@LeopoldPodmolik Is it possible that the terminal shell you use is not set as a default for your user login?
Can you run the following command in order to set it as default:
* `chsh -s $SHELL`

You can verify the default shell being set by:
* `cat /etc/passwd | grep leo`

**You need to re-login in order for the new settings to be applied.**

**Comment by LeopoldPodmolik** [comment]
@ventsislav-georgiev any changes ...` :/bin/bash`

I have 2 terminals (**default** and **Terminator**) but both give me same result

**Comment by ventsislav-georgiev** [comment]
@LeopoldPodmolik we found the issue to be related to the shell being launched as a login shell and thus not reading the `.bashrc` file, where the nvm configuration is being added.

Could you check if editing the `.bash_profile` file by adding the following at the bottom of the file solves the issue:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by LeopoldPodmolik** [comment]
@ventsislav-georgiev Yes after add this lines it is work from "menu".

Thank you
