### ISSUE TITLE
Lastest Sidekick update

### ISSUE THREAD

**Issue by japasanto** [NativeScript/sidekick-feedback#301]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem

I have just updated sidekick( or he did because i turned my mac off, and when i returned the sidekick updates automatically) and since this, i have been experiencing a lot of problems that i didn´t have for example this morning...he simply get´s stuck on the "Refreshing application on device..." and does nothing else...a few minutes ago was asking me to do it manually( which i didn´t had to do before) but if after that i update something on my code, then he get´s stuck...i´m bulding locally and i´m using my iphone 6´s.

Could anyone please tell me what is going on?!?!

### Which platform(s) does the issue occur on?
IOS

### Provide the following version numbers that the issue occurs with:

Version: 1.14.1-v.2018.11.23.3 (latest)

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
Yes

**Comment by ggarabedian** [comment]
@japasanto, can you please [share the logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) that are tied to this error? If you are not certain which logs contain information about the issue, I would ask you to reproduce it, close Sidekick and share the latest logs.

Additionally, as you have mentioned that you build locally, can you tell me what version of Xcode you have installed on your machine?

**Comment by japasanto** [comment]
Hi garo,

 The problem was my Xcode, it needed to be updated as also some updates on my mac, after that everything is working normally again.

Thanks for responding

João santo

No dia 28/11/2018, às 09:08, Garo Garabedian <notifications@github.com<mailto:notifications@github.com>> escreveu:


@japasanto<https://github.com/japasanto>, can you please share the logs<https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs> that are tied to this error? If you are not certain which logs contain information about the issue, I would ask you to reproduce it, close Sidekick and share the latest logs.

Additionally, as you have mentioned that you build locally, can you tell me what version of Xcode you have installed on your machine?
