### ISSUE TITLE
Icon/image builder (like brosteins) integrated into sidekick for resource mangement assistance

### ISSUE THREAD

**Issue by Meyer-dev** [NativeScript/sidekick-feedback#302]
Icon Generator 🥇 would it be possible to extend the app icon generator functionality for other app icons and images so that those resources can be correctly generated for android and ios, and easily managed via Sidekick. Kinda like the functionality that you get of brosteins.com but with much more simplified naming and automatically placed into the correct files. This would be great and I'm sure just an extension of the current icon generator functionality.

**Comment by NickIliev** [comment]
To implement this feature, we need the NativeScript CLI to support the generation of custom icons. [This one is logged as a feature here](https://github.com/NativeScript/nativescript-cli/issues/4416) so closing this issue as related.

**Comment by Izrab** [comment]
I think this issue should be **reopened**, because I want to generate generic icons in GUI, like of generating app icon and splash screen.
