### ISSUE TITLE
Cloud build error on: throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by ryenchek** [NativeScript/sidekick-feedback#308]
## Please, provide the details below:
Cloud build error on: throw er; // Unhandled stream error in pipe.

### Did you verify whether this issue has already been reported here?
_Yes/No_

Yes
### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

In Sidekick doing an Android cloud build.  Last few lines in console log..
[18-12-06 13:22:20.891] Build step started.
[18-12-06 13:22:24.892] (CLI) internal/streams/legacy.js:59
[18-12-06 13:22:24.892] (CLI)       throw er; // Unhandled stream error in pipe.
[18-12-06 13:22:24.892] (CLI)       ^
[18-12-06 13:22:24.892] (CLI) Error: getaddrinfo ENOTFOUND livesync.ly livesync.ly:443
[18-12-06 13:22:24.892] (CLI)     at errnoException (dns.js:50:10)
[18-12-06 13:22:24.892] (CLI)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
[18-12-06 13:22:26.230] Build failed.

Also, I think I have been blacklisted or have had my acct disabled.  Right now I'm on a laptop outside of my corporate network.  In my corporate network Sidekick won't even run.  This maybe because of our SOPHOS endpoint software but right now we can't confirm it.  Was also wondering if nativescript.org admins blacklisted me.  The only reason I can think of why I got blacklisted is that maybe because I had been using Playground to Preview, then copy code into Visual Studio Code, then Sidekick to Build.  I've been doing this for a good 2-3 weeks for now because phone emulation and via usb isn't working, so I unable to debug quickly.  Yesterday Playground stopped working and so did Sidekick.  **Can anyone help?**  I was only doing this for testing and prototyping. Our agency has been using Telerik products for 5-6 years now and currently have DevCraft Ultimate subscription.
Thanks!!

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

Android/Windows.
### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

Version: 1.14.1-v.2018.11.23.3 (latest)
NativeScript CLI version: 5.0.1
CLI extension nativescript-cloud version: 1.14.4
CLI extension nativescript-starter-kits version: 0.3.5

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ... Build
3. Target Platform: Android
4. Build Type: Cloud
5. Config: Debug
6. Webpack Checked.
7. Click Build Button.

### Does this issue happen every time?
_Yes/No_

Yes.

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

[console-log-18-12-06-.txt](https://github.com/NativeScript/sidekick-feedback/files/2655009/console-log-18-12-06-.txt)
[main_18-12-06_13-21-22.044.log](https://github.com/NativeScript/sidekick-feedback/files/2655010/main_18-12-06_13-21-22.044.log)

**Comment by ggarabedian** [comment]
@ryenchek, thank you for reporting this issue. The error is related to a temporary problem with our cloud infrastructure. The good news is that we have taken the necessary steps to fix the issue. However, before you are able to build successfully in the cloud, you might be required to [Clear Your Local DNS Cache](https://documentation.cpanel.net/display/CKB/How+To+Clear+Your+DNS+Cache).

I hope this helps.

**Comment by ryenchek** [comment]
Thank you @ggarabedian..
Everything is up and running now.. 
Have a great day!
