### ISSUE TITLE
Cannot see the Debug button

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/sidekick-feedback#32]
I cannot see the debug button when running on linux. The screen high in not adjustable.

**Comment by teobugslayer** [comment]
Hey @leocrawf , what is your screen resolution?

**Comment by bundyo** [comment]
We would appreciate if you use the issue template when logging your issue and answer the questions to the best you can. Thus we can better decide how we can help you.

**Comment by leocrawf** [comment]
The screen resolution is 1366 x 768.

**Comment by bundyo** [comment]
Which version of NativeScript Sidekick are you using? Which Linux distro and version? Which window manager?

Similar issue was fixed in 0.2.1, but it won't affect your window directly if you used 0.2.0 - try resizing the window to make it smaller.

**Comment by leocrawf** [comment]
I copied the following from the sidekick about us:
Version: 0.2.0-v.2017.7.31.4
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

Also I am using Linux Mint 18.2 64 bit Cinnamond and I can only resize on horizontally not vertically.

**Comment by bundyo** [comment]
You're using the first version, there have been 2 updates since then - please download the latest version and install it to get the issue resolved. We're working to add update notifications on Linux when new version comes out.
