### ISSUE TITLE
Minimum Cloud Build iOS SDK version

### ISSUE THREAD

**Issue by kwilliamsnucleus** [NativeScript/sidekick-feedback#323]
## Please, provide the details below:
After cloud build and publish to Apple Store Connect, the following email is sent to me from Apple:

> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "APP_ID". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> SDK Version Issue - This app was built with the iOS 11.0 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.
> 
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Best regards,
> 
> The App Store Team

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Even though the binary uploads successfully and can be used in App Store Connect, starting in March, the cloud build process needs to update its iOS SDK to 12.1 or later.

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:

- NativeScript Sidekick Desktop: Version: 1.14.1-v.2018.11.23.3 (latest)
- NativeScript CLI: 5.0.1
- CLI extension nativescript-cloud: 1.15.0
- CLI extension nativescript-starter-kits: 0.3.5 

### Tell us how to recreate the issue in as much detail as possible
1. Publish a Nativscript Sidekick app using cloud build.
2. Log into the App Store Connect prompt that shows during the submission process of publishing.
3. Watch as the upload succeeds, but an email is sent to the account for which you logged in during step #2. That email is what is posted above.

### Does this issue happen every time?
Yes

**Comment by teobugslayer** [comment]
Hi @kwilliamsnucleus,

The team is aware of this issue and will update the SDK before the end date.

**Comment by dichlor** [comment]
Hi @teobugslayer 

Is there any new info regarding the issue? I am facing the same issue as @kwilliamsnucleus. 

Much appreciated!

**Comment by SoSimpull** [comment]
It should be noted that the app store is still accepting apps built in SDK 11.0.  My team was able to submit and get an app reviewed and proved this month ( FEB 2019 ) using SDK 11.0.  I just wanted to note this for anyone that is holding app submissions based on this issue.

**Comment by maik-becker** [comment]
Is there any news on this yet? I uploaded a cloud-built version today and the issue still exists. Since all the information we got from apple is "starting March", I guess the potential deadline could be already tomorrow. Its a bit unsettling, considering we are not hearing anything about this from the NativeScript devs.

**Comment by ggarabedian** [comment]
@dichlor, @SoSimpull and @maik-becker, we have already updated some of our machines to the latest version of Xcode. Please, have in mind that only builds with NativeScript CLI 5.2.0 and above versions will go to the machines with the latest version of Xcode. To ensure that you are using NativeScript CLI 5.2.0 or higher in your cloud build, you need to set the `tns-ios` version in the `package.json` file of your project to at least `5.2.0`.

**Comment by dichlor** [comment]
@ggarabedian Thank you very much! It works fine now.

**Comment by prabh08** [comment]
@ggarabedian I am still getting this warning from Apple and I am already using Nativescript 6 and here is package.json file that you can see :-
{
  "nativescript": {
    "id": "com.cdi.orderProcessing",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.1"
    }
  },
  "description": "CDI Order Processing",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "base-64": "^0.1.0",
    "nativescript-accordion": "^6.0.0-beta.2",
    "nativescript-angular": "^8.2.1",
    "nativescript-appversion": "^1.4.2",
    "nativescript-bottom-navigation": "^2.0.5",
    "nativescript-cardview": "^3.2.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-cloud": "^1.19.1",
    "nativescript-downloader": "^2.1.5",
    "nativescript-drawingpad": "^3.1.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-exit": "^1.0.1",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-globalevents": "^1.2.3",
    "nativescript-grid-view": "git+https://github.com/aaayushsingh/NativeScript-Grid-View.git",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-insomnia": "^1.2.3",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-loading-indicator": "^2.5.2",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toasty": "^2.0.1",
    "tns-core-modules": "6.0.1",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.2.0"
  },
  "gitHead": "1964ea9e8ca1a0518e0d6370781eedcf6c23db42",
  "readme": "NativeScript Application"
}

Please let me know the solution. Its very urgent for me.
