### ISSUE TITLE
[Feature Request] Ability to generate iOS builds from Mac on local network

### ISSUE THREAD

**Issue by saibbyweb** [NativeScript/sidekick-feedback#324]
For someone who primarily wants to develop on Windows, Sidekick cloud builds are simply magic.
Can you bring a magic companion app for MacOS which makes it act as our "LOCAL" cloud to build iOS apps on Windows. See I will give you a real life scenario:

I have a beast PC ( Windows - which works for almost everything except for building iOS app) and a Macbook Air (which isn't powerful enough for heavy multi-tasking)

If somehow Sidekick can zip app files, sends it to my local Macbook Air **over LAN** (instead of CLOUD) and brings back the compiled IPA, the development process will definitely speed up (for people with slow-average internet connection).

**Comment by saibbyweb** [comment]
Is there any documentation available for the "cloud" command?

**Comment by NickIliev** [comment]
@saibbyweb [in this thread](https://stackoverflow.com/a/55177147/4936697) you can find more information on how you could use the `cloud` command. Prior to the above make sure that you have installed the cloud extension as mentioned in[ this documentation section](https://docs.nativescript.org/tooling/docs-cli/cloud/cloud-setup)
