### ISSUE TITLE
ios build failing with error 65, both Cloud and local.

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#329]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I added resources to the app using the Assets view of Nativescript Sidekick. After that my build stopped working for ios. It doesn't seem related to that, though. It seems to have more to do with something like duplicate target tasks.

### Which platform(s) does the issue occur on?
iOS errors out

Android builds fine.

### Provide the following version numbers that the issue occurs with:

Version: 1.14.1-v.2018.11.23.3 (latest)
NativeScript CLI version: 5.1.0
CLI extension nativescript-cloud version: 1.15.0
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Open a simulator for an ios device
2. Click Run on Device

my dependencies:

"dependencies": {
    "@angular/animations": "7.2.0",
    "@angular/common": "7.2.0",
    "@angular/compiler": "7.2.0",
    "@angular/core": "7.2.0",
    "@angular/forms": "7.2.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "async-await": "^0.1.40",
    "lodash": "^4.17.10",
    "moment": "^2.22.0",
    "nativescript-angular": "^7.0.0",
    "nativescript-audio": "^5.0.0",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-orientation": "^2.2.0",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-listview": "^5.1.0",
    "nativescript-ui-sidedrawer": "^5.1.0",
    "nativescript-unit-test-runner": "^0.3.4",
    "nativescript-videoplayer": "^4.1.0",
    "nativescript-webview-interface": "^1.4.2",
    "nativescript-xmlobjects": "^1.1.4",
    "node-sass": "^4.9.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.3.3",
    "tns-core-modules": "^5.1.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.1",
    "@angular/cli": "^7.0.3",
    "@angular/compiler-cli": "~7.1.0",
    "@ngtools/webpack": "^6.2.7",
    "@types/lodash": "4.14.68",
    "@types/node": "~6.0.60",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "jasmine-core": "^3.1.0",
    "karma": "^3.1.1",
    "karma-jasmine": "^1.1.1",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "^0.7.9",
    "nativescript-dev-webpack": "^0.19.0",
    "tns-platform-declarations": "^3.4.1",
    "ts-node": "~3.3.0",
    "tslint": "^5.8.0",
    "typescript": "~3.1.1"
  },

if I remove the nativescript-pro-ui plugins, ios compiles, but I need them.

### Does this issue happen every time?
Yes

### Send the client logs

[main_19-01-15_10-08-37.904.log](https://github.com/NativeScript/sidekick-feedback/files/2760225/main_19-01-15_10-08-37.904.log)
[console_19-01-15_10-08-27.888.log](https://github.com/NativeScript/sidekick-feedback/files/2760226/console_19-01-15_10-08-27.888.log)

**Comment by bradrice** [comment]
I think I finally solved this by removing and reinstalling the nativescript-ui-sidedrawer and nativescript-ui-listivew

**Comment by ggarabedian** [comment]
@bradrice, apologies for the late response.

I am happy to hear that you were able to resolve the issue, because I wasn't able to reproduce it when testing a sample app with the provided `package.json` file. The error indicates that there were duplicate tasks - most likely, during the update of the sidedrawer and listview plugins, some artifacts from the previous versions remained in the `node_modules` or `platforms/<platform>` folder and caused the error.
