### ISSUE TITLE
Sidekick 2018 Macbook Air CPU and fan

### ISSUE THREAD

**Issue by StuDownie** [NativeScript/sidekick-feedback#333]
Running Sidekick makes the fan on my 2018 Macbook Air run loud. CPU usage is through the roof when running on emulator. 

Sounds like issue #61  but i've added the following line to my .bash_profile file and it's made no difference:

export TSC_NONPOLLING_WATCHER="1"

MacBook Air (Retina, 13-inch, 2018)
1.6 GHz Intel Core i5
Mac OS 10.14.2
Node.js v10
Sidekick Version: 1.15.0-v.2019.1.18.17 

1. Start Sidekick
2. Click into my Vue Firebase template starter project (fan gradually ramps up)
3. Open iOS emulator (iPhone X iOS 12)
4. Click "run on device" (local build). Everything works, but with high CPU usage and fan running loud
5. Close Sidekick and fan gradually calms down

[main_19-01-24_23-16-43.543.log](https://github.com/NativeScript/sidekick-feedback/files/2794023/main_19-01-24_23-16-43.543.log)
[console_19-01-24_23-16-41.821.log](https://github.com/NativeScript/sidekick-feedback/files/2794024/console_19-01-24_23-16-41.821.log)

**Comment by ggarabedian** [comment]
@StuDownie, apologies for the late response.

We are currently working on resolving a similar issue that results in a high CPU usage. Can you please install the `next` version of the NativeScript CLI and see if that makes any difference? You can install the `next` version by running the `npm install nativescript@next -g` command.

**Comment by StuDownie** [comment]
That's definitely better, thanks.

Fan is still running though (only when using Sidekick, doesn't when using "tns run ios")

Keep up the good work, love the app.
