### ISSUE TITLE
Build failed - 404 error on har-validator

### ISSUE THREAD

**Issue by VeeK727** [NativeScript/sidekick-feedback#336]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem
I've installed NativeScript on a fresh computer and `tns doctor` reports no issues. I connected my iPhone and started build on an existing project. I got this error

`npm ERR! 404 Not Found: har-validator@https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz`

Apparently there's some issue with this plugin which is being [discussed here](https://github.com/ahmadnassri/node-har-validator/issues/113). The solution is to skip this version and download 5.1.3 instead. But how do I do it with NativeScript? I haven't been able to find the file which determines the version of `har-validator` to use.

### Which platform(s) does the issue occur on?
_Both <br/>
_macOS 10.14 Mojave

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.15.0
- **NativeScript CLI:** 5.1.1
- **CLI extension nativescript-cloud:** 1.15.2
- **CLI extension nativescript-starter-kits:** 0.3.5

### Does this issue happen every time?
_Yes

### Send the client logs
[Logs](https://gist.github.com/VeeK727/c229de735233ed5f53ea4b8f0f35ed17)

**Comment by ggarabedian** [comment]
@VeeK727, the reported issue seems to be specific to your app and implementation. Can you please share the content of your `package.json`, so we can attempt to reproduce the error on our side and investigate it further.
