### ISSUE TITLE
Device console tab is empty

### ISSUE THREAD

**Issue by VeeK727** [NativeScript/sidekick-feedback#337]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem
I installed Sidekick and ran my app which worked fine and I was getting console outputs in the device console tab. But I left my laptop for a while and when I came back the console had stopped working. The new outputs are no longer appearing. I tried restarting Sidekick and then restarting the computer but no effect.

I then reinstalled Sidekick and sure enough, the console started appearing again. Once again, the computer logged off and when I logged in again to resume working the console outputs stopped again.

Edit: Restarting the computer makes console logs to appear again. But after logoff and log back in, the console tab is empty again and new messages don't appear.

### Which platform(s) does the issue occur on?
_Both<br/>
_macOS 10.14 Mojave

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.15.0 
- **NativeScript CLI:** 5.1.1
- **CLI extension nativescript-cloud:** 1.15.2
- **CLI extension nativescript-starter-kits:** 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start Sidekick
2. Verify if console output is appearing
3. Logoff your computer (The apps are not closed)
4. Resume working and verify if console output still works)

### Does this issue happen every time?
_Yes

### Send the client logs
[Log](https://gist.github.com/VeeK727/f1a2fcd66bf2b77a171ec63c41f2004f)

**Comment by ggarabedian** [comment]
Hello @VeeK727,

I apologize for the delayed response. 

It seems that the OS is terminating the connection to the device when you log off, which is not something we can control. However, you shouldn't need to restart the machine or reinstall Sidekick to detect the device. You should be able to reinitialize the connection by detaching and then attaching the device from the USB cable. 

Let me know if the suggested above helps.

**Comment by VeeK727** [comment]
Yes that works. Also quitting (not closing with red icon) and starting Sidekick works too. This problem does not occur on Windows, is there anything that can be done in Sidekick's code that could resolve the issue?

**Comment by NickIliev** [comment]
Closing the issue as the main case has a solution. 

@VeeK727 we will post if there is an additional fix that can handle this one, Still, at this very moment, there are limited options to control the device detection so if you experience this one proceed with the solution provided above.
