### ISSUE TITLE
Bundle Node with Sidekick

### ISSUE THREAD

**Issue by MrCroft** [NativeScript/sidekick-feedback#340]
### Tell us about the problem
While using WSL (Windows Subsystem Linux), having Node installed on both the host OS (Windows) and on WSL can be very tricky. It usually results in npm not working properly.

Ideally, Sidekick should have the appropriate Node.js version bundled in and not require us to have Node.js installed on the host OS.
As a nice side-effect, this would also make Sidekick independent of the host OS installed Node version, if any.

### Which platform(s) does the issue occur on?
_Windows_

**Comment by teobugslayer** [comment]
We do not have immediate plans for implementing this feature. Part of the story behind NativeScript Sidekick is to help developers to configure their machines for the NativeScript CLI and the latter requires global Node.js installation.
