### ISSUE TITLE
Device Console scrolling problem

### ISSUE THREAD

**Issue by kefahB** [NativeScript/sidekick-feedback#342]
Impossible to scroll between logs in the Device logs when run on real device .. when I trying to scroll up or down the scrolling is very capricious an can't stop it !! 

For me this happen on IOS because I use Sidekick for IOS .. I do not use it for android

**Comment by ggarabedian** [comment]
@kefahB, apologies for the late response. 

Are you talking about the "scrolling to the bottom" when a new line is added to the output? I notified our engineering team and they will work on correcting the scrolling behavior. 

This is the only issue which we were able to identify when testing the scrolling in the device console pane, so please let me know if you are experiencing a different problem.
