### ISSUE TITLE
Sidekick generated angular.json file missing default angular cli actions

### ISSUE THREAD

**Issue by kingjordan** [NativeScript/sidekick-feedback#349]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When I use Sidekick to create a new app, the angular.json file does not contain the build, serve, test, lint actions for the angular cli.  Thus the following error is displayed:
> _angular cli "No projects support the build target"_

If i use the nativescript cli and run the following:

> ng new -c=@nativescript/schematics my-project --shared --style=scss

then the angular.json file contains the proper details for the build, serve, test lint ... actions

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:**  Version: 1.16.1-v.2019.2.27.1 (latest)
- **NativeScript CLI:** 3.1.6
- **CLI extension nativescript-starter-kits:** All Starter Templates

### Tell us how to recreate the issue in as much detail as possible
1. Open sidekick
2. Choose Create new project and choose any of the templates
3. After project is created, open the angular.json file and you will see the missing actions for the default project

TO see the difference run the tsc command above and compare the generated angular.json files.

### Does this issue happen every time?
Yes

**Comment by kingjordan** [comment]
I am not sure this is an issue after more research.  Is the native script sidekick app designed to create projects that will code share between web/angular/native?

**Comment by tsvetie** [comment]
Hey @kingjordan,
You are correct in your assumption that NativeScript Sidekick does not have this feature. NativeScript Sidekick was designed to work on top of NativeScript CLI - it provides UI for most of NS CLI functionality and some additional features that make working on a NativeScript app easier.

As the command you referred to is actually an Angular CLI command, not a NS CLI command, NS Sidekick does not offer UI to create this type of project. However, once created with the Anlugar CLI, you can use NS Sidekick to work with the shared project - preview, build, LiveSync, publish, etc. the mobile part of the app. NS Sidekick does not offer functionality to help you develop the web part of the app.

**Comment by kingjordan** [comment]
thanks, I see that now, this can be removed or closed.
