### ISSUE TITLE
Nativescript Sidekick Publish to App Store

### ISSUE THREAD

**Issue by basyr** [NativeScript/sidekick-feedback#356]
Hi,

I'm running Sidekick on my Windows 10 machine (64b).
I'm trying to publish my app to the Apple AppStore. Certificate, provision is all ok. When I publish, build is made, I can log in when asked and fill in the verication code.
But then I get error 'Spawn Failed'. Googled this error, but didn't find anything.

Erros in the log are:
[19-03-08 10:52:20.711] (CLI) Build machine host name: administrators-Mac-16.local
[19-03-08 10:52:58.349] Spawn failed.
, Error: Spawn failed. at CloudPublishService.getiOSError (C:\Users\bartad\AppData\Roaming.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:79:21)
at CloudPublishService. (C:\Users\bartad\AppData\Roaming.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:96:29)
at Generator.next ()
at fulfilled (C:\Users\bartad\AppData\Roaming.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:4:58)
at 
Does anyone have an idea what's wrong here ?
Thanks Bart

**Comment by tsvetie** [comment]
Hey Bart,

Can you send me the log files that Sidekick created during a session, in which you reproduced the error? You can open the folder with the logs files by selecting _Help -> Show logs_ from the window menu. The logs files contain a bit more information about the problem compared to the contents in the Output pane.

**Comment by basyr** [comment]
Hey,
Thanks for following this up, but this morning I eventually succeeded in uploading it to app connect.
Reason was my 'app id' and 'bundle id'. They were not the same. But the error 'spawn failed' did not give me the info on that…  So it was hard to find.
