### ISSUE TITLE
Unable to download latest update through the electron app (0.2.2 => 0.2.3)

### ISSUE THREAD

**Issue by shiv19** [NativeScript/sidekick-feedback#36]
I am using Nativescript Sidekick version 0.2.2

Over here in the documentation
https://dy0uugugdpwse.cloudfront.net/ab/fusion/docs/latest/documentation.html

It says that the latest version is 0.2.3

When I check for updates in Sidekick, it says 0.2.2 is the latest version.

**Comment by tsvetie** [comment]
@shiv19 this is a bug in the documentation. We are currently preparing 0.2.3, it is not released yet. The latest version is 0.2.2.

**Comment by shiv19** [comment]
@tsvetie
Thanks for clearing the confusion :)
