### ISSUE TITLE
Publishing to ios store - several issues

### ISSUE THREAD

**Issue by japasanto** [NativeScript/sidekick-feedback#360]
## Please, provide the details below:

So as everyone knows, publish to the appstore is a nightmare, at this precise moment i´m trying to publish my app but i keep getting erros regardless of using nativescript sidekick or using aplication loader, also i have done EVERY step that is said here: https://www.youtube.com/watch?v=5gKuR2UCOnM

### Did you verify whether this issue has already been reported here?
YES

### Tell us about the problem
**_When using sidekick:_**
1 - i go to the top, select run->publish
2 - i select ios and in the cogwheel put my certificate (distribution) and provisioning profile (distribution).
3 - it creates the ipa file and asks for my apple developer credentials.
4 - it then shows an input where i´m suppose to insert my password(of my credentials):
Password (application-specific for myUserName)
5 - **It get´s completly stuck here!!!** no matter what password i put it simply does not work.

I also notest something else...everytime i need to start sidekick the below happens:
```
[19-03-15 17:21:21.547] NativeScript Sidekick version: 1.16.1-v.2019.2.27.1
[19-03-15 17:21:21.909] Checking for updates...
[19-03-15 17:21:22.111] Dependencies versions: NodeJS: 8.12.0, npm: 6.4.1, NativeScript CLI: 5.1.1.
[19-03-15 17:21:22.264] Downloading updates...
[19-03-15 17:21:22.298] Could not create temporary directory: Permissão negada, Error: Could not create temporary directory: Permissão negada
[19-03-15 17:21:22.311] An error occurred while checking for updates.
```

**_When using Aplication Loader:_**
`ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle myReverseDomain [Payload/myApp.app] is invalid. [Missing code-signing certificate].`
I have tried a lot of things, i have checked and re-checked to see if i was creating the files incorrectly, but i think i´m not!.

### Which platform(s) does the issue occur on?
IOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** - Version: 1.16.1-v.2019.2.27.1

### Tell us how to recreate the issue in as much detail as possible
I really don´t know how you could reproduce the issue, try to upload a .ipa file and see if the same happens.

### Does this issue happen every time?
YES ... and i also tried using the solution here: https://github.com/NativeScript/sidekick-feedback/issues/321 but i problem continues

Could anyone please help with this? i´m losing so much time and i´m stuck not knwing what to do.
Thanks for your time
   Regards

**Comment by tsvetie** [comment]
Hey @japasanto,

Are you still stuck on this problem? Since you mentioned that you had the same problem using both Sidekick and Application Loader - it might have been some temporary issue. Ca you still reproduce the problem?

On a side note, there is one thing that can be slightly misleading in Sidekick UI (we will address it in a future version) - if you are using local iOS build, then the provision and certificate are picked by xCode. It does not matter with provision and certificate you set in Sidekick. These are applicable only for cloud builds. With this in mind - did you use cloud or local build? In case you are using local builds, then you should add the certificate to your keychain and make sure that xCode has downloaded the correct provisioning profile (Go to XCode > Preferences > Accounts and select the Apple Id and click Download Manual Profiles).

**Comment by japasanto** [comment]
Hi Tsvetelina Ivanova

   First of all, i want to thank you for spending time answering my issue. Next what i did was, i used xcode for everything, i have opened my xcworkspace on my xcode, and created the archive, the xcode manages everything about the profiles(all the boring stuff!!) and that´s it, the app is on the air!.


Regards
 João

________________________________
De: Tsvetelina Ivanova <notifications@github.com>
Enviado: quinta-feira, 4 de abril de 2019 15:18
Para: NativeScript/sidekick-feedback
Cc: japasanto; Mention
Assunto: Re: [NativeScript/sidekick-feedback] Publishing to ios store - several issues (#360)


Hey @japasanto<https://github.com/japasanto>,

Are you still stuck on this problem? Since you mentioned that you had the same problem using both Sidekick and Application Loader - it might have been some temporary issue. Ca you still reproduce the problem?

On a side note, there is one thing that can be slightly misleading in Sidekick UI (we will address it in a future version) - if you are using local iOS build, then the provision and certificate are picked by xCode. It does not matter with provision and certificate you set in Sidekick. These are applicable only for cloud builds. With this in mind - did you use cloud or local build? In case you are using local builds, then you should add the certificate to your keychain and make sure that xCode has downloaded the correct provisioning profile (Go to XCode > Preferences > Accounts and select the Apple Id and click Download Manual Profiles).
