### ISSUE TITLE
MacOS with iOS simulator - Run causes Shutdown 

### ISSUE THREAD

**Issue by nlmunro** [NativeScript/sidekick-feedback#361]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
After successfully transferring the files, the restart application step causes the iPhone simulator to shutdown, so it closes and the following step gets an error code 164 "Unable to lookup in current state: Shutdown". I then need to go to the Simulator and select Hardware > Restart and the app is there but I no debugging or logging is done as there is no connection to Sidekick. 

### Which platform(s) does the issue occur on?
macOS (High Sierra 10.13.6) when building for iOS XCode Simulator (10.1)
(works fine on Windows when connected to a real iPhone 5)

### Provide the following version numbers that the issue occurs with:
Version: 1.16.1-v.2019.2.27.1
NativeScript CLI version: 5.2.3
CLI extension nativescript-cloud version: 1.17.1
CLI extension nativescript-starter-kits version: 0.3.5 

### Tell us how to recreate the issue in as much detail as possible

1. Select Cloud build (or local Xcode if I can be bothered continually having sign-in...)   
2. Select iPhone X in "Virtual Device Launcher" and wait for it to start up
3. Click "Run on Device"

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/nlmunro/aa09e403cb088000158f09062b792a64

**Comment by nlmunro** [comment]
I've also noticed that I end up with increasing numbers of instances of simctl, CoreSimulatorBridge and other "sim" processes. These remain even if I quit the Simulator or logout, but this issue happens right from the start (after a reboot).

**Comment by nlmunro** [comment]
I also get this when I try and build locally, even though XCode shows me a logged in...
Error Domain=DVTPortalServiceErrorDomain Code=1100 "Your session has expired.  Please log in."

**Comment by tsonevn** [comment]
Hi @nlmunro,
The issue seems to be related to a local Xcode problem. Check out [this thread](https://forums.developer.apple.com/thread/102264), where a similar case has been discussed.

**Comment by nlmunro** [comment]
I was using a managed server on macincloud.com and I think the problem is basically that it does not allow admin access. I have now upgraded to a dedicated server and following the advanced setps with admin access it works. The only minor issues were using xcode-select and it did not recognise "pip" so I had to manually install that.
