### ISSUE TITLE
Can not create a new Vue app win 7

### ISSUE THREAD

**Issue by ehabdevel** [NativeScript/sidekick-feedback#362]
## Please, provide the details below:
Can not create a new vue app win 7 64

### Did you verify whether this issue has already been reported here?
_Yes/No_
Yes

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

Vue App

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

Windows 7 64

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

https://gist.github.com/ehabdevel/fc7dc2c5a96b1a6735e1c5214589ac91

**Comment by tsonevn** [comment]
HI @ehabdevel,
It seems that there is an issue with the installation of `node-sass@4.9.4` while using `node 11.*.*`. Check out the issue [here](https://github.com/sass/node-sass/issues/2525). Try to install the latest [LTS Node](https://nodejs.org/en/) version `10.15.*` and check if you will still have a problem with the creation of a new NS Vue project.
