### ISSUE TITLE
Android Build failed

### ISSUE THREAD

**Issue by kapiltiwari61** [NativeScript/sidekick-feedback#364]
Hi Guys,

Android build is getting failed. Please check the logs.

```
Could not resolve all dependencies for configuration ':app:_F0F1F2F3F4F5F6F7F8F9DebugApkCopy'.

Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
Required by:
project :app
> Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
> Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'.
> Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'. Received status code 502 from server: Bad Gateway
> Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
> Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'.
> Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'. Received status code 502 from server: Bad Gateway
Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
Required by:
project :app
> Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
> Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
> Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
> Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
> Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
> Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
```

**Comment by tsonevn** [comment]
Hi @kapiltiwari61,
Can you send us your project's package.json file as well as NativeScript Sidekick log files? More info, how to access them, can be found [here](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs).

**Comment by NickIliev** [comment]
@kapiltiwari61 update the project to use the latest versions (CLI, runtime, modules, plugins) - detailed explanation [here](https://github.com/NativeScript/sidekick-feedback/issues/367#issuecomment-483963734)

**Comment by prabh08** [comment]
@NickIliev I am also facing the same issue.
Here you see my package.json file. Please let me know the solution. I am trying to resolve this from a long time.

{
  "nativescript": {
    "id": "com.cdi.orderProcessing",
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.1"
    }
  },
  "description": "CDI Order Processing",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "base-64": "^0.1.0",
    "nativescript-accordion": "^5.0.4",
    "nativescript-angular": "^8.2.1",
    "nativescript-appversion": "^1.4.2",
    "nativescript-bottom-navigation": "^2.0.5",
    "nativescript-cardview": "^3.2.0",
    "nativescript-carousel": "^6.1.1",
    "nativescript-cloud": "^1.19.1",
    "nativescript-dna-netservices": "^1.1.0",
    "nativescript-downloader": "^2.1.5",
    "nativescript-drawingpad": "^3.1.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-exit": "^1.0.1",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-globalevents": "^1.2.3",
    "nativescript-grid-view": "git+https://github.com/aaayushsingh/NativeScript-Grid-View.git",
    "nativescript-image-cache": "^1.1.6",
    "nativescript-insomnia": "^1.2.3",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-loading-indicator": "^2.5.2",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-masked-text-field": "^4.0.3",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toasty": "^2.0.1",
    "tns-core-modules": "6.0.1",
    "url-parse": "^1.4.7",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.2.0"
  },
  "gitHead": "1964ea9e8ca1a0518e0d6370781eedcf6c23db42",
  "readme": "NativeScript Application"
}

And here is the error that I am getting.

Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
     Required by:
         project :app
      > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
         > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'.
            > Could not HEAD 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
