### ISSUE TITLE
iOS publishing issue

### ISSUE THREAD

**Issue by kapiltiwari61** [NativeScript/sidekick-feedback#367]
### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

**Comment by kapiltiwari61** [comment]
Hi Guys, I tried to upload ios build but it failed even i am using correct app specific password and updated sdk.
Please find logs.

`[19-04-15` 20:01:26.585] Spawn failed. [Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938) [Transporter Error Output]: ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 11.4 SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later. Further, starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.", Error: Spawn failed. [Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938) [Transporter Error Output]: ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS 11.4 SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later. Further, starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later." at CloudPublishService.getiOSError (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:79:21) at CloudPublishService.<anonymous> (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:96:29) at Generator.next (<anonymous>) at fulfilled (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:4:58) at <anonymous>`

**Comment by NickIliev** [comment]
@kapiltiwari61 can you post the content of your `package.json`

**Comment by kapiltiwari61** [comment]
@NickIliev, please have a look to package.json
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.example.abc",
    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "3.4.3"
    }
  },
  "dependencies": {
    "ajax-request": "^1.2.3",
    "base-64": "^0.1.0",
    "lodash": "^4.17.4",
    "nativescript-accordion": "^5.0.3",
    "nativescript-appversion": "^1.4.1",
    "nativescript-bottom-navigation": "^1.1.2",
    "nativescript-cardview": "^2.0.4",
    "nativescript-carousel": "^3.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-downloader": "^1.0.3",
    "nativescript-drawingpad": "^2.1.1",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-exit": "^1.0.1",
    "nativescript-geolocation": "^4.2.3",
    "nativescript-globalevents": "^1.2.1",
    "nativescript-grid-view": "^3.2.2",
    "nativescript-image-cache": "^1.1.5",
    "nativescript-insomnia": "^1.2.2",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-sqlite": "https://github.com/divyanshujain12/sqlite-nativescript.git",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-listview": "^3.5.1",
    "tns-core-modules": "^3.1.0",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "^0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}
`

**Comment by NickIliev** [comment]
@kapiltiwari61 the issue is that you are building your project with an old version of the iOS runtime (`tns-ios`). The current latest version of iOS runtime (`tns-ios`) is 5.3.x and with the latest version, we are explicitly building against the latest XCode requirements.

The version used in your project (4.0.1) was released some time ago and thus it is building against an older version of XCode (which is causing the issue and the error message).

Consider updating your porject to use the latest runtimes, modules and the related plugins.[ Here you can find instructions on how to update](https://docs.nativescript.org/releases/upgrade-instructions) the versions of the CLI, runtimes, modules and related plugins. Apart from that, I guess that you will have to migrate the in-app codebase as well.

**Comment by kapiltiwari61** [comment]
HI @NickIliev, I have updated the iOS runtime but now facing with new issue.
`[19-04-17 17:42:50.093] (CLI) Downloading dependencies
[19-04-17 17:42:50.093] (CLI) Installing AFNetworking (3.2.1)
[19-04-17 17:42:50.093] (CLI) Installing BEMCheckBox (1.4.1)
[19-04-17 17:42:50.093] (CLI) Installing DKCarouselView (2.4.13)
[19-04-17 17:42:50.093] (CLI) Installing IQKeyboardManager (5.0.8)
[19-04-17 17:42:50.093] (CLI) Installing MBProgressHUD (1.1.0)
[19-04-17 17:42:50.093] (CLI) Installing MiniTabBar (1.0.2)
[19-04-17 17:42:50.093] (CLI) Installing SDWebImage (4.0.0)
[19-04-17 17:42:50.093] (CLI) Installing SignatureView (1.1.0)
[19-04-17 17:42:50.093] (CLI) Installing Toaster (2.0.4)
[19-04-17 17:42:50.093] (CLI) [!] Unable to determine Swift version for the following pods:
[19-04-17 17:42:50.093] (CLI) - `MiniTabBar` does not specify a Swift version and none of the targets (`cdinativescript`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
[19-04-17 17:42:50.093] (CLI) - `Toaster` does not specify a Swift version and none of the targets (`cdinativescript`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
[19-04-17 17:42:51.578] (CLI) 'pod install' command failed.
[19-04-17 17:42:51.578] (CLI) 'pod install' command failed.
[19-04-17 17:42:58.820] Build step completed.
[19-04-17 17:42:58.846] Build failed. Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:41.896] [WARN]  'pod install' command failed.
[00:00:43.206] [ERROR] 'pod install' command failed.
'Build failed with error code 2'.
`

**Comment by kapiltiwari61** [comment]
Hi @NickIliev, 
Can you elaborate the statement " I guess that you will have to migrate the in-app codebase as well".
Need clarification on this.

Thanks.

**Comment by NickIliev** [comment]
> Can you elaborate the statement " I guess that you will have to migrate the in-app codebase as well".
> Need clarification on this.

There are a number of changes in the way a framework, plugin and library works when the authors are bumping the **major** version (e.g. from 3.x.x to 5.x.x there are two major versions). Those are called breaking changes for a good reason - so when you are migrating to a newer major version (of a dependency, runtime, library, plugin, etc.) you should also expect the need to check the related CHANGELOG and apply the needed changes.

For example, here is [the CHANGELOG of `tns-core-modules`](https://github.com/NativeScript/NativeScript/blob/master/CHANGELOG.md)

Here is [the CHANGELOG for `nativescript-ui-listview`](https://github.com/telerik/nativescript-ui-feedback/blob/master/releases/listview.md)

If some of the dependencies are not having a CHANGELOG then I would suggest going through the official documentation and observing for changes in the code you are using.
