### ISSUE TITLE
pod install failed 

### ISSUE THREAD

**Issue by kapiltiwari61** [NativeScript/sidekick-feedback#368]
### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

**Comment by kapiltiwari61** [comment]
Hi guys,

HI @NickIliev, I have updated the iOS runtime but now facing with new issue.

`[19-04-17 17:42:50.093] (CLI) Downloading dependencies [19-04-17 17:42:50.093] (CLI) Installing AFNetworking (3.2.1) [19-04-17 17:42:50.093] (CLI) Installing BEMCheckBox (1.4.1) [19-04-17 17:42:50.093] (CLI) Installing DKCarouselView (2.4.13) [19-04-17 17:42:50.093] (CLI) Installing IQKeyboardManager (5.0.8) [19-04-17 17:42:50.093] (CLI) Installing MBProgressHUD (1.1.0) [19-04-17 17:42:50.093] (CLI) Installing MiniTabBar (1.0.2) [19-04-17 17:42:50.093] (CLI) Installing SDWebImage (4.0.0) [19-04-17 17:42:50.093] (CLI) Installing SignatureView (1.1.0) [19-04-17 17:42:50.093] (CLI) Installing Toaster (2.0.4) [19-04-17 17:42:50.093] (CLI) [!] Unable to determine Swift version for the following pods: [19-04-17 17:42:50.093] (CLI) - MiniTabBar does not specify a Swift version and none of the targets (cdinativescript) integrating it have the SWIFT_VERSIONattribute set. Please contact the author or set theSWIFT_VERSIONattribute in at least one of the targets that integrate this pod. [19-04-17 17:42:50.093] (CLI) -Toaster does not specify a Swift version and none of the targets (cdinativescript) integrating it have the SWIFT_VERSIONattribute set. Please contact the author or set theSWIFT_VERSIONattribute in at least one of the targets that integrate this pod. [19-04-17 17:42:51.578] (CLI) 'pod install' command failed. [19-04-17 17:42:51.578] (CLI) 'pod install' command failed. [19-04-17 17:42:58.820] Build step completed. [19-04-17 17:42:58.846] Build failed. Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:41.896] [WARN] 'pod install' command failed. [00:00:43.206] [ERROR] 'pod install' command failed. 'Build failed with error code 2'.`

**Comment by NickIliev** [comment]
@kapiltiwari61 the error logs are guiding you to the reason for your issue - you are using plugins, which are using CocoaPod developed with older Swift version.

I guess one of the plugins is `nativescript-toast` - if that is the case the best solution is to replace the plugin with this one - **[nativescript-toasty](https://github.com/triniwiz/nativescript-toasty)** which is basically the same plugin but with the updated pod.

I am not familiar with the other plugin, but you could try to apply one of the solutions suggested [here](https://stackoverflow.com/questions/53009550/swift-version-nativescript). If you are still experiencing issue, the try to locate the repository of the plugin and open/search a related issue.


Closing the issue as unrelated to NativeScript Sidekick.

**Comment by Kev12997** [comment]
Hello, Rajinder! My name is Kevin Rodriguez, I am one of the interns at CDI technologies working on the nativescript app. I had a similar error while trying to cloud build for IOS. I solved all my errors by updating my tns-core-modules to a more recent version. I also updated tns-android. Just delete platforms, hooks and node_modules and rebuild after you have updated the package JSON. Here is my package JSON: 

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "YOUR-APP-ID",
    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "5.2.1"
    }
  },
  "dependencies": {
    "ajax-request": "^1.2.3",
    "base-64": "^0.1.0",
    "lodash": "^4.17.11",
    "nativescript-accordion": "^5.0.3",
    "nativescript-appversion": "^1.4.1",
    "nativescript-barcodescanner": "^3.1.3",
    "nativescript-bottom-navigation": "^1.1.2",
    "nativescript-cardview": "^2.0.4",
    "nativescript-carousel": "^3.1.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-downloader": "^1.0.3",
    "nativescript-drawingpad": "^3.0.2",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-exit": "^1.0.1",
    "nativescript-geolocation": "^4.2.3",
    "nativescript-globalevents": "^1.2.1",
    "nativescript-grid-view": "^3.2.2",
    "nativescript-image-cache": "^1.1.5",
    "nativescript-insomnia": "^1.2.2",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-sqlite": "https://github.com/divyanshujain12/sqlite-nativescript.git",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-listview": "^3.5.1",
    "tns-core-modules": "^4.2.1",
    "utf8": "^3.0.0"
  },
  "devDependencies": {
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "^2.1.1",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^0.9.2",
    "nativescript-worker-loader": "^0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by nmandyam** [comment]
This doesn't really SOLVE the problem, does it? I have a similar issue with SkyFloatingLabelTextField, there seems to be no upgrade to include the SWIFT_VERSION and I don't want to dump the pod. On my Mac, I can do all that's suggested in the other articles (including a simple _export SWIFT_VERSION=3_ before the _tns_ command) and that solves the issue. Is there an equivalent in the Sidekick environment?

**Comment by nmandyam** [comment]
[This](https://github.com/NativeScript/nativescript-cli/issues/4553#issuecomment-485717747) mechanism works, so that's great!

**Comment by zzzxtreme** [comment]
removing toast solved my problem. yikes
