### ISSUE TITLE
JDK & Sdk missing error

### ISSUE THREAD

**Issue by chamodKanishka** [NativeScript/sidekick-feedback#369]
I have already these two & I also variable paths created. I've run react native apps correctly. But this erroe shows me on shared project with angular. Also shows this error in non shared projects

**Comment by NickIliev** [comment]
@chamodKanishka can you share the output from the following command
```
tns doctor
```

**Comment by chamodKanishka** [comment]
Thank you for replying to this. I fixed my problems. ABDROID_HOME & JAVA_HOME variables I earlier added in user variables. It isn't work for me. Then I added these two to system variables & restart pc & every things works fine
