### ISSUE TITLE
Cloud build with tns version

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/sidekick-feedback#370]
I have had to downgrade the TNS version of an app to 5.1.1 to stop a bug in the nativescript-videorecorder plugin. I have to do a cloud build to get my Enterprise apps to run on non provisioned (not our test) devices (iOS) otherwise the app will not install if I build locally. The local build install fails because of the lack of provisioning for the device, but never had a problem with building in the cloud. Not sure what is happening that is different. 

My question is what version of TNS is used to compile cloud builds because my app is failing to run again because of a bug due to the tns version, so assuming the Cloud build always use the latest. How can I build from the TNS CLI using the cloud and my installed version of TNS. I installed TNS 5.1.1 as a dev dependency as I did not want to affect my whole install base for other apps.

**Comment by NickIliev** [comment]
@mrwrighty installing the runtime (e.g. `tns-ios`) as a devDependency is not supported so you should remove it and add it through the CLI. 


Can you let us know which is the version used prior to downgrading? I would suggest trying to build with the latest CLI & runtime (at this very moment those are versions 5.4.x which was released 2 days ago)

```
npm uninstall -g nativescript
npm install -g nativescript@latest
cd <path-to-you-project>

tns platform add ios
```

**Comment by NickIliev** [comment]
Closing as resolved in[ the duplicate issue](https://github.com/NativeScript/sidekick-feedback/issues/371)
