### ISSUE TITLE
Cloud Build installs on iOS, local build fails with provisioning error

### ISSUE THREAD

**Issue by mrwrighty** [NativeScript/sidekick-feedback#371]
Using Nativescript Sidekick Version: 1.16.2-v.2019.3.13.12 (latest) when doing a build from the build tab.

If I build using the Cloud, either debug or release it doesn't matter, my app installs and runs.
If I build using Local (Changed using the selector on the build tab), my app will not run with the following error.

 <Notice>: 0x191c1000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 147: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.EqQE6S/extracted/Payload/myapp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)

Why does the cloud build work, and the local build does not?

PS I've changed the name of my app in the error above as I do not want it public.

**Comment by mrwrighty** [comment]
Further to this, obviously on the cloud build tab you have to give a path to a p12 certificate and the provisioning profile. At the point of compiling, you are asked to enter the password for the p12 file. On a local build or cli build, tns prepare ios --provision lists the provisioning profiles available, but not the one I use in the cloud build. I've tried adding the UUID to the xcconfig file but this fails on the code signing. How to I do a CLI local build using the same p12 and provisioning profile that I use in Sidekick

**Comment by mrwrighty** [comment]
OK, added the p12 to my keychain. tns prepare iOS --provision to get the UUID. Then build app using ./node_modules/.bin/tns build ios --release --forDevice --provision <UUID>.

Used a local path to Nativescript because I installed an earlier version of Nativescript as a dev-dependency to fix a bug in a plugin, otherwise use tns build iOS --release --forDevice --provison <UUID>

**Comment by NickIliev** [comment]
@mrwrighty yep to do a local build you need to use the `--provision` flag and to pass the needed provisiong profile.

To simply see the list of available profiles (which as you mentioned have to be added to the keychaingh) you can run
```
tns run ios --provision
```

to actually build and run against those provisions pass the  profile alias as well
```
tns run ios --provision <name--of-provision-profile>
```
