### ISSUE TITLE
Cannot install SideKick

### ISSUE THREAD

**Issue by hetd54** [NativeScript/sidekick-feedback#373]
### Did you verify whether this issue has already been reported here?
_Yes, saw note from another staff member that file logs are needed to help_

### Tell us about the problem
_Unable to install NativeScript Sidekick-- it doesn't detect any of the pre-reqs even though I have everything installed._

### Which platform(s) does the issue occur on?
_Windows 10_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** Unable to install
- **NativeScript CLI:** 5.3.4
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Follow instructions on installing NativeScript in the terminal at https://docs.nativescript.org/start/ns-setup-win
2. Follow instructions on installing NativeScript Sidekick at https://docs.nativescript.org/sidekick/intro/installation#step-2-install-the-nativescript-cli ..
3. Become stuck on Step 3 because it says it cannot detect additional components to run

### Does this issue happen every time?
_Yes_

### Send the client logs
>_https://gist.github.com/hetd54/551cd4aa354900271592afc7c1c1f095_

**Comment by hetd54** [comment]
Update: Attempted install on another Windows machine. I installed version 10.15.3 of node.js. I installed NativeScript CLI in the terminal. The command "tns" brings up a list of commands and seems successful.

I downloaded NativeScript Sidekick, and again it states that it cannot detect the prerequisites node.js, npm, and NativeScript CLI. Please assist.

**Comment by davicyyo** [comment]
Same problem here
