### ISSUE TITLE
SDK Version Issue. This app was built with the iOS 11.4 SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later. Further, starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

### ISSUE THREAD

**Issue by ann1111** [NativeScript/sidekick-feedback#376]
SDK Version Issue. This app was built with the iOS 11.4 SDK. All iOS apps submitted to the App Store must be built with the iOS 11 SDK or later, included in Xcode 9 or later. Further, starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.

While Upload using xcode 10.1.2 SDK issue I generating from my windows usig sidekick cloud kindly resolve this issue ASAP

**Comment by tsonevn** [comment]
Hi @ann1111,
Make sure that you are using the latest tns-ios(`v.5.3.1`), tns-core-modules(`v. 5.3.2`) and CLI(`v.5.3.4`). If you are using older versions, upgrade ios runtime, modules and CLI, delete `platforms`, `node_modules` folders and  `package-lock.json` file. Then rebuild the project.
