### ISSUE TITLE
On Mac, after first install, the 'Create' is disabled

### ISSUE THREAD

**Issue by realtebo** [NativeScript/sidekick-feedback#377]
I just installed Nativescript Sidekick on Mac with Mojave.

I've already all working from console-side, e.g. I can run tns run ios --bundle.

The problem is that when Sidekick starts, I cannot create a new app, and I see no messages. Actually the 'create' button is disabled.

Why?

**Comment by NickIliev** [comment]
@realtebo have you entered a new name for your app - the button "Create" will be inactive until you input an application name (with the allowed symbols)

**Comment by realtebo** [comment]
I cannot. I have no create button and no open app button. I have only the Whyte background.  




Ottieni Outlook per Android







On Fri, May 17, 2019 at 7:27 AM +0200, "Nick Iliev" <notifications@github.com> wrote:












@realtebo have you entered a new name for your app - the button "Create" will be inactive until you input an application name (with the allowed symbols)

**Comment by NickIliev** [comment]
@realtebo I guess that the above post should contain some screenshots but there are none

**Comment by realtebo** [comment]
I still have the problem. I don't see initial login screen so I see only white background

Also, Login is grayed in the menu 

![image](https://user-images.githubusercontent.com/1268699/58237505-850dcb80-7d45-11e9-992d-8577d5f792c2.png)

**Comment by NickIliev** [comment]
@realtebo sorry for the delay -but we up to this moment we are not able to reproduce the issue. Perhaps it is related to connectivity problem - were you able to resolve your case and if not please verify that you have an active internet connection and that you are using the latest version of Sidekick

**Comment by realtebo** [comment]
The problem is still here and I have no connection issue.

I resolved finding the login page url and opening it manually.

After success login, reopening  the sidekick it finds the login cookie or what else and it works.

I tried to 3 different Mac, with last Mojave . Same issue. So I cannot believe it is happening only to me. But I solved without your help anyway. 
So thanks. Close if you want. But you should test what happen if sw cannot for some reason open the login page or the login dialog on the sw itself. I think. It is a blocking condition. So it is rare but important. Do what you like.
