### ISSUE TITLE
No devices found. iPhone on Windows 10

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/sidekick-feedback#379]
### Did you verify whether this issue has already been reported here?
Yes/

### Tell us about the problem
Sidekick does not find a properly connected iPhone to the USB port

### Which platform(s) does the issue occur on?
_iOS/ <br/>
_Windows 10 64 bits_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** version: 1.16.2-v.2019.3.13.12 (latest)
- **NativeScript CLI:** version: 5.3.2
- **CLI extension nativescript-cloud:** version: 1.17.4
- **CLI extension nativescript-starter-kits:** version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. I created a blank application while the iPhone is properly connected.
I have iTunes installed.
Both iTunes and Windows Explorer connect to the iPhone. See attached document.
Sidekick says "No devices found"

I have Sidekick running on a Windows 7 PC and it connects fine to the same iPhone and same cable.

### Does this issue happen every time?
_Yes/

[console_19-05-16_11-54-06.525.log](https://github.com/NativeScript/sidekick-feedback/files/3192668/console_19-05-16_11-54-06.525.log)
![NoDevicesFound](https://user-images.githubusercontent.com/45446335/57949015-337ec000-78b1-11e9-820f-8dd960eb4100.png)

**Comment by teobugslayer** [comment]
@alexisconsuegra, can you verify that you ahve installed iTunes from the Apple site and not from Windows Store?

**Comment by alexisconsuegra** [comment]
How can I do that? I have tried but the Apple site redirect me to the Windows Store

**Comment by NickIliev** [comment]
@alexisconsuegra  from[ this link ](https://www.apple.com/lae/itunes/download/) - scroll down a bit and you will see links **"macOS  > Windows"** - tap on windows and directly download the iTunes. Also, try to connect the device and then restart Sidekick.

**Comment by alexisconsuegra** [comment]
@NickIliev it worked. Thanks!!!
Now I see that SideKick triggers a build every time I save a file. It says "Hook skipped because either bundling or livesync is in progress". How can I refresh the app in the iPhone without building every time I save a file?

**Comment by alexisconsuegra** [comment]
Hi. It is all good now. FYI. It happened while I was working out of a USB drive. Now back on SSD is all good. Thanks.
