### ISSUE TITLE
Cannot build: Error detected during LiveSync on EP7333JKFA for C:\Users\Bridge\Desktop\FARM\Molot. Error: Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:15.653] [WARN]  clean-webpack-plugin: /mnt/storage/builds/_/d59b5ed09044695e789a4ba1164f9b04fca516ab/5.4.0/5.4.0/Molot/platforms/android/app/src/main/assets/app/**/* has been removed.

### ISSUE THREAD

**Issue by Izrab** [NativeScript/sidekick-feedback#384]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem
I just can't cloud build my app anymore, and I am not sure what is the reason, it might probably because of updating `tns-core-modules` and `nativescript-dev-webpack` to the latest version, or maybe because of trying out Core TypeScript project for the first time. I am not sure, I am a beginner, and not an experienced programmer.

### Which platform(s) does the issue occur on?
Android version 5.1
_Windows 10 Pro

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.16.2-v.2019.3.13.12
- **NativeScript CLI:** 5.4.0
- **CLI extension nativescript-cloud:** 1.17.4
- **CLI extension nativescript-starter-kits:** 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start NativeScript Sidekick
2. Create a new, blank TypeScript core project
3. Change icon and splash screen
4. Add a plugin and make sure to update all plugins to the latest version, including `tns-core-modules`, `nativescript-dev-webpack`, and `nativescript-dev-typescript`.
5. Run this command in CMD in your app root directory to update `webpack.config.js` file, because otherwise it will fail to build:
`node_modules\.bin\update-ns-webpack --configs`
6. Connect your Android phone to laptop via USB cable
7. Select your phone and click on run to build in cloud and run the app
8. Now app should be successfully built on you device
9. Add and install a new plugin on your app to cause a complete new cloud build.
10. Now you should see this ERROR message:

> [19-06-12 01:25:14.924] Error detected during LiveSync on EP7333JKFA for C:\Users\Bridge\Desktop\FARM\Molot. Error: Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:15.585] [WARN]  clean-webpack-plugin: /mnt/storage/builds/_/d59b5ed09044695e789a4ba1164f9b04fca516ab/5.4.0/5.4.0/Molot/platforms/android/app/src/main/assets/app/**/* has been removed.
[00:00:19.660] [WARN]  Executing webpack failed with exit code 2.
[00:00:19.801] [ERROR] clean-webpack-plugin: /mnt/storage/builds/_/d59b5ed09044695e789a4ba1164f9b04fca516ab/5.4.0/5.4.0/Molot/platforms/android/app/src/main/assets/app/**/* has been removed.
Executing webpack failed with exit code 2.
'Build failed with error code 2'.
[19-06-12 01:25:14.936] Couldn't enable debugging for EP7333JKFA, Error: Couldn't enable debugging for EP7333JKFA
    at Errors.fail (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:126:28)
    at Errors.failWithoutHelp (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:136:21)
    at LiveSyncService.<anonymous> (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\livesync-service.js:252:30)
    at Generator.next (<anonymous>)
    at C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\livesync-service.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\livesync-service.js:9:12)
    at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\livesync-service.js:249:16)
    at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\common\decorators.js:67:47)
    at LiveSyncService.<anonymous> (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\livesync-service.js:289:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\services\livesync\livesync-service.js:10:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
OUTPUT 2

### Does this issue happen every time?
_Yes

### Send the client logs
I cannot see any client log files, Logs directory is empty, C:\Users\Bridge\AppData\Roaming\NativeScriptSidekick\Logs\ is empty

### Anything else?
This is my package.json
`{
  "nativescript": {
    "id": "org.nativescript.Molot",
    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "nativescript-couchbase-plugin": "0.9.1",
    "nativescript-mapbox": "4.4.1",
    "nativescript-theme-core": "1.0.6",
    "tns-core-modules": "5.4.2"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "0.10.0",
    "nativescript-dev-webpack": "0.24.1"
  },
  "gitHead": "8ab7726d1ee9991706069c1359c552e67ee0d1a4",
  "readme": "NativeScript Application"
}

}

`

**Comment by Izrab** [comment]
I tried creating a new project in NativeScript CLI and opened and built in sidekick (cloud build), it seems it worked now. I am not sure but I think it works fine now. 
I will in sha Allah report further if something went wrong

**Comment by mennolp098** [comment]
Same issue here...

**Comment by NickIliev** [comment]
@mennolp098 @Izrab trying to reproduce the issue but to no avail.

While using the latest update of NativeScript-Sidekick and CLI 5.4.2 the issue is not reproducible on my side (creating cloud build on Windows 10 - changing the splash and icons and adding plugins no the fly - all working as expected)

**Comment by alereisan** [comment]
same issue here... (after latest nativescript update)

**Comment by NickIliev** [comment]
@alereisan @mennolp098 @Izrab can you guys please delete your webpack.config.js  and make sure that you are using the latest version of `nativescript-dev-webpack`, `tns-core-modules` , and NativeScript CLI. The with removed `node_modules` and platforms rebuild the project.

**Comment by Izrab** [comment]
Alhamdulilah, the problem is gone and solved. I uninstalled sidekick and nodejs on my windows, and then reinstalled, to get fresh latest updates of everything, then I updated every plugin etc... All latest version,

**Comment by Izrab** [comment]
@NickIliev I did exactly what your instructed. I made sure I'm using the latest `nativescript-dev-webpack` and `tns-core-modules`. I deleted webpack.config.js AND node_modules fodler AND platforms AND I rebuild the project, but **SAME ERROR!** is displaying. I Cannot **BUILD MY APP!** **Aaaaaahhhh!**

**Comment by NickIliev** [comment]
@Izrab I've followed step by step your instructions but **after step 9** (install a new plugin) and **before triggering a new cloud build** I've checked the **"Clean Build"** option in Sidekick. This way, we are triggering "cleaned" cloud build (with removed `platforms` on the cloud side). After doing so I am able to build the app and add as many plugins as needed - and after each clean rebuild, the app is working as expected.

If you are still experiencing troubles, then please provide more information about step 3 (which images are you changing) and about the new plugins added (which plugins exactly are added in your "add a plugin step").

**Comment by Izrab** [comment]
@NickIliev , Step 3 is opening my project in Sidekick, and going to "assets" page in Sidekick GUI, and then drag my icon png file and drop it in icon box, and then drag my splash png file and drop it in splash screen box. This generates and applies my icon and splash screen. 

These versions I use

> Version: 1.17.0-v.2019.5.31.1 (latest)
> NativeScript CLI version: 5.4.2
> CLI extension nativescript-cloud version: 1.17.6
> CLI extension nativescript-starter-kits version: 0.3.5

Also this is my 'package.json' file which shows the plugins I use along with their versions:
```
{
  "nativescript": {
    "id": "cloud.hammerhead.molot",
    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.2"
    }
  },
  "description": "Mobile point of sale and inventory management application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "moment": "2.24.0",
    "nativescript-barcodescanner": "3.2.0",
    "nativescript-couchbase-plugin": "0.9.1",
    "nativescript-grid-view": "5.1.0",
    "nativescript-theme-core": "1.0.6",
    "nativescript-ui-autocomplete": "4.1.1",
    "nativescript-ui-calendar": "4.1.0",
    "nativescript-ui-chart": "4.0.2",
    "nativescript-ui-dataform": "4.0.1",
    "nativescript-ui-gauge": "4.0.0",
    "nativescript-ui-listview": "6.4.1",
    "nativescript-ui-sidedrawer": "6.0.0",
    "tns-core-modules": "5.4.3"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.10.0",
    "nativescript-dev-webpack": "0.24.1"
  },
  "gitHead": "8c1a4866a66daab09bf5ef8e5a96472687192373",
  "readme": "NativeScript Application",
  "author": "Barzi Rewandzi"
}

```

Also, some people said something on my question in StackOverflow but not useful to me... 
https://stackoverflow.com/questions/56531587/what-causes-this-webpack-code-2-error-and-how-to-solve-it

**Comment by NickIliev** [comment]
@Izrab we've noticed that you are using `nativescript-couchbase-plugin` which is requiring **mindSDKVersion 19** while the base templates are setting minSDKVersion to 17 (e.g. as done [here](https://github.com/NativeScript/nativescript-app-templates/blob/master/packages/template-blank-ts/app/App_Resources/Android/app.gradle#L14)). Check your **_app.gradle_** and change the minSDKVersion to 19 and then make a clean rebuild. 

If the issue still persists, send us the full error log.

**Comment by Izrab** [comment]
@NickIliev I checked my **_app.gradle_**, it was minSdk 17, I changed it to 19, deleted platform and cloud folders, started a new build, but **same error message is appearing**.
I don't think nativescript couchbase plugin is the one who causes this error, because it shows an ERROR message with useful info about SDK version if the minsdk is not 19, I have experienced this issue before.

**Comment by Izrab** [comment]
@NickIliev **anyways, these are full error logs files** 
[main_19-07-02_21-29-54.789.log](https://github.com/NativeScript/sidekick-feedback/files/3351617/main_19-07-02_21-29-54.789.log)
[console_19-07-02_21-29-52.448.log](https://github.com/NativeScript/sidekick-feedback/files/3351618/console_19-07-02_21-29-52.448.log)
[main_19-07-02_00-23-42.414.log](https://github.com/NativeScript/sidekick-feedback/files/3351619/main_19-07-02_00-23-42.414.log)

**Comment by NickIliev** [comment]
@Izrab I saw that the Webpack is failing on several places with the following error:
```
ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/earnings/earnings-view-model.ts
ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/earnings/earnings-view-model.ts(1,28):
TS2307: Cannot find module 'data/observable'.

ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/expirations/expirations-view-model.ts
ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/expirations/expirations-view-model.ts(1,28):
TS2307: Cannot find module 'data/observable'.

ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/sales/sales-view-model.ts
ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/sales/sales-view-model.ts(1,28):
TS2307: Cannot find module 'data/observable'.

ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/settings/settings-view-model.ts
ERROR in C:/Users/Bridge/Desktop/Mushroom/Molot/app/settings/settings-view-model.ts(1,28):
TS2307: Cannot find module 'data/observable'.

...

Detected short imports in your application. Please note that short imports are deprecated since NativeScript 5.2.0. More information can be found in this blog post https://www.nativescript.org/blog/say-goodbye-to-short-imports-in-nativescript
```

So open those files and replace[ the short imports](https://www.nativescript.org/blog/say-goodbye-to-short-imports-in-nativescript) with full imports
e.g.,
Replace 'data/observable' with `tns-core-modules/data/observable`


Then there is another error about a missing CSS module
```
[ERROR] Module not found: Error: Can't resolve './home-page-common.css' 
```

The file ends in `--common` which might need that you need to add it to your `CopyWebpackPlugin` entries in **webpack.config.js** file. Or just remove the `-common` postfix so that it can be bundled (Webpack will automatically bundle all files in a NativeScript app that are ending with `-page`)

**Comment by Izrab** [comment]
@NickIliev 
Alhamdulilah, **it built successfully** 🎉 After I fixed the two mistakes I had,
I changed `data/observable` to `tns-core-modules/data/observable` (full module import) in all view-model TS files.
and I changed the `@import './home-page-common.css';` to `@import './app-root-common.css';`
for `app-root.xml`

Thanks you all guys.
