### ISSUE TITLE
stuck at "Restarting application on device"

### ISSUE THREAD

**Issue by Razorholt** [NativeScript/sidekick-feedback#388]
I'm using sidekick on windows 10. Every time I hit "run on device" the app gets build just fine but then the process gets stuck at "Restarting application on device". I have to restart the program in order to get out of the loop.

**Comment by NickIliev** [comment]
@Razorholt what settings do you have prior to pressing "Run on device" - is is a local or cloud build?

Verify that your device is connected and recognized by executing `tns devices`. If using emulator, please try to run a different image and make a clean boot for the emulator.

**Comment by gauchannelam** [comment]
I had the same issue... deteted some other apps and restarted my device again and it worked fine.

**Comment by erkanarslan** [comment]
I have the same issue as well. `tns run ios` command on real iPhone device stucks at Restarting application on device...

I have to tap on the app icon to start the app.

NS, iOS and Android versions are 6.1.1

**Comment by erkanarslan** [comment]
When you start the app by tapping its icon, you cannot get the console logs in the terminal. This is very bad.

**Comment by tonyhogben** [comment]
Did you solve this?

**Comment by Upd4ting** [comment]
Still having the same problem, any work-around?
