### ISSUE TITLE
Cannot read property 'nativescript-telerik-ui' of undefined

### ISSUE THREAD

**Issue by cime** [NativeScript/sidekick-feedback#39]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick: 0.2.2-v.2017.8.9.3 (latest)** 
- **NativeScript CLI: 3.1.3** 

### Tell us how to recreate the issue in as much detail as possible.
1. Try to create new Nativescrtipt + Angular & Typescript Master-Detail application

### Does this issue happen every time?
Yes

### Send the client logs.

[17-08-21 17:42:49.484] (Error) Command npm.cmd install tns-template-master-detail-ng@3.1.4 --silent --save-exact --save failed with exit code 1 Error output: 
 C:\Users\cime\Desktop\sidekick\TestSidekick\node_modules\nativescript-imagepicker\scripts\require-nativescript-telerik-ui.js:9
var telerikui = projectPackageJson.dependencies["nativescript-telerik-ui"];
                                               ^

TypeError: Cannot read property 'nativescript-telerik-ui' of undefined
    at Object.<anonymous> (C:\Users\cime\Desktop\sidekick\TestSidekick\node_modules\nativescript-imagepicker\scripts\require-nativescript-telerik-ui.js:9:48)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by dtopuzov** [comment]
Hi @cime 

Can you please post your `node` and `npm` versions.

**Comment by cime** [comment]
@dtopuzov sure

node: **v8.2.1**
npm: **5.3.0**

**Comment by dtopuzov** [comment]
Thanks, I can confirm I hit the same issues when I run:
```
tns create my-app-name --template tns-template-master-detail-ng
```

It looks ok when I create master details demo like this: 
```
tns create my-app-name --template https://github.com/NativeScript/template-master-detail-ng
```

We will investigate the problem and will try to provide fix as soon as possible.

**Comment by dtopuzov** [comment]
Reason for this issue:

`tns-template-master-detail-ng@3.1.4` refer nativescript-imagepicker with ~:
https://github.com/NativeScript/template-master-detail-ng/blob/bac3832697d9a65adf39a753a356f2e490d53de3/package.json#L28

`nativescript-imagepicker@3.0.5` released 4h ago cause the issue.

Latest code in master branch refer strict version so that is why it works.
We should either ship new `tns-template-master-detail-ng` or fix `nativescript-imagepicker` (or both).

**Comment by bundyo** [comment]
The issue has been fixed in nativescript-imagepicker and app creation passes.
