### ISSUE TITLE
Connect Nativescript Sidekick to ios beta 13 simulator

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#394]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I installed Xcode 11 beta and want to connect Sidekick to a beta simulator. It doesn't show up.

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:

Version: 1.17.0-v.2019.5.31.1 (latest)
NativeScript CLI version: 5.4.2
CLI extension nativescript-cloud version: 1.17.6
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Install beta Xcode application
2. Launch simulator
3. Launch Sidekick
4. Try to connect using Virtual Device Launcher or if it is running already, use it in connected devices
5. No beta simulator devices show

### Does this issue happen every time?
Yes

**Comment by NickIliev** [comment]
@bradrice iOS 13 is still Beta version and is not officially supported b NativeScript CLI. Our team is working on the support but it won't be official until iOS 13 is officially released by Apple. The reason for this is that the Beta versions are changing on a daily basis and there is no point to support a work-in-progress.
