### ISSUE TITLE
Cloud build failed: Unable to determine CLI version for cloud build based on project's runtime version: 6.0.0.

### ISSUE THREAD

**Issue by TimoTautenhahn** [NativeScript/sidekick-feedback#397]
Hi Dev-Community,
I seem to have a similiar issue than @Radu2501 posted here originally. I'm leveraging the latest NativeScript CLI v6.0.0 which might be not supported yet...?

Did you verify whether this issue has already been reported here?
Yes

Tell us about the problem
When attempting an iOS cloud build, it fails with the following error:
Build failed. Unable to determine CLI version for cloud build based on project's runtime version: 6.0.0. Error is: Cannot find CLI versions.

Which platform(s) does the issue occur on?
iOS 

Windows 10

Provide the following version numbers that the issue occurs with:
NativeScript Sidekick Desktop: 1.17.0-v.2019.5.31.1
NativeScript CLI: 6.0.0-2019-07-15-122841-13639
CLI extension nativescript-cloud version: 1.18.0
CLI extension nativescript-starter-kits version: 0.3.5
You can obtain the requested information by following the steps outlined below.

Attempt an iOS cloud build
Build fails
Does this issue happen every time?
Yes

[console_19-07-16_01-20-36.555.log](https://github.com/NativeScript/sidekick-feedback/files/3394550/console_19-07-16_01-20-36.555.log)
[main_19-07-16_01-20-37.885.log](https://github.com/NativeScript/sidekick-feedback/files/3394551/main_19-07-16_01-20-37.885.log)

_Originally posted by @TimoTautenhahn in https://github.com/NativeScript/sidekick-feedback/issues/246#issuecomment-511605234_

**Comment by teobugslayer** [comment]
Yes, Sidekick is not currently working with NS CLI 6.0. The team is working on this task and I expect the release very soon.

**Comment by NickIliev** [comment]
The latest version of Sidekick is now supporting CLI version 6.x.x and the previous version 5.4.x.

To resolve the issue just click "Check for Updates" or press **Ctrl + Shift + U**

**Comment by Vinaykummar** [comment]
how to revert back nativescript sidekick to previous version

**Comment by TimoTautenhahn** [comment]
Thank you very much for solving this issue!!!
