### ISSUE TITLE
Missing API Errors After Update to CLI 6.0.0

### ISSUE THREAD

**Issue by anazhd** [NativeScript/sidekick-feedback#398]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Missing APIs

### Which platform(s) does the issue occur on?
macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick: 1.17.0-v.2019.5.31.1** 
- **NativeScript CLI: 6.0.0** 
- **CLI extension nativescript-cloud: 1.18.0** 
- **CLI extension nativescript-starter-kits: 0.3.5** 
- **NodeJS: 10.16.0**

### Tell us how to recreate the issue in as much detail as possible
1. Open terminal, run ```npm i -g nativescript@latest```
2. Update success and verified using ```tns doctor``` to see if there's something missing
3. 

### Does this issue happen every time?
Yes

### Send the client logs
**Client logs**
https://gist.github.com/anazhd/145c808c87365aee24b2a89a0858ae20
**TNS Doctor output**
https://gist.github.com/anazhd/f2d44cd7198e4d8e0e7afb08ad48864b

**Comment by teobugslayer** [comment]
The current version of Sidekick is not working with CLI 6.0. The team is fixing a last minute issue and we are working on releasing a new version of Sidekick which is compatible with CLI 6.0.
