### ISSUE TITLE
Communication with the child process was ended

### ISSUE THREAD

**Issue by sudhanshu-15** [NativeScript/sidekick-feedback#4]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
On opening Sidekick, this is the 1st message that I got after I created a new app.

### Which platform(s) does the issue occur on?
macOS -> version 10.12.6

### Provide the following version numbers that the issue occurs with:

Version: 0.2.0-v.2017.7.31.4 (latest)
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. This is the 1st message that I got.

### Does this issue happen every time?
No -> Only on initial run after creating a new app

### Send the client logs.

[main_17-07-31_11-49-22.936.log.zip](https://github.com/NativeScript/sidekick-feedback/files/1188130/main_17-07-31_11-49-22.936.log.zip)

**Comment by ventsislav-georgiev** [comment]
@sudhanshu-15 Do you use a NodeJS version manager like [n](https://github.com/tj/n), [nvm](https://github.com/creationix/nvm) or other?

**Comment by sudhanshu-15** [comment]
@ventsislav-georgiev no I do not use n or nvm. I just have the package manager npm installed.

**Comment by ventsislav-georgiev** [comment]
@sudhanshu-15 are there any cli_17-07-31_ log files?

**Comment by sudhanshu-15** [comment]
[Archive.zip](https://github.com/NativeScript/sidekick-feedback/files/1188316/Archive.zip)
Here are the files.

**Comment by tsvetie** [comment]
@sudhanshu-15 Try running _tns devices_ in the Terminal to see if this command will fail. In case it does, run "tns devices --log trace &>log.log" and send me the log.log file.

On a side note, are you behind a proxy by any chance?

**Comment by sudhanshu-15** [comment]
@tsvetie sorry for the delay in responding, tns devices works. I am not behind a proxy but on an university network, I can send you the log files if required.

**Comment by mahmoudrabie** [comment]
I have the same issue when I start sidekick.

I have copied the error and paste it here
```
[17-09-05 23:51:08.971] (Error) Communication with the child process was ended. Errors: events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:51287
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

```

**Comment by rosen-vladimirov** [comment]
Hey guys,
We have applied a lot of changes in our product and infrastructure in the last months, so can you please try building your projects once again after installing latest NativeScript Sidekick? In case you still have issues, we'll need the full logs and error messages for investigations.

**Comment by Alpha1001** [comment]
(CLI) events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: unexpected end of file
    at Gunzip.zlibOnError (zlib.js:153:15)
 Build failed. Communication with the child process was ended.

Can anyone help with this?

**Comment by williemaxt** [comment]
@sudhanshu-15 It seems that being on a large LAN throws that error with NativeScript Sidekick
