### ISSUE TITLE
Found some disturbance in NativeScript sidekick page from where we can create or open project line showing address of each project is getting out of its box which leaves bad impression

### ISSUE THREAD

**Issue by ashhadullah19** [NativeScript/sidekick-feedback#406]
![issue](https://user-images.githubusercontent.com/46919624/61870832-923b6800-aef8-11e9-8375-703aefc78ef2.png)

### Did you verify whether this issue has already been reported here?
Yes

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2.. Open home page

### Does this issue happen every time?
Yes

**Comment by tsonevn** [comment]
Hi @ashhadullah19,
Make sure that you are using the latest SideKick version. I checked {N} SideKick on my side, but, I did not notice such a problem.
