### ISSUE TITLE
Wrong version data

### ISSUE THREAD

**Issue by Izrab** [NativeScript/sidekick-feedback#408]
### Did you verify whether this issue has already been reported here?
No_

### Tell us about the problem
Sidekick gives wrong data on package versions, like saying "Latest version: 5.4" for tns-core-modules, whereas the latest version is 6.0.0
![image](https://user-images.githubusercontent.com/22328131/61961705-d07a6b00-af7c-11e9-901b-8637006ada29.png)

### Provide the following version numbers that the issue occurs with:
![image](https://user-images.githubusercontent.com/22328131/61961724-dcfec380-af7c-11e9-8f19-8de51c3c7fc9.png)

### Does this issue happen every time?
_Yes

**Comment by tsonevn** [comment]
Hi @Izrab,
This issue is fixed. Can you check if you will have the same problem with the latest {N} SideKick version?
