### ISSUE TITLE
Support SDK Build Tools 26

### ISSUE THREAD

**Issue by crutchcorn** [NativeScript/sidekick-feedback#41]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Currently, though NativeScript CLI supports Android SDK Build-tools 26, NativeScript Sidekick does not. This allows me to run  `tns run android` via CLI and still not be able to run local builds with Sidekick

### Which platform(s) does the issue occur on?
Android
Windows 10 Creator's Update

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

Version: 0.2.2-v.2017.8.9.3 (latest)
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.7
CLI extension nativescript-starter-kits version: 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application with Build Tools 26 and not 25 installed 
2. Generate any example project
3. Try to build the app for Android

### Does this issue happen every time?
Yes

**Comment by rosen-vladimirov** [comment]
Hey @crutchcorn ,
Thank you for pointing this misalignment between **NativeScript CLI** and **NativeScript SideKick**. We will try to enable support for _Android SDK 26_ in one of the next releases. For the moment you will have to install SDK 25 and it will be used when building your application via **NativeScript SideKick**.
