### ISSUE TITLE
"Enterprise Auth" template lacks its icon and screenshot (small UI/UX issue)

### ISSUE THREAD

**Issue by Izrab** [NativeScript/sidekick-feedback#418]
### Did you verify whether this issue has already been reported here?
No_

### Tell us about the problem
The enteprise auth template does not have an icon and the screenshot, Unlike other templates. See
![image](https://user-images.githubusercontent.com/22328131/63920656-32a01300-c9f6-11e9-8083-a4a52b131811.png)

### Which platform(s) does the issue occur on?
_Windows

### Provide the following version numbers that the issue occurs with:

![image](https://user-images.githubusercontent.com/22328131/63920682-40559880-c9f6-11e9-9dcf-c6dfadfc03a6.png)

### Tell us how to recreate the issue in as much detail as possible
1. Start the application 
2. Create new app
3. Look for the enterprise auth template

### Does this issue happen every time?
_Yes

**Comment by bundyo** [comment]
Probably can't be installed too. The problem in this case is that enterprise authentication template has been removed, but the marketplace, where Sidekick gets its data from, hasn't been updated, hence the non working icons/screenshots. It will be updated today, so the template will disappear.

**Comment by Izrab** [comment]
@bundyo 
**SOLVED** ✅  
It has disappeared from Sidekick. Thanks.
