### ISSUE TITLE
Publishing on IOs Cloud fails after build

### ISSUE THREAD

**Issue by algoz098** [NativeScript/sidekick-feedback#422]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
On publish option, after the build, when i type user and password for Apple Developer, in the middle of the process it throw the folling error:
`Error: Command failed: openssl smime -in "/var/folders/sz/6czcrqd94032_s1qgx6tnmrw0000gq/T/1569001230243.7625/Payload/MaterialComponents.framework/embedded.mobileprovision" -inform der -verify -CAfile "/var/folders/sz/6czcrqd94032_s1qgx6tnmrw0000gq/T/AppleIncRootCertificate.pem" Can't open input file /var/folders/sz/6czcrqd94032_s1qgx6tnmrw0000gq/T/1569001230243.7625/Payload/MaterialComponents.framework/embedded.mobileprovision 4564842092:error:02FFF002:system library:func(4095):No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/crypto/bio/bss_file.c:122:fopen('/var/folders/sz/6czcrqd94032_s1qgx6tnmrw0000gq/T/1569001230243.7625/Payload/MaterialComponents.framework/embedded.mobileprovision', 'rb') 4564842092:error:20FFF080:BIO routines:CRYPTO_internal:no such file:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/crypto/bio/bss_file.c:125: 
`
Tried to redo all the steps, and regenerate certificates

### Which platform(s) does the issue occur on?
iOS
Windows 10

### Provide the following version numbers that the issue occurs with:
Version: 1.19.1-v.2019.8.1.2 (latest)
NativeScript CLI version: 6.1.1
CLI extension nativescript-cloud version: 1.18.2
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the application
2. Opens the project
3. Click on publish
4. Choose IOs with cloud build
5. Click to publish and wait the process
6. When finished type the Apple Developer Email and Password
7. Wait util the error occours

### Does this issue happen every time?
Yes

### Send the client logs
[main_19-09-20_12-20-07.520.log](https://github.com/NativeScript/sidekick-feedback/files/3637133/main_19-09-20_12-20-07.520.log)
[console_19-09-20_12-20-05.291.log](https://github.com/NativeScript/sidekick-feedback/files/3637135/console_19-09-20_12-20-05.291.log)

**Comment by tsonevn** [comment]
Hi @algoz098,
Excuse me for the delay in reply.
Try to clear up the project by deleting `node_modules`, `platforms`, `hooks`, `.cloud` folders and `package-lock.json` file. Also, clear the cloud workspace via ` Clean Cloud Workspace` option in SideKick (`File -> Clean Cloud Workspace`). Then try to rebuild the project and check if the issue will be reproduced again. If the problem persists, please, send us the project or sample one, where the problem can be reproduced.

**Comment by algoz098** [comment]
Hi @tsonevn, there's no problem with the delay. The sidekick is a AMAZING tool, and have help me alot. Thank you!

I have discovery the problem. Was a change inside the app folder, where the code compilled was corrupted.

And your answer was the right one.
