### ISSUE TITLE
How to use vue-devtools?

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/sidekick-feedback#427]
vue-devtools is almost essential for vue development since it's the only way to observe the state of vuex store etc... plus so many other debugging benefits. Is there any way to use that with sidekick local builds?

**Comment by NickIliev** [comment]
@aranmohyeddin so far vue-dev tools is working with only builds only - see [this article on configuration details](https://nativescript-vue.org/en/docs/getting-started/vue-devtools/)

**Comment by aranmohyeddin** [comment]
@NickIliev can you elaborate? you mean builds without sidekick?
