### ISSUE TITLE
uploaded ios app crashed at startup since  october 5

### ISSUE THREAD

**Issue by growerp** [NativeScript/sidekick-feedback#429]
### Did you verify whether this issue has already been reported here?
_Yes/\

### Tell us about the problem
I have been using your IOS cloud service the last few months and it worked fine.
now since October 5 all uploads crash after the startup  image.
They do however work fine in the apple mac  emulator
Downloaded to different iphones 6 with the same result: crashed at startup

### Which platform(s) does the issue occur on?
_iOS Linux
### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** Version: 1.19.1-v.2019.8.1.2 (latest)
- **NativeScript CLI:**  6.1.2 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. upload to Itunes using sidekick
2. download in IOS testflight and start app

### Does this issue happen every time?
_Yes yes starting October 5

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

sidekick seems to upload fine, then in testflight the app (Growerp Restaurant) crashed after the startup image.

i re-uploaded older versions which worked before in test flight and still do, however these uploaded older versions then still crash
 
dump file here:
[dump.txt](https://github.com/NativeScript/sidekick-feedback/files/3695471/dump.txt)

**Comment by NickIliev** [comment]
Hello @growerp 

Regarding 
```
They do however work fine in the apple mac emulator
Downloaded to different iPhones 6 with the same result: crashed at startup
```

If you have access to MAC perhaps can you try to create a local build and deploy on a  real device.
Another option is to produce the IPA file from the cloud and deploy locally on a real device (e.g., via iTunes). Make sure that you are using the proper provisioning profile when building for device.

**Comment by growerp** [comment]
This problem was a pretty difficult one to solve, also because i do not have a Mac. I do not quite understand why people want to program in such a closed environment which requires Apple hardware, not only the phone which i bought just for this, but also you need a Mac which i could use from over the net and with the help of Sidekick!

Luckily after some more tests i found out I had a similar problem in Android too, however only with the --env.production setting. I was not aware this setting could have such an impact.

i got this error:
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: o is not a function
System.err: File: (file:///node_modules/reduce-css-calc/dist/parser.js:154:506)
System.err: 
System.err: StackTrace:....................... 

then i decided to delete parts of the project until the error would at least change...i copied the helloworld screen in, to see if the error would disappear...what did not happen.

Then i decided to start from scratch with the 'tns create' command and compared the package.json file from my project with he one generated by 'tns create'. There i saw in the devDependencies a lot of more files in my project, which were added by other processes i am not aware of.

I replaced my DevDepencies with the ones from 'tns create'....and that solved the problem also for IOS

**Comment by growerp** [comment]
In the end i found that replacing the devDependencies are not the cause because they are not used in production....it was caused by a const being updated.....yes a simple error with big implications..
