### ISSUE TITLE
How to use sidekick without internet?

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/sidekick-feedback#431]
Sidekick doesn't open without internet for me. What I need from sidekick is it's chrome devtools so that I can monitor my network requests. I'm using a real device and the device is connected to internet but my laptop is not connected to internet. So I can't open sidekick. eventho I just want to run a local build.

Is there any opensource alternative to sidekick?

Is there a way to use chrome devtools on my app without using nativescript-sidekick?

**Comment by tsonevn** [comment]
Hi @aranmohyeddin,
Check out [this feature request](https://github.com/NativeScript/sidekick-feedback/issues/415) for enabling offline usage of {N} SideKick. Regarding the chrome devtools, you can use it also via CLI as well. Check the article [here](https://docs.nativescript.org/tooling/debugging/chrome-devtools).

**Comment by aranmohyeddin** [comment]
Thank you so much for the very helpful article and issue link.

**Comment by aranmohyeddin** [comment]
@tsonevn would you be so kind as to explain to me how I was  supposed to find that in the docs?
