### ISSUE TITLE
Sidekick IOS cloud publish timeouts and fails

### ISSUE THREAD

**Issue by kakembo** [NativeScript/sidekick-feedback#437]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Sidekick IOS cloud publish timeout after hours. Fail on amazonaws requests: Can't receive all parts of the response. Retrying request to https://sk-builds-results-us-east-1-v4-production.s3.amazonaws.com/NzNjYTY0OTEtYjI1Yy00YzZmLTQxMWEtZGM0ZDBlM2ZjNTBj/output

Then often hangs there for hours or fails with UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
    at emitWarning (internal/process/promises.js:81:15)

Have tried remedies in issue #321 & #339 ie increasing timeouts (HttpClient.STUCK_REQUEST_TIMEOUT = 600000;)

Have also tried tns platform remove ios before some runs.
### Which platform(s) does the issue occur on?
_iOS<br/>
_Windows
### Provide the following version numbers that the issue occurs with:

Version: 1.19.2-v.2019.11.18.2 (latest)
NativeScript CLI version: 6.2.1
CLI extension nativescript-cloud version: 1.19.3
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Open Angular NS app in sidekick
2. Select Cloud build
3. Start

### Does this issue happen every time?
No - Last worked Nov 6th but failed every day since

### Send the client logs
https://gist.github.com/kakembo/3fd2ac73346994589987311942f29529

**Comment by NickIliev** [comment]
@kakembo we are looking into the timeout case and recently improved some of the server settings that might cause a similar issue. Can you please try (with the latest CLI and Sidekick) a clean rebuild and let us know if the build is successful?

**Comment by kakembo** [comment]
Thanks for looking @NickIliev 
The build is good - The publish still fails I'm afraid.

Main & Console logs on : https://gist.github.com/kakembo/72aae40146276d7a3701088fd9e7d3ef

UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND sk-builds-results-us-east-1-v4-production.s3.amazonaws.com sk-builds-results-us-east-1-v4-production.s3.amazonaws.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26) 

preceded by several: Can't receive all parts of the response. Retrying request to https://sk-builds-results-us-east-1-v4-production.s3.amazonaws.com

**Comment by kakembo** [comment]
Clean build a success btw - See attached. Just the publish seems an issue
[main_19-11-22_19-09-27.490.log](https://github.com/NativeScript/sidekick-feedback/files/3881136/main_19-11-22_19-09-27.490.log)

**Comment by kakembo** [comment]
And just now 1st successful IOS publish for 2.5 weeks.
Don't think I changed anything !
Thanks for whatever the fix was @NickIliev  et al
