### ISSUE TITLE
"Run on Device" button does not reflect correct status.

### ISSUE THREAD

**Issue by EdJones** [NativeScript/sidekick-feedback#463]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem
Nominally, the "run on Device" button seems to have three states:

- Not connected to a device (hazy color, or 'grayed out')
- Connected to a device and ready to begin Livesync (solid blue)
- running livesync (shrinking/growing/looping bars gif)

In this scenario, the "Stop livesync" button would maintain a kind of converse state.

However, most of the time, the "Run on Device" button flops back to solid blue soon after establishing livesync, and stays that way whether the session is responding or not. And, the "Stop Livesync" button remains disabled regardless of the state of the livesync session.

### Which platform(s) does the issue occur on?
_iOS<br/>
_Windows

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Connect device & observe button state change.
3. Run a livesysnc session and monitor button.

### Does this issue happen every time?
I think

**Comment by NickIliev** [comment]
Hello @EdJones - thank you for your observations. The team will take it into consideration.

From my point of view the "Run on Device" is working as expected - it triggers the `tns run` command and should be active only during the actual deployment. The third state  (shrinking/growing/looping bars gif) is actually during the build process and not for the livesync.

From that point on the `Stop Livesync` button becomes active (if the livesync is ON) and will became in-active when we stop the livesync.

**Comment by EdJones** [comment]
@Nicklliev, then it's just really bad US design. The button should not say "Run on device" and be available, while Sidekick is actually running on the device.

(Also, as noted in #451, I nearly NEVER see the "Stop Livesync" button available. It is nearly always gray.)
