### ISSUE TITLE
Please provide a download mirror

### ISSUE THREAD

**Issue by montsamu** [NativeScript/sidekick-feedback#464]
For some reason the firewall software controlling my access does not like "nativescript.cloud". Can you please provide a download mirror for Sidekick on Windows.

**Comment by EdJones** [comment]
@Montsamu. I'm not an insider, but I would think that if nativescript.cloud is blocked, downloading is the least of the problems you'll face. 

Consider this from my log when I started Sidekick this morn:
`[20-01-22 06:53:05.530] (Info) ab.authentication.shell.cloudServicesDomainNames - ["authentication.nativescript.cloud","build.nativescript.cloud","misc.nativescript.cloud","accounts.nativescript.cloud","project.nativescript.cloud","cloud-operation.nativescript.cloud"]`

Is the firewall local? Company? National?

**Comment by montsamu** [comment]
You're right - the best approach is to expedite my company firewall adding nativescript.cloud as allowed. Closing.
