### ISSUE TITLE
NativeScript Sidekick Hangs on macOS

### ISSUE THREAD

**Issue by Spenstar** [NativeScript/sidekick-feedback#47]
### Did you verify whether this issue has already been reported here?
**Yes**

### Tell us about the problem.
After installing NativeScript Sidekick on my Mac, I was able to load it up the firs time with no problem. I then tried running the app on my phone. When I ran the Run on Device option, the program just hung there doing nothing. After a while, I quit the application and reloaded it. Now it just hangs with the loading indicator. I tried uninstalling the program completely and then re-installed it, but now it just hangs there with the loading indicator. **This happened on both my iMac and MacBook Pro.** I can still build and deploy the project through the CLI.

### Which platform(s) does the issue occur on?
**macOS** running Sierra 10.12.6

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 0.2.2-v.2017.8.9.3
- **NativeScript CLI:** 3.2.0
- **CLI extension nativescript-cloud:** 0.1.11
- **CLI extension nativescript-starter-kits:** 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Open NativeScript Sidekick
2. Add an existing NativeScript project
3. Hover over the "Run" option in the top-left and select "Run on Device"
4. Application begins to hang...

### Does this issue happen every time?
**Yes**

### Send the client logs.
[Mac Log](https://gist.github.com/Spenstar/154d55895a3b0aee1b17ed323e77b788)

**Comment by ivanovit** [comment]
Hi @Spenstar,
Last week we fixed an issue which may cause the application to hang. Could you try to install @next version of nativescript cli and tell us if the problem still occurs?

**Comment by Spenstar** [comment]
Thank you! That resolved the issue.
