### ISSUE TITLE
Sidekick can not run on nativescript 6.3.3 windows 10

### ISSUE THREAD

**Issue by Punchi00** [NativeScript/sidekick-feedback#473]
After I update nativescript to version 6.3.3, Nativescript sidekick show It's want to update in windows 10 and can not do anything after its. 
I try uninstall Nativescript sidekick and nativescript but result is same.

**Comment by NickIliev** [comment]
@Punchi00 what do you mean by **_"and can not do anything after its."_**

Is the SideKick running after a complete uninstall? Is a specific feature not working or do you mean that the whole SideKick is not starting at all?

Please provide as much information as possible related to the issue so we could investigate further.
