### ISSUE TITLE
Cannot find module after TNS core tools update

### ISSUE THREAD

**Issue by Noppey** [NativeScript/sidekick-feedback#475]
I've updated tns-core-modules from 6.4.0 to 6.4.1.

Now I get the build error for iOS: Cannot find module '../api-info/api-info.json'
I use angular nativescript and it concerns the code: import ApiInfo from '../api-info/api-info.json';

webpack.config.js contains the necessary filepath and the file is actually contained in the built items:
new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
                { from: { glob: "**/api-info/api-info.json" } },

**Comment by NickIliev** [comment]
@Noppey are you using the latest versions of **nativescript-dev-webpack** and is you**_r webpack.config.js_** also updated with the latest version? Can you post the content of your `package.json`
