### ISSUE TITLE
Android APK is not optimized on review process

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/sidekick-feedback#478]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
APK built is not optimized on review process Android App Bundle format required

### Which platform(s) does the issue occur on?
Android

### Provide the following version numbers that the issue occurs with:

Version: 1.19.2-v.2019.11.18.2 (latest)
NativeScript CLI version: 6.4.1
CLI extension nativescript-cloud version: 1.19.3
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start a build for Android
2. Upload the APK to Google Play Console.
3. Submit it for review

### Does this issue happen every time?
Yes

### Platform versions
{
  "nativescript": {
    "id": "com.domain.myid",
    "tns-android": {
      "version": "6.2.0"
    },
    "tns-ios": {
      "version": "6.2.0"
    }
  },

**Comment by NickIliev** [comment]
@alexisconsuegra SIdekick is not providing option to produce Android App Bundle. However, you could produce and AAB by using a local build for Android.

[See this article ](https://docs.nativescript.org/tooling/publishing/android-app-bundle)on how to produce an AAB with CLI.
