### ISSUE TITLE
Entreprise Auth template missing

### ISSUE THREAD

**Issue by ssougnez** [NativeScript/sidekick-feedback#481]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When I create a new app, I don't see the "Entreprise Auth template".

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.19.2-v.2019.11.18.2 (you're not joking with versioning ha ha)
- **NativeScript CLI:** 6.4.0
- **CLI extension nativescript-cloud:** 1.19.3
- **CLI extension nativescript-starter-kits:** 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Open SideKick
2. Click on "Create App"

### Does this issue happen every time?
Yes

### Remark

Every post I read (including the documentation) explained that I just need to start SideKick, create an app and I'll see the template "Entreprise Auth", however, when I do so, I see all the template but that one.

I also have an additional remark. My goal is to connect an app to my company ADFS. What is the role of Kinvey in here? Does Kinvey imply that the URL used to connect won't be the ADFS but Kinvey?

**Comment by NickIliev** [comment]
We have deprecated this template and it is no longer provided.

As for the Kinvey question - you are not obligated to use Kinvey - it is just a solution used in some of the templates.
