### ISSUE TITLE
Projects Folder doesnt let you create new folder

### ISSUE THREAD

**Issue by davecoffin** [NativeScript/sidekick-feedback#5]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When you are creating a new app, the Projects Folder system dialog does not let you create a new folder.

### Which platform(s) does the issue occur on?
Mac

### Provide the following version numbers that the issue occurs with:
Version: 0.2.0-v.2017.7.31.4 (latest)

Version: 0.2.0-v.2017.7.31.4 (latest)
NativeScript CLI version: 3.1.3
CLI extension nativescript-cloud version: 0.11.6
CLI extension nativescript-starter-kits version: 0.1.11

**Comment by ventsislav-georgiev** [comment]
@davecoffin Thanks for the report. The fix will be available in the next update.
