### ISSUE TITLE
socket timeout in downloading : Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node"

### ISSUE THREAD

**Issue by mbariola** [NativeScript/sidekick-feedback#57]
### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem.
_Give us a concise description of the feature you suggest or the issue you report._

Fresh install of Sidekick on Win10, nativescript perfectly working from CLI. Tried to create a new NS+ JS project , TABBED template.
Build fails with following message:

[17-10-03 12:19:55.611] (Error) Command npm.cmd install failed with exit code 1 Error output: 
 Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node": 

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:13:12)\n    at F (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:68:19)\n    at E (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:80:29)\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:89:16\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\index.js:42:5\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:13:12)\n    at F (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:68:19)\n    at E (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:80:29)\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:89:16\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\index.js:42:5\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher 
gyp verb could not find "python". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\node-sass
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Massi\AppData\Roaming\npm-cache\_logs\2017-10-03T10_19_51_746Z-debug.log
, Error: Command npm.cmd install failed with exit code 1 Error output: 
 Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node": 

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.11.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:13:12)\n    at F (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:68:19)\n    at E (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:80:29)\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:89:16\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\index.js:42:5\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:13:12)\n    at F (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:68:19)\n    at E (C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:80:29)\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\which\\which.js:89:16\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\index.js:42:5\n    at C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher 
gyp verb could not find "python". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\nativescript\\KAMCHATKA\\KAMCHATKA\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\nativescript\KAMCHATKA\KAMCHATKA\node_modules\node-sass
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Massi\AppData\Roaming\npm-cache\_logs\2017-10-03T10_19_51_746Z-debug.log

    at ChildProcess.childProcess.on (C:\Users\Massi\AppData\Roaming\npm\node_modules\nativescript\lib\node-package-manager.js:235:36)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)

### Which platform(s) does the issue occur on?

_Windows 10_

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

Version: 0.2.5-v.2017.9.27.4 (latest)
NativeScript CLI version: 3.2.1
CLI extension nativescript-cloud version: 0.13.0
CLI extension nativescript-starter-kits version: 0.1.16

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. create new app
3. put KAMCHATKA as name of app
4 c:\nativescript\KAMCHATKA as folder
5 com.orphic.kamchatka as id (planning to build for android anyway)
6. select NS + JS app, TABBED template
7. build
8 error.

### Does this issue happen every time?
_Yes_

### Send the client logs.

https://gist.github.com/mbariola/101e74a85b387279ce389dfd2f559ed1

**Comment by ventsislav-georgiev** [comment]
@mbariola It seems that the error is:
`gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`
Which is returned by [node-gyp](https://github.com/nodejs/node-gyp#nodejs-native-addon-build-tool). Which is used by npm when the installed package uses native dependencies that need recompilation for your environment. 

Here is a list of node-gyp prerequisites for windows:
https://github.com/nodejs/node-gyp#on-windows

**Comment by ventsislav-georgiev** [comment]
@mbariola On a second note the node-gyp is trying to rebuild from sources because the download of the precompiled binaries fails with the socket error. Here is an issue related to the same error: https://github.com/sass/node-sass/issues/1888

There is a workaround mentioned for the same node-sass version (v4.5.3):
* manually download the binary from [github](https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node) 
* run the command to install node-sass by specifying the path for the downloaded binary:
`npm install node-sass --sass-binary-path="D:\win32-x64-48_binding.node"`
