### ISSUE TITLE
Side not installing on my system

### ISSUE THREAD

**Issue by mict-exp** [NativeScript/sidekick-feedback#67]
## Please, provide the details below:
I am trying to install sidekick on my development system. All attempt terminated with the below error:

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
Nativescript Sidekick
Windows 7

### Provide the following version numbers that the issue occurs with:
NativeScript Sidekick

### Tell us how to recreate the issue in as much detail as possible.
Installation

### Does this issue happen every time?
Yes

### Send the client logs.
[SquirrelSetup.log](https://github.com/NativeScript/sidekick-feedback/files/1385303/SquirrelSetup.log)

**Comment by ahitrov** [comment]
Hi @mict-exp ,

Do you by any chance try to install NativeScript Sidekick on a 32-bit Windows 7?

Currently only 64-bit OSes are supported:
http://docs.nativescript.org/sidekick/intro/requirements.html
