### ISSUE TITLE
TypeError: Cannot read property 'isUserLoggedIn' of undefined

### ISSUE THREAD

**Issue by felix-idf** [NativeScript/sidekick-feedback#68]
### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem.
Since the latest Update of NS Sidekick (0.2.6...) I get the following error when running the program on Windows:
_[17-10-16 14:37:40.340] (Error) Cannot read property 'isUserLoggedIn' of undefined, TypeError: Cannot read property 'isUserLoggedIn' of undefined at CLIUserService.executeIsUserLoggedIn (C:\Users\pc1-local\AppData\Local\NativeScriptSidekick\app-0.2.6-v201710131\resources\app.asar.unpacked\cli\base\cli-service-base.js:49:52) at CLIUserService.executeGetUser (C:\Users\pc1-local\AppData\Local\NativeScriptSidekick\app-0.2.6-v201710131\resources\app.asar.unpacked\cli\base\cli-service-base.js:53:25) at requireCLI.then (C:\Users\pc1-local\AppData\Local\NativeScriptSidekick\app-0.2.6-v201710131\resources\app.asar.unpacked\cli\services\cli-user-service.js:18:33) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)_

I am not able to login and to build the app project.

### Which platform(s) does the issue occur on?
_Windows 10_

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 0.2.6-v201710131

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..

### Does this issue happen every time?
_Yes_

### Send the client logs.
[Logs](https://gist.github.com/felix-idf/46788335c3a860975e19cd03dc4b154d)

**Comment by MilosStanic** [comment]
I had the same error on Mac OS, plus some other errors about being unable to install some npm's. However after restarting Sidekick 3-4 times in a row and after a series of npm errors, it started just fine. 

I also changed the permissions in my `./local/share/.nativescript-cli/extensions/node_modules` dir to 777, after the initial start with the above error. Then restarted it 2 more times, and it worked. 

I hope this was of help to @tsvetie in identifying the problem.

**Comment by tsvetie** [comment]
Hey @felix-idf, I have an assumption that I will need your help to verify. Could you please try the following:

1. Close Sidekick
2. Navigate to the following folder and delete the extensions folder:
Windows: _%AppData%\.nativescript-cli_
macOS: _~/.local/share/.nativescript-cli_
Linux: _~/.local/share/.nativescript-cli_
3. Start Sidekick again

Let me know if you get the errors again after this.

@MilosStanic, thanks for jumping in with more information - much appreciated. Unfortunately, there are a couple of situations that lead to the "'isUserLoggedIn' of undefined" error. In short, Sidekick installs two extensions (npm packages) of NativeScript CLI and some versions of Sidekick update the versions of these extensions. In case the npm commands fail, you would get errors as some of the functionality that Sidekick relies on is missing. Your case sounds a bit more like a permissions problem, unlike the case of felix-idf. We are looking into these problems to see how we can at least make identifying the problem for a user easier.

**Comment by felix-idf** [comment]
Hey @tsvetie , thanks. I forgot to delete this folder. Now it works for me.
