### ISSUE TITLE
Soft keyboard overlaps portion of the view only in project created with SideKick - normal behavior in CLI

### ISSUE THREAD

**Issue by kshaheen** [NativeScript/sidekick-feedback#69]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem.
I have simple chat component with gridlayout. The input and send button is located at the bottom of the page. When the soft keyboard shows, it overlaps/covers a portion of the view including the input and send button. This behavior only happens on project created with SideKick (Angular + Blank). In project created with CLI (tns create {ProjectName} --ng), the soft keyboard behavior is normal, pushing the view content up. The same component is used in both projects (created with SideKick and created with CLI).
** The component files (html and ts) are attached as .zip:
[chat-component.zip](https://github.com/NativeScript/sidekick-feedback/files/1401500/chat-component.zip)

### Which platform(s) does the issue occur on?
Android 8.0
Windows 10

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick: 0.2.6-v.2017.10.31.1
- **NativeScript CLI: 3.2.1
- **CLI extension nativescript-cloud: 0.16.0
- **CLI extension nativescript-starter-kits: 0.2.1

### Tell us how to recreate the issue in as much detail as possible.
1. Start a new project using SideKick: Angular + Blank
2. Copy the attached component into the project and configure as default route
3. When app starts, click on the input at bottom of the screen, the soft keyboard shows up and covers the content
4. Repeat the same steps but with CLI using command "tns create {ProjectName} --ng". Click the input at the bottom, the soft keyboard shows and pushes up the content , which is the normal behavior.

### Does this issue happen every time?
_Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
[console_17-10-20_12-30-03.616.log](https://github.com/NativeScript/sidekick-feedback/files/1401515/console_17-10-20_12-30-03.616.log)
[main_17-10-20_12-30-07.240.log](https://github.com/NativeScript/sidekick-feedback/files/1401516/main_17-10-20_12-30-07.240.log)
[cli_17-10-20_12-30-10.674.log](https://github.com/NativeScript/sidekick-feedback/files/1401517/cli_17-10-20_12-30-10.674.log)

**Comment by manoldonev** [comment]
The problem is related to this issue [here](https://issuetracker.google.com/issues/36986276) as translucent status bar is used for all templates but the hello-world at the moment (this is the one created with `tns create {ProjectName} --ng`).

You can fix the overlapping by setting `android:windowSoftInputMode="adjustResize"` attribute to the NativeScriptActivity in **[app-root]\app\App_Resources\Android\AndroidManifest.xml**:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="1"
	android:versionName="1.0">

        <!-- ...  -->

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme"
			android:windowSoftInputMode="adjustResize">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		
        <!-- ...  -->

	</application>
</manifest>
```

Or you can disable the translucent status bar altogether by updating the contents of **[app-root]\app\App_Resources\Android\values-v21\styles.xml** to:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Application theme -->
    <style name="AppTheme" parent="AppThemeBase">
        <item name="android:datePickerStyle">@style/SpinnerDatePicker</item>
        <item name="android:timePickerStyle">@style/SpinnerTimePicker</item>
    </style>

    <!-- Default style for DatePicker - in spinner mode -->
    <style name="SpinnerDatePicker" parent="android:Widget.Material.Light.DatePicker">
        <item name="android:datePickerMode">spinner</item>
    </style>

    <!-- Default style for TimePicker - in spinner mode -->
    <style name="SpinnerTimePicker" parent="android:Widget.Material.Light.TimePicker">
        <item name="android:timePickerMode">spinner</item>
    </style>

    <style name="NativeScriptToolbarStyle" parent="NativeScriptToolbarStyleBase">
        <item name="android:elevation">4dp</item>
    </style>    
</resources>
```

**Comment by kshaheen** [comment]
Thanks for the information. I already tried adding android:windowSoftInputMode="adjustResize" in the activity in AndroidManifest.xml, but it didn't fix the issue. The only way is to disable the Translucent Bar.

I've been looking around for a while and many are facing the same issue. I am confused though because many known apps such as WhatsApp has both the translucent bar and the resize working together.
My suggestion is, if it's an issue, to have the translucent bar disabled by default in the templates or at least the line commented.

**Comment by manoldonev** [comment]
@kshaheen Indeed, it seems you are right -- `android:windowSoftInputMode="adjustResize"` does not have any effect, only `android:windowSoftInputMode="adjustPan"` does (but at the price of panning the whole screen up).

We have decided to remove the translucent status bar from the default blank template and leave the decision whether to use it at the developer's discretion.
