### ISSUE TITLE
Size Problem

### ISSUE THREAD

**Issue by runbb** [NativeScript/sidekick-feedback#7]
cant click output button
![screenshot_20170801_061741](https://user-images.githubusercontent.com/20779154/28807978-7de56e84-7681-11e7-8b9f-b767c61edc0a.png)

**Comment by bundyo** [comment]
This issue has been fixed and the fix will be available with the next release.

**Comment by bundyo** [comment]
Keep in mind that old size is saved, you will need to resize the window smaller (or maximize it)

**Comment by runbb** [comment]
version 0.2.2
The problem is unresolved
![screenshot_20170818_153116](https://user-images.githubusercontent.com/20779154/29459020-99d7ecd2-842a-11e7-9944-c0367722fb16.png)

**Comment by bundyo** [comment]
Try resizing or maximizing the window, as it remembers its last position.

**Comment by runbb** [comment]
I did it but the same problem was not resolved

**Comment by bundyo** [comment]
We checked desktop resolution stats before doing the fix and the most used ones are 768px+ desktop height, which should be supported. What is your exact resolution, is it 720p perchance?

**Comment by runbb** [comment]
1366x768

**Comment by bundyo** [comment]
Seems KDE takes some additional space or Electron doesn't resize the window properly. I'll reopen this then.
