### ISSUE TITLE
Child communication error: missing path

### ISSUE THREAD

**Issue by henkvhest** [NativeScript/sidekick-feedback#70]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When starting the installer it goes from "installing" to another loading window. It's during this window that the following error message pops up:

Communication with the child process was ended. Errors: assert.js:41
(also see gist below)

### Which platform(s) does the issue occur on?
Windows 10 10.0.15063 Build 15063

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick:** 
0.2.6-v201710131
- **NativeScript CLI:** 
3.2.1

### Tell us how to recreate the issue in as much detail as possible.
1. Start the installer
2. Wait untill "Install"  is no longer on the screen and a new loading screen pops up, Sidekick should now be available in the taskbar

### Does this issue happen every time?
Yes

### Send the client logs.
[main_17-10-20_14-29-38.548.log](https://gist.github.com/henkvhest/cb226263dd4c226360c7c55f548ff644#file-main_17-10-20_14-29-38-548-log)
[console_17-10-20_14-29-29.836.log](https://gist.github.com/henkvhest/50ea9e00e58f66fe60453d328082e6b5#file-console_17-10-20_14-29-29-836-log)
[cli_17-10-20_14-29-42.427.log](https://gist.github.com/henkvhest/4aba271e53e24de8729b7a92c1b76fa3#file-cli_17-10-20_14-29-42-427-log)

**Comment by bundyo** [comment]
This link should be a bit more readable:
https://gist.github.com/henkvhest/a7e48a642138c6c4af6aa191371abb33#file-main_17-10-20_13-15-58-282-log

**Comment by henkvhest** [comment]
@bundyo Thanks, updated mine aswell

**Comment by tsvetie** [comment]
Hey @henkvhest, can you send us the rest of the log files as well - the "console" and "cli" are the ones I am after.

**Comment by henkvhest** [comment]
Here you go:
[console_17-10-20_14-29-29.836.log](https://gist.github.com/henkvhest/50ea9e00e58f66fe60453d328082e6b5#file-console_17-10-20_14-29-29-836-log)
[cli_17-10-20_14-29-42.427.log](https://gist.github.com/henkvhest/4aba271e53e24de8729b7a92c1b76fa3#file-cli_17-10-20_14-29-42-427-log)

**Comment by henkvhest** [comment]
I used Yarn instead of NPM to install the NativeScript CLI globally.  Switched back to using NPM:

`npm install -g nativescript` did the trick.
