### ISSUE TITLE
Not able to build Android (Local and cloud) both

### ISSUE THREAD

**Issue by abhinavaggarwal8** [NativeScript/sidekick-feedback#73]
Not able to build both cloud and local Android.

### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem.
I was previously working on Android Studio and in the android studio, there were no issues in building any application.
Now, while trying to setup native script "tns doctor" also shows some warnings.
I have updated ANDROID_HOME and JAVA_HOME and tried again but the issue persists with "tns doctor", Every time when i run "tns doctor" it updates my ANDROID_HOME which is fine but "sdkmanager" shows some errors and hence android fails to build.

In sidekick or terminal every time while building application there are same errors and pop-ups with this title "Your system is not configured for local builds" opens.

Issue with "Android-sdk" setup
==> Satisfying dependencies
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/itengine/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Verifying checksum for Cask android-sdk
==> Installing Cask android-sdk
==> Exception in thread "main" 
==> java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
==> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
==> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
==> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
==> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
==> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
==> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
==> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
==> 	... 5 more
Error: Command failed to execute!

Issue with "sdkmanager" mentioned below- 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more

### Which platform(s) does the issue occur on?
Build for Android
Building on macOSX

### Provide the following version numbers that the issue occurs with:
Version: 0.2.6-v.2017.10.13.1 (latest)
NativeScript CLI version: 3.2.1
CLI extension nativescript-cloud version: 0.16.0
CLI extension nativescript-starter-kits version: 0.2.1

### Tell us how to recreate the issue in as much detail as possible.
1. While Setting up on MacBookAir which was previously used for Android Native Development

### Does this issue happen every time?
_Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

[cli_17-10-19_13-47-05.451.log](https://github.com/NativeScript/sidekick-feedback/files/1410554/cli_17-10-19_13-47-05.451.log)
[cli_17-10-19_14-01-47.975.log](https://github.com/NativeScript/sidekick-feedback/files/1410555/cli_17-10-19_14-01-47.975.log)
[cli_17-10-19_22-34-55.542.log](https://github.com/NativeScript/sidekick-feedback/files/1410556/cli_17-10-19_22-34-55.542.log)
[cli_17-10-23_10-39-53.781.log](https://github.com/NativeScript/sidekick-feedback/files/1410557/cli_17-10-23_10-39-53.781.log)
[cli_17-10-23_12-23-10.148.log](https://github.com/NativeScript/sidekick-feedback/files/1410558/cli_17-10-23_12-23-10.148.log)
[cli_17-10-24_11-57-36.320.log](https://github.com/NativeScript/sidekick-feedback/files/1410559/cli_17-10-24_11-57-36.320.log)
[cli_17-10-24_12-13-34.678.log](https://github.com/NativeScript/sidekick-feedback/files/1410560/cli_17-10-24_12-13-34.678.log)
[cli_17-10-24_15-02-48.894.log](https://github.com/NativeScript/sidekick-feedback/files/1410561/cli_17-10-24_15-02-48.894.log)
[cli_17-10-24_15-13-25.481.log](https://github.com/NativeScript/sidekick-feedback/files/1410563/cli_17-10-24_15-13-25.481.log)
[cli_17-10-24_15-19-10.906.log](https://github.com/NativeScript/sidekick-feedback/files/1410564/cli_17-10-24_15-19-10.906.log)
[cli_17-10-24_15-33-47.380.log](https://github.com/NativeScript/sidekick-feedback/files/1410565/cli_17-10-24_15-33-47.380.log)
[cli_17-10-24_16-19-39.657.log](https://github.com/NativeScript/sidekick-feedback/files/1410566/cli_17-10-24_16-19-39.657.log)
[console_17-10-18_15-03-40.802.log](https://github.com/NativeScript/sidekick-feedback/files/1410567/console_17-10-18_15-03-40.802.log)
[console_17-10-19_13-47-00.071.log](https://github.com/NativeScript/sidekick-feedback/files/1410568/console_17-10-19_13-47-00.071.log)
[console_17-10-19_14-01-41.473.log](https://github.com/NativeScript/sidekick-feedback/files/1410569/console_17-10-19_14-01-41.473.log)
[console_17-10-19_22-34-49.098.log](https://github.com/NativeScript/sidekick-feedback/files/1410570/console_17-10-19_22-34-49.098.log)
[console_17-10-23_10-39-47.656.log](https://github.com/NativeScript/sidekick-feedback/files/1410571/console_17-10-23_10-39-47.656.log)
[console_17-10-23_12-22-58.511.log](https://github.com/NativeScript/sidekick-feedback/files/1410572/console_17-10-23_12-22-58.511.log)
[console_17-10-24_11-57-28.467.log](https://github.com/NativeScript/sidekick-feedback/files/1410573/console_17-10-24_11-57-28.467.log)
[console_17-10-24_12-13-22.023.log](https://github.com/NativeScript/sidekick-feedback/files/1410574/console_17-10-24_12-13-22.023.log)
[console_17-10-24_15-02-41.971.log](https://github.com/NativeScript/sidekick-feedback/files/1410575/console_17-10-24_15-02-41.971.log)
[console_17-10-24_15-13-19.456.log](https://github.com/NativeScript/sidekick-feedback/files/1410576/console_17-10-24_15-13-19.456.log)
[console_17-10-24_15-19-04.851.log](https://github.com/NativeScript/sidekick-feedback/files/1410577/console_17-10-24_15-19-04.851.log)
[console_17-10-24_15-33-40.855.log](https://github.com/NativeScript/sidekick-feedback/files/1410578/console_17-10-24_15-33-40.855.log)
[console_17-10-24_16-19-34.025.log](https://github.com/NativeScript/sidekick-feedback/files/1410579/console_17-10-24_16-19-34.025.log)

[main_17-10-18_15-03-43.561.log](https://github.com/NativeScript/sidekick-feedback/files/1410581/main_17-10-18_15-03-43.561.log)
[main_17-10-19_13-47-02.561.log](https://github.com/NativeScript/sidekick-feedback/files/1410582/main_17-10-19_13-47-02.561.log)
[main_17-10-19_14-01-44.530.log](https://github.com/NativeScript/sidekick-feedback/files/1410583/main_17-10-19_14-01-44.530.log)
[main_17-10-19_22-34-52.282.log](https://github.com/NativeScript/sidekick-feedback/files/1410584/main_17-10-19_22-34-52.282.log)
[main_17-10-23_10-39-50.470.log](https://github.com/NativeScript/sidekick-feedback/files/1410585/main_17-10-23_10-39-50.470.log)
[main_17-10-23_12-23-06.254.log](https://github.com/NativeScript/sidekick-feedback/files/1410586/main_17-10-23_12-23-06.254.log)
[main_17-10-24_11-57-32.557.log](https://github.com/NativeScript/sidekick-feedback/files/1410587/main_17-10-24_11-57-32.557.log)
[main_17-10-24_12-13-28.152.log](https://github.com/NativeScript/sidekick-feedback/files/1410589/main_17-10-24_12-13-28.152.log)
[main_17-10-24_15-02-45.446.log](https://github.com/NativeScript/sidekick-feedback/files/1410590/main_17-10-24_15-02-45.446.log)
[main_17-10-24_15-13-22.435.log](https://github.com/NativeScript/sidekick-feedback/files/1410591/main_17-10-24_15-13-22.435.log)
[main_17-10-24_15-19-07.543.log](https://github.com/NativeScript/sidekick-feedback/files/1410592/main_17-10-24_15-19-07.543.log)
[main_17-10-24_15-33-44.205.log](https://github.com/NativeScript/sidekick-feedback/files/1410593/main_17-10-24_15-33-44.205.log)
[main_17-10-24_16-19-36.803.log](https://github.com/NativeScript/sidekick-feedback/files/1410594/main_17-10-24_16-19-36.803.log)

**Comment by dtopuzov** [comment]
Hi @abhinavaggarwal8 

Can you please check your Java version with this command: `java -version`.
NativeScript require 1.8 and it do not support 1.9 at the moment.

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for a long time. Please, feel free to reopen it if you still encounter this issue with the latest version of Sidekick.

Thank you!

**Comment by bart** [comment]
I'm having the same issue. @abhinavaggarwal8 How did you solve it?

**Comment by ladigitale** [comment]
I'm having the same issue. with java 1.8.0_181
