### ISSUE TITLE
Endpoint request timeout when trying to Auto Generate Provisioning Profile and Certificate for iOS

### ISSUE THREAD

**Issue by meshmmanuel** [NativeScript/sidekick-feedback#74]
### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem.
Getting 

> (Error) {"message": "Endpoint request timed out"}, Error: {"message": "Endpoint request timed out"} at IncomingMessage.responseStream.on (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:135:45) at emitNone (events.js:91:20) at IncomingMessage.emit (events.js:185:7) at endReadableNT (_stream_readable.js:974:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)

while trying to generate provisioning profile and certificate.

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** Sidekick 0.2.6

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Select application
3. Goto Run and Build on Device
4. Select gear button for iOs and generate provisioning profile and cert.

### Does this issue happen every time?
_Yes_

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by teobugslayer** [comment]
Hi @meshmmanuel ,

We had an issue with our infrastructure which we fixed. Please try again - it should work now.

Best regards,
Todor
