### ISSUE TITLE
Provide a sensible default for Android > Application Version Code

### ISSUE THREAD

**Issue by rastographics** [NativeScript/sidekick-feedback#77]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When creating a new app, under General Settings > Application Version, this warning appears: "To use this field, you need to unify the Android and iOS versioning." 

Then I have to click on the help link, and go figure out that I need to do some math to come up with the correct number to put in on Android > Application Version Code.

For new apps, why doesn't Sidekick default the Android > Application Version Code to 10,000 to begin with? Seems unnecessary to make the developer figure out a setting that can easily be made the default.

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

Version: 0.2.7-v.2017.10.26.3 (latest)
NativeScript CLI version: 3.3.0
CLI extension nativescript-cloud version: 0.16.0
CLI extension nativescript-starter-kits version: 0.3.1

### Tell us how to recreate the issue in as much detail as possible.
When creating a new app, under General Settings > Application Version, this warning appears: "To use this field, you need to unify the Android and iOS versioning." 

### Does this issue happen every time?
Yes

**Comment by teobugslayer** [comment]
@rosen-vladimirov

**Comment by tsvetie** [comment]
Hey @rastographics, you know how sometimes an idea could be very obvious to a bystander and once it is out there, it becomes obvious to everyone? I think this is the case with your suggestion. I will add it to our ToDo list.

**Comment by tsvetie** [comment]
This is already live. New projects should have General Settings > Application Version enabled by default.
