### ISSUE TITLE
Can't select provision profile and certificate - MacOS

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/sidekick-feedback#8]
Hi, 

I have problem with selecting certificates. Files are not clickable.
I am using MacOS X high sierra.

![snimek obrazovky 2017-08-01 v 8 55 50](https://user-images.githubusercontent.com/4247839/28812939-63960be0-7697-11e7-8da7-b2f1023f5dc8.png)

**Comment by ventsislav-georgiev** [comment]
@b4rtt by clicking the *Select Provision* button the file dialog intentionally is validating that the file extension to be `.mobileprovision`. However, the *Select Certificate* button will also not allow you to select a `.cer` file, because the only supported file format currently is `.p12`. This will be improved in the future.

**Comment by gabitoesmiapodo** [comment]
For Android, the only file extension I could get working was .p12, but I usually have my store keys named something like googleplaykey.keystore or googleplaykey.jks

**Comment by ventsislav-georgiev** [comment]
@gabitoesmiapodo Thanks for the feedback. The .keystore and .jks files will be allowed in the next release.

**Comment by tsvetie** [comment]
@gabitoesmiapodo Just to note that these file extensions will be supported only for local builds and not cloud builds. Support for cloud builds will be added at a later stage.

**Comment by stoskov** [comment]
Meanwhile you could convert these certificates to .p12 files and use them in the cloud builds as well. More information how to do it could be found [here]( https://www.tbs-certificates.co.uk/FAQ/en/627.html).

**Comment by rdlauer** [comment]
Wondering why this is closed when this still appears to be the case for Sidekick and .cer files?

**Comment by rdlauer** [comment]
I just confirmed with the latest version that if I use Sidekick to generate the CSR I can't export the p12 file from within keychain. If I generate the CSR with keychain it works fine.

**Comment by erkanarslan** [comment]
This is still a problem. I cannot use .cer file for Sidekick
