### ISSUE TITLE
fsevents.o has conflicting provisioning settings.

### ISSUE THREAD

**Issue by JuergenSimon** [NativeScript/sidekick-feedback#80]
### Did you verify whether this issue has already been reported here?
Yes. 

### Tell us about the problem.
I'm trying to debug an application. It has only ios as platform so far. 
Command line: tns debug ios works.
Same command in WebStorm IDE works.
Both of the above don't give any workable debugging. The remote debugger is horrific and can't handle reloads. The Nativescript Inspector is slow, lacks basic features and freezes/crashes constantly. Unusable. 
So I tried my luck with Sidekick. While the other two methods build fine and start on the emulator, Sidekick categorically conks out with this error message:

[17-11-04 18:47:04.586] (Error) Command xcodebuild failed with exit code 70 Error output: 2017-11-04 18:47:01.202 xcodebuild[77335:605317] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/wx/7q2n1sm97vq46y42q2xnyj_w0000gp/T/bellyachesmobile_2017-11-04_18-47-01.201.xcdistributionlogs'. 2017-11-04 18:47:04.526 xcodebuild[77335:605317] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fb96649d0d0>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=( "Error Domain=IDEProvisioningErrorDomain Code=8 \"fse.node has conflicting provisioning settings.\" UserInfo={NSLocalizedDescription=fse.node has conflicting provisioning settings., NSLocalizedRecoverySuggestion=fse.node is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified. Remove the \"signingCertificate\" entry from your Export Options property list, or switch to manual signing by setting \"signingStyle\" to \"Manual.}", 
...

this is repeated about half a dozen times or so. I opened the XCode project in platform/ios and inspected the settings. Seemed ok (at least no complaints from xcode). I have wasted 2 days on trying to get a debuggable setup. 

### Which platform(s) does the issue occur on?
_iOS_

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick: Version: 0.2.7-v.2017.10.26.3 (latest)** 
- **NativeScript CLI: 3.3.0** 

### Tell us how to recreate the issue in as much detail as possible.
1. Open a project with ios and hit build. 

### Does this issue happen every time?
_Yes_

### Send the client logs.
https://gist.github.com/JuergenSimon/ff62edbfc3f2b8e2617371e4b244d0e0#file-sidekickbuildlogs-log

**Comment by JuergenSimon** [comment]
I created a new project using sidekick itself, using the same application id. Same problem.

**Comment by tsvetie** [comment]
Hey @JuergenSimon,
Regarding your experience with NativeScript CLI - you can use the DevTools debugger with NativeScript CLI as well. Just pass the "--chrome" flag:

```
tns debug ios --chrome
```

As to the error in Sidekick - this can happen, in case you have a binary in node_modules. The focus of your error is this part - "fse.node is automatically signed for distribution". I am guessing that you have fsevents as dependency or it is a dependency of a dependency. You can execute _npm ls fsevents_ in the Terminal and the output of this command will give you information which package is referencing fsevents. Make sure that it is a devDependency or an optionalDependency as in case your package has a binary, you might not be able to publish it.

Now, regarding your debug build - you have the following options:
1. Use cloud build - only cloud builds respect the code signing that you specify from Sidekick UI, local iOS builds, do not.
2. Go to your build.xcconfig file (_[app_folder]/app/App_Resources/iOS_) and specify CODE_SIGN_IDENTITY. This will enforce Manual code signing.

On a side node, did you pass "--provisioning" when you executed _tns debug ios_? This is the only reason I could think of why you did not get the error with NativeScript CLI, but you got it with NativeScript Sidekick.

**Comment by JuergenSimon** [comment]
Hello @tsvetie,

thanks for responding. I stopped looking for the problem and instead re-created the project from ground up using Sidekick rather than the WebStorm {N} plugin. The resulting project works as advertised in Sidekick and command line. Perhaps there is some subtle difference in the way the projects are created?

**Comment by tsvetie** [comment]
Not sure about that, but I can look into it. Can you list the steps you used to create your app with WebStorm {N} plugin?

**Comment by tsvetie** [comment]
Here are my findings - basically, the WebStorm plugin uses the same templates as Sidekick and the same CLI commands. However, it seems that WebStorm first creates the project in a temp folder and then copies the files to the folder you specified. This leads to the following difference and this is the only difference - the metadata, that is added to package.json files in mode_modules has incorrect absolute paths.

However, I tested both local and cloud builds in Sidekick and CLI with a project, created with WebStorm and I did not get any errors. I am guessing, if there is a problem that this difference leads to, it is in a specific case and depends on the specific version of npm.

**Comment by JuergenSimon** [comment]
Hello Tsvetlelina,

thank you very much for your findings. My lesson to take home is to create the project in Sidekick and then use WebStorm for editing, Visual Studio for debugging. Messy but works. 

J.

**Comment by tsvetie** [comment]
Hey Juergen, just out of curiosity, why don't you user the debugger of Sidekick? Did you have problems with it?

**Comment by JuergenSimon** [comment]
Hello,

> On 8. Nov 2017, at 13:19, Tsvetelina Ivanova <notifications@github.com> wrote:
> 
> Hey Juergen, just out of curiosity, why don't you user the debugger of Sidekick? Did you have problems with it?
> 
> 

Yes. It constantly crashed and it was not possible to debug something at application start-up. 

Cheers,
Jürgen

**Comment by tsvetie** [comment]
Logged your last comment as a feature request to see if other people need it as well #90

**Comment by JuergenSimon** [comment]
Great, thanks.
