### ISSUE TITLE
Issue with live sync when "Start Debugger" is selected

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/sidekick-feedback#84]
When Start Debugger is selected, any synced changes restarts the app (iOS).

**Comment by ventsislav-georgiev** [comment]
@alexrainman unfortunately, this is by design. We need to force the debugger to reload its resources. Could be improved in the future.

**Comment by alexrainman** [comment]
The thing is when the app gets restarted after a sync, debugger disconnect and stop working. Both things should work seamlessly: Sync + Debugger.

**Comment by ventsislav-georgiev** [comment]
@alexrainman could you provide more details:
* Is this on Windows or on Mac?
* Is the debugger left opened with some "Disconnected" message?
* Attach the log files from the session with the issue.
