### ISSUE TITLE
Sidekick v1 Won't Open

### ISSUE THREAD

**Issue by chrisbellman** [NativeScript/sidekick-feedback#87]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Sidekick will no longer open on my machine as of v1. The previous versions opened with errors. I am behind a corporate proxy and believe this may be the cause(?). A reinstall did not fix this. Stuck on splash screen.

### Which platform(s) does the issue occur on?
macOS Sierra

### Provide the following version numbers that the issue occurs with:
Version: 1.0.0-v.2017.11.6.3 (latest)

- **NativeScript Sidekick:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application.

### Does this issue happen every time?
YES

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:

Gist: https://gist.github.com/chrisbellman/0ef5dd62a052298df1c7b8b603854177

<img width="339" alt="nativescript errors" src="https://user-images.githubusercontent.com/4149988/32574670-b9e5b26a-c486-11e7-83e7-5b7cf24941bd.png">

**Comment by chrisbellman** [comment]
It looks like opening Terminal -> turning on proxy -> running `open NativeScript\ Sidekick.app/` may have solved this issue.
I still believe there should be a proxy settings option in the application preferences, or there should be a settings.json file it references on disk where it can pull proxy information from.

**Comment by ventsislav-georgiev** [comment]
@chrisbellman Thank for the report. We don't currently support proxy settings. By enabling the proxy from the terminal you will be able to use all the functionalities that require internet connection from the CLI API in Sidekick (like Cloud Builds). However, any Sidekick only functionalities that require internet won't use the proxy settings (like Plugins management). We are currently working on the proxy support for Sidekick.

**Comment by chrisbellman** [comment]
Strangely, the Terminal -> proxy -> open "trick" no longer seems to work...perhaps something changed in an update? Still hoping for proxy settings!

**Comment by jonathanread** [comment]
I am running in to this same error when opening Sidekick on Ubuntu 17.10. Is there some settings I missed?
