### ISSUE TITLE
Error: Invalid maximum heap size: -Xmx16384M

### ISSUE THREAD

**Issue by marriazamartinez** [NativeScript/sidekick-feedback#89]
### Did you verify whether this issue has already been reported here?
**_Yes**/No_

### Tell us about the problem.
[17-11-09 13:12:58.863] (Error) Error detected during LiveSync on emulator-5554 for 
E:\xxxx. Error: Command gradlew.bat failed with exit code 1 Error output: 
 
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
**Invalid maximum heap size: -Xmx16384M**
The specified size exceeds the maximum representable size.

### Which platform(s) does the issue occur on?
i have windows 10 ,android studio3, jdk 1.8
_iOS/**Android**/Both (if applicable, tell us the specific version of the platform)_ 
_**Windows**/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:
 nativescript last version (installed today) 9/11/2017

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
it happends every time when i run 
tns run android

### Does this issue happen every time?
**_Yes**/No_

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

--- i try  change  -Xmx16384M to Xmx128M in the file:  gradle.properties but this error continues...
its an empty app

**Comment by ahitrov** [comment]
Hi @marriazamartinez,

What is the **bitness** of the JDK specified in the **JAVA_HOME** environment variable?

Currently we do not support 32-Bit JDKs and the error message in that case is the same as the one you are reporting.

**Comment by marriazamartinez** [comment]
thank you very much, that was the problem

2017-11-10 11:15 GMT-04:00 Alex Hitrov <notifications@github.com>:
