### ISSUE TITLE
Build failed with "Pod install command failed"

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/sidekick-feedback#9]
## Please, provide the details below:
This issue was reported via Intercom.

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
``` [17-08-01 08:33:54.534] (Info) Version: 0.2.0-v.2017.7.31.4
[17-08-01 08:33:56.008] (Info) Checking for updates...
[17-08-01 08:34:10.519] (Info) No updates available.
[17-08-01 08:34:28.369] (Info) Dependencies versions: NodeJS: 6.11.1, npm: 3.10.10, NativeScript CLI: 3.1.3.
[17-08-01 08:34:52.511] (Info) Devices service initialized.
[17-08-01 08:35:34.290] (Info) Installed CLI extension nativescript-starter-kits, version 0.1.11.
[17-08-01 08:36:25.134] (Info) Installed CLI extension nativescript-cloud, version 0.11.6.
[17-08-01 08:36:30.163] (Info) Loaded CLI extension nativescript-cloud, version 0.11.6.
[17-08-01 08:36:30.165] (Info) Loaded CLI extension nativescript-starter-kits, version 0.1.11.
[17-08-01 08:48:12.764] (Info) App with name "details" was created in /Users/dotcomholding/Desktop/template.
[17-08-01 08:49:58.528] (Info) Login canceled.
[17-08-01 08:50:53.115] (Info) Build started.
[17-08-01 09:00:04.903] (Error) ab.buildDeploy.shell.build - Pod install command failed. Error output: 
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8
[0m
[17-08-01 09:00:30.112] (Info) Build started.
```

### Which platform(s) does the issue occur on?
Unknown target OS
Unknown host OS

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 0.2.0-v.2017.7.31.4
- **NativeScript CLI:** 3.1.3
- **CLI extension nativescript-cloud:** 0.11.6
- **CLI extension nativescript-starter-kits:** 0.1.11

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. ...

### Does this issue happen every time?
Unknown_Yes/No_

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by teobugslayer** [comment]
Reported 2 times on Intercom.

**Comment by ndinev** [comment]
Try recommendation from the log above:
```
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
```
You can add it to .bash_proflle as well

**Comment by aop4** [comment]
It should also be noted that you have to _restart_ Sidekick after you add the export--just as you'd have to restart the terminal in other cases where you update ~/.bash_profile. Further, those who aren't very familiar with Unix might not realize this is a file in your _user_ root directory, not a file in the application's root directory. It's literally what you reference when you type ~/file_name in your command line.

**Comment by kapiltiwari61** [comment]
Hi guys,

HI @NickIliev, I have updated the iOS runtime but now facing with new issue.
`[19-04-17 17:42:50.093] (CLI) Downloading dependencies [19-04-17 17:42:50.093] (CLI) Installing AFNetworking (3.2.1) [19-04-17 17:42:50.093] (CLI) Installing BEMCheckBox (1.4.1) [19-04-17 17:42:50.093] (CLI) Installing DKCarouselView (2.4.13) [19-04-17 17:42:50.093] (CLI) Installing IQKeyboardManager (5.0.8) [19-04-17 17:42:50.093] (CLI) Installing MBProgressHUD (1.1.0) [19-04-17 17:42:50.093] (CLI) Installing MiniTabBar (1.0.2) [19-04-17 17:42:50.093] (CLI) Installing SDWebImage (4.0.0) [19-04-17 17:42:50.093] (CLI) Installing SignatureView (1.1.0) [19-04-17 17:42:50.093] (CLI) Installing Toaster (2.0.4) [19-04-17 17:42:50.093] (CLI) [!] Unable to determine Swift version for the following pods: [19-04-17 17:42:50.093] (CLI) - MiniTabBar does not specify a Swift version and none of the targets (cdinativescript) integrating it have the SWIFT_VERSIONattribute set. Please contact the author or set theSWIFT_VERSIONattribute in at least one of the targets that integrate this pod. [19-04-17 17:42:50.093] (CLI) -Toaster does not specify a Swift version and none of the targets (cdinativescript) integrating it have the SWIFT_VERSIONattribute set. Please contact the author or set theSWIFT_VERSIONattribute in at least one of the targets that integrate this pod. [19-04-17 17:42:51.578] (CLI) 'pod install' command failed. [19-04-17 17:42:51.578] (CLI) 'pod install' command failed. [19-04-17 17:42:58.820] Build step completed. [19-04-17 17:42:58.846] Build failed. Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:41.896] [WARN] 'pod install' command failed. [00:00:43.206] [ERROR] 'pod install' command failed. 'Build failed with error code 2'.`
