### ISSUE TITLE
iOS: Code Signing Assistance does not work

### ISSUE THREAD

**Issue by tporem** [NativeScript/sidekick-feedback#92]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I try to autogenerate certificate and provisions, 403 Forbidden is returned. I am using free developer account, and can't see the certificates menu in the apple account web overview.

### Which platform(s) does the issue occur on?
iOS: iPhone 5 iOS version 10.3.3
Windows 10

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.0.1-v.2017.11.16.1
- **NativeScript CLI:**  3.3.0
- **CLI extension nativescript-cloud:**  1.0.0
- **CLI extension nativescript-starter-kits:**  0.3.4

### Does this issue happen every time?
Yes

**Comment by ventsislav-georgiev** [comment]
@tporem are you behind proxy or a firewall that may reject the request to our servers?

**Comment by tporem** [comment]
I tried code signing on multiple networks that I believe are not behind the proxy, tried turning off firewalls and there is no change in described behaviour.
When I do not provide correct credentials, I am presented with "Invalid username and / or password.." so it looks like there should not be a problem with connection to the server.

**Comment by ventsislav-georgiev** [comment]
@tporem could you provide the log files from *%AppData%\NativeScriptSidekick\Logs directory*?

**Comment by stvyzxx** [comment]
I have the same issue.

**Comment by sprattek** [comment]
Same here, this is what I've got in logs

`Using NativeScript CLI located in C:\...\AppData\Roaming\npm\node_modules\nativescript
Searching for devices...
(node:18052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Invalid or unexpected token
(node:18052) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[0G[0GDownload progress ... 0% | 252.38 kB | 168.25 kB/s[0G                                                      [0GDownload progress ... 100% | 352.49 kB | 201.42 kB/s[0G                                                        [0GDownload completed.
Starting generation of iOS certificate and provision files.
Starting generation of iOS certificate and provision files.`

**Comment by tporem** [comment]
Here are the logs, but I did not find anything other then the 403 error in them, to be honest.
You will find invalid username / password error there as well, since I tried testing it whether that is not the reason for 403. It is definitely not.
[logs.zip](https://github.com/NativeScript/sidekick-feedback/files/1505682/logs.zip)

**Comment by ventsislav-georgiev** [comment]
We still cannot reproduce the reported issue, however, the Code Signing Assistance relies on a third-party service and we suspect that the issue was only temporary. Could you please verify if the code assistance is working now and if it fails again retry it in 10-15 minutes or so.

**Comment by sprattek** [comment]
@ventsislav-georgiev I have tried it few times today with same result, one thing I noticed is that I'm receiving this error upon sidekick start

[17-11-28 14:36:40.660] (Error) Invalid or unexpected token, C:\Users\Tattek\AppData\Roaming\.nativescript-cli\extensions\node_modules\sshpk\lib\certificate.js:140
	var didOne = fal
	                

> SyntaxError: Invalid or unexpected token
>     at Object.exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:543:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\Tattek\AppData\Roaming\.nativescript-cli\extensions\node_modules\sshpk\lib\fingerprint.js:10:19)
>     at Module._compile (module.js:571:32)

I'll try to reinstall sidekick and I'll let you know if that helps. Thanks.

**Comment by tporem** [comment]
Code Assistance is still not working, it behaves the same any time I try it. Can't it be because I am using the free developer account? With that account I can only download Xcode, maybe Apple changed its policy again?

**Comment by stvyzxx** [comment]
I solved this problem by resetting phone settings to default. Maybe there were some restrictions on the phone.
