### ISSUE TITLE
To run NativeScript Sidekick, your machine needs some additional setup

### ISSUE THREAD

**Issue by aldo-roman** [NativeScript/sidekick-feedback#93]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Installed Sidekick on my machine, all dependencies as well, but it will display the message:
`To run NativeScript Sidekick, your machine needs some additional setup`

### Which platform(s) does the issue occur on?
LinuxMint

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick:** 
- **NativeScript CLI:**  3.3.0
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application

### Does this issue happen every time?
Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by ventsislav-georgiev** [comment]
@aldo-roman check the following reported issues: https://github.com/NativeScript/sidekick-feedback/issues/3 https://github.com/NativeScript/sidekick-feedback/issues/26
