### ISSUE TITLE
Sidekick -- Settings cogwheel never dismisses usage data approval screen

### ISSUE THREAD

**Issue by RyeGuy12** [NativeScript/sidekick-feedback#95]
### Did you verify whether this issue has already been reported here?
YES

### Tell us about the problem.
While trying to walk [through this tutorial here](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/code-signing-assistance) I am stuck on step 3. Whenever I click the settings cog wheel icon, it prompts me to provide approval or disapproval to send usage data to NativeScripts. No matter what I choose, Yes or No, then click save the screen does not disappear. I have tried closing and reopening sidekick and restarting my computer. However every time I navigate to the settings icon I am prompted with this screen and it does NOT go away.

### Which platform(s) does the issue occur on?
macOS

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick: Version: 1.0.1-v.2017.11.16.1 (latest)

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Click iOS on the left side menu
3. Press the setting cog wheel in top right corner
4. The usage data permission screen reappears and does not go away

### Does this issue happen every time?
Yes

**Comment by ventsislav-georgiev** [comment]
@RyeGuy12 the tutorial says you should go to the **Run** menu and then from there click **Run on Device**: 
![image](https://user-images.githubusercontent.com/5616486/33173625-8275de94-d05d-11e7-80d7-57cd1292553b.png)

From there you should click the cog wheel on the device:
![image](https://user-images.githubusercontent.com/5616486/33175597-ed0cd58a-d064-11e7-85d6-e058a5343e77.png)

**Comment by RyeGuy12** [comment]
Thanks this solved my issue!
