### ISSUE TITLE
"Path must be a string. Received undefined" error when building for Android

### ISSUE THREAD

**Issue by netowp** [NativeScript/sidekick-feedback#96]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Sidekick is not building for Android since it will always stop with a `(Error) Path must be a string. Received undefined` error.

### Which platform(s) does the issue occur on?
Android
macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.0.1-v.2017.11.16.1 (latest)
- **NativeScript CLI:** 3.3.0
- **CLI extension nativescript-cloud:** 1.0.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
I can't reproduce this error on other projects.

### Does this issue happen every time?
Yes

### Send the client logs.
My `/Library/Application Support` folder does not have a `NativeScriptSidekick` folder.

**Comment by RustyGumbo** [comment]
I'm getting this error when attempting to either cloud build ios or local build android using Sidekick (it builds fine from VSCode) how did you fix this?
