### ISSUE TITLE
(Error) The service api.npms.io is not available.

### ISSUE THREAD

**Issue by Xsmael** [NativeScript/sidekick-feedback#97]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I get the following error when i try to install a plugin  using sidekick GUI. and it tells me to use the console

### Which platform(s) does the issue occur on?
Android
indows 7 64bits

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

Version: 
1.0.1-v.2017.11.16.1 (latest)
NativeScript CLI version: 3.3.1
CLI extension nativescript-cloud version: 1.0.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Install a fresh verion of NativeScript 3.3
2. Install the latest version of SideKick (as of now)  1.0.1-v.2017.11.16.1

### Does this issue happen every time?
Yes

**Comment by tsvetie** [comment]
@Xsmael, I tested this on my side and I could not reproduce it. Can you give it another try to see if you can still reproduce it? In case you can, send us the log files. You can find them here:

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_
