### ISSUE TITLE
Error on Startup - The server returned unexpected response: TypeError: Cannot read property 'ExceptionMessage' of null

### ISSUE THREAD

**Issue by binghamc** [NativeScript/sidekick-feedback#98]
### Did you verify whether this issue has already been reported here?
YES

### Tell us about the problem.
On startup of SideKick, prompted to accept usage agreement.  Accepted and then toast pops up an error "The server returned unexpected response: TypeError: Cannot read property 'ExceptionMessage' of null"

I have run tns doctor and it reports everything is in order.

### Which platform(s) does the issue occur on?
Windows 7, 64 bit.

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_
Version: 1.0.1-v.2017.11.16.1 (latest)
NativeScript CLI version: 3.3.1
CLI extension nativescript-cloud version: 1.0.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. Accept user agreement
3. Click OK
4. Error message toast pops up
5. Startup splash displays and nothing ever happens
6. Kill application

### Does this issue happen every time?
YES

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
[Logs.zip](https://github.com/NativeScript/sidekick-feedback/files/1507763/Logs.zip)

 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by ivanovit** [comment]
Hi,

Do you have any proxy setup on your system? In case you have a proxy, there may be some issues with the certificate of the proxy server (the proxy server certificate is verified against the list of supplied CAs.)

Could you try to configure the proxy using the cli command passing the [--insecure](https://github.com/NativeScript/nativescript-cli/blob/557cc893bcaca7a132dbb5f3c63545b053c86168/docs/man_pages/general/proxy-set.md#options) param: 
``tns proxy set <url>:<port> --insecure``

Please let us know if this solution works for you.

**Comment by binghamc** [comment]
Hi, no we are not using a proxy server here.  What cert do I need and I can manually import it to where it needs to go if possible.

**Comment by ivanovit** [comment]
Hi,

Since there is no proxy on your system we will continue the investigation of the problem and I will get back to you with more information.

**Comment by ggarabedian** [comment]
Hello @binghamc, 

I’m closing this issue because it has been inactive for a long time. Our further investigation did not turn anything new and we were not able to reproduce the issue locally. We hope that the reported problem was no longer present in the newer version of the NativeScript CLI and Sidekick. 

Please, do not hesitate to reopen the issue if you still encounter this problem with the latest version of the CLI and Sidekick.

Thank you!
